Azure/autorest.java

src/azure/Templates/AzureMethodTemplate.cshtml
src/azure/Templates/PagingMethodTemplate.cshtml
src/azure/Templates/SimulatedPageMethodTemplate.cshtml
src/azurefluent/CodeGeneratorJvaf.cs
src/azurefluent/Model/MethodJvaf.cs
src/vanilla/Model/CompositeTypeJv.cs
src/vanilla/Model/MethodJv.cs
src/vanilla/Model/ParameterJv.cs
src/vanilla/Model/ResponseJv.cs
src/vanilla/Templates/MethodTemplate.cshtml
src/vanilla/Templates/ModelTemplate.cshtml
src/vanilla/Templates/XmlListWrapperTemplate.cshtml

This adds support in the generator for common XML features. Testing this--including XML-related work in autorest.testserver-- is a significant priority, but I want to refactor overload generation first.

Xml list wrappers

---

src/vanilla/ClientModelExtensions.cs
src/vanilla/DanModel/DanCodeGenerator.cs

Addresses #64 and #65.
It sounds when we're doing XML serialization we should get the serialized name from `Property.XmlName`. If we're doing JSON serialization we should just use `Property.SerializedName`.
I'm passing around the `shouldGenerateXmlSerialization` flag because I assume it is still expensive-- it can wind up doing a seek on the entire list of methods in the service looking for XML-related attributes, IIRC.

Fix XML case #64 and use ListWrapper annotation #65

---

src/vanilla/DanModel/DanCodeGenerator.cs

Changes generator to respect XmlIsWrapped for lists and to use the value of XmlName for the root element when serializing class instances.

More XML fixes

---

src/vanilla/DanModel/DanCodeGenerator.cs

An XML list wrapper type allows the name of the root element to be specified when the root object being serialized is a list. The only situation that we serialize to XML in RestProxy is for a body parameter with an XML content type.

Only use XML wrappers for body parameters

---

src/JavaClass.cs
src/JavaCodeGenerator.cs

Fixes https://github.com/Azure/autorest-clientruntime-for-java/issues/365
This is a workaround for a Jackson XML limitation: https://github.com/FasterXML/jackson-dataformat-xml/issues/192
Also fixes a few miscellaneous issues:
- XmlSequenceWrapper had wrong localName annotation argument for constructor parameter
- Flowable<byte[]> was used as the Stream type when getting a default value for an optional body parameter
Here's an example XML class before this generator change:
```java
/**
* The AppleBarrel model.
*/
@JacksonXmlRootElement(localName = "AppleBarrel")
public class AppleBarrel {
/**
* The goodApples property.
*/
@JacksonXmlElementWrapper(localName = "GoodApples")
private List<Apple> goodApples;
/**
* The badApples property.
*/
@JacksonXmlElementWrapper(localName = "BadApples") …
```

Fix XML serialization for composite types containing multiple lists

---

src/JavaCodeGenerator.cs
src/Model/ArrayType.cs
src/Model/ClassType.cs
src/Model/EnumType.cs
src/Model/GenericType.cs
src/Model/IType.cs
src/Model/PrimitiveType.cs
src/Model/ServiceModel.cs
src/Model/ServiceModelProperty.cs
src/Model/XmlSequenceWrapper.cs

This cleanup fixes a problem where Model properties weren't getting the correct types if the `string-dates` flag was specified.
There's also just some other cleanup in here too.

Some more cleanup

---

src/JavaCodeGenerator.cs

This fixes a regression related to headers serialization. When you use `@JacksonXmlProperty`, the attribute values are ignored for JSON serialization, but when you use `@JsonProperty`, the attribute values are also used for XML serialization.
Since we do JSON serialization internally to translate to Headers classes, we weren't serializing using the correct header names, and we would always produce a Headers object with null for every property.
This fix was only tested manually against a Blob Service Swagger because it's been requested that this fix be deployed ASAP.

Use JsonProperty for non-attribute members in XML models

---

src/azure/Model/MethodJva.cs
src/vanilla/CodeNamerJv.cs
src/vanilla/Model/MethodJv.cs

Fixes #150. I expect CI to fail unfortunately because we haven't addressed the BigDecimal issue in the new numbers test spec. AutoRest test server also doesn't really have coverage for `x-ms-skip-url-encoding` in its vanilla suite.

Respect skip-url-encoding extension in vanilla generator

---

test/vanilla/src/test/java/fixtures/header/HeaderOperationsTests.java

The name of this method changed. Just got around to releasing the snapshot.

Fix changed method name in HeaderOperationsTests

---

src/JavaCodeGenerator.cs

The plan here was to only add a Content-Length parameter when the Swagger didn't already have one specified. But we searched for the wrong parameter name.
This really should have a test-- so may delay merging until I can add a simple test Swagger, or append to an existing Swagger to exercise it.

Check for Content-Length instead of Content-Type

---

package.json
src/JavaCodeGenerator.cs

XmlProperties lets us distinguish whether the Swagger actually contained `xml: { name: "..." }` or whether it was inferred based on the name of the property or name of the class in accordance with the spec.
We basically want to use the xml name defined on a model type only if it was explicitly added-- so we have to go searching for it in XmlProperties, and if it's not there, fine, fall back to whatever XmlName was inferred for the property.

Prefer model xml name only if present in XML properties

---

package.json
src/JavaCodeGenerator.cs

Similar to the case for a property's XmlName, we have to check the ElementType.XmlProperties.Name before checking the property's ElementXmlName. I've been hashing this question out for a while and basically concluded that it's not realistic to move the code for these two workarounds over to the modeler.

Prefer the ElementType.XmlProperties.Name if present

---

src/azurefluent/Model/FluentCommon/OtherMethods/OtherMethods.cs

Fixes https://github.com/Azure/autorest.java/issues/276

Fixes the issue of throwing NotImplemented exception when other method returns primitive

---

src/azure/Model/MethodJva.cs
src/azurefluent/Model/FluentCommon/Model/CreatableUpdatableModel.cs
src/azurefluent/Model/NestedFluentResource/NestedFluentModelImpl.cs

* Generate id parsing statements in NestedResource::ctr(inner, manager) body only if the resource is updatable|refreshable
* MethodJva.cs:: Emit body().items() accessor only if body() is of-type PageImpl

Fix for issue #278 (Accessing non-existing id & items property) (#282)

---

src/vanilla/Model/ParameterJv.cs

@anuchandy @lmazuel
I posted this issue (https://github.com/Azure/autorest/issues/3278) and I was advised to create this pull request.
Some implementation class does not have following import statements.
This pull request is resolve this problem.
```
import okhttp3.MediaType;
import okhttp3.RequestBody;
```
Thanks.

Fixing missing import

---

src/azure/Model/CodeModelJva.cs
src/azure/Templates/AzureMethodTemplate.cshtml

@jianghaolu This fix will unblock the SDK generation for the latest (2019-08) network RP, which contains a root method on the service side for LRO.

Fix for service client LRO operations.

---

javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/MethodGroupClient.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
javagen/src/main/java/com/azure/autorest/template/MethodGroupTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java

https://github.com/Azure/autorest.java/issues/442
AzureProxy is probably no longer needed.
AzureEnvironment seems not need to get into Client, but still keep there.
The namespace is certainly going to change.
Build pass now. Remaining issue is the apiVersion param in methods.

fix for fluent

---

javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java

https://github.com/Azure/autorest.java/issues/442
`settings.getPackage() + "." + enumSubpackage` will not work when `enumSubpackage = ""`

fix sealedchoice package

---

javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/transformer/Transformer.java

FIx https://github.com/Azure/autorest.java/issues/477
Currently I did it in Mapper. Second thought that it might better be done in Transform (remove the parent and add a property with that schema). @jianghaolu Let me know which stage you prefer, and I will update the PR.

support additionalProperties in ObjectSchema

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

1. multiple flattened parameter with same origin need to be put in same detail
2. naming in fluent (should be no need to do this in template)

fix multiple flattened parameter with same origin

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java

Azure core will internal convert HEAD response to boolean, if response type is boolean. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L503
So I figure it be safe to just use boolean as response type for HEAD (I also added a condition that 404 is in the status code).
Let me know if data-plane would actually do not want this.
Tested on resources.json, works as expected.

return type Boolean for HEAD request

---

javagen/src/main/java/com/azure/autorest/mapper/ExceptionMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
javagen/src/main/java/com/azure/autorest/util/DefaultNamerFactory.java
javagen/src/main/java/com/azure/autorest/util/ModelNamer.java
javagen/src/main/java/com/azure/autorest/util/NamerFactory.java
tests/src/test/java/fixtures/head/HeadOperationsTests.java

At present, fluent would continue track1 naming for a while, until we can decide whether to make this break.

v4 namer factory + fix exception package for fluent

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

Overload client method with only required parameters.
I choose not to overload XXXWithResponseAsync method. This overload is not useful for fluent. Let me know if you prefer to overload this as well.
Please take a look whether it is OK for you.
If it is OK, I will need to update test cases, since some parameter sequence got updated.

v4 support client method with only required parameters

---

src/azure/Templates/AzureMethodGroupRetrofitTemplate.cshtml
src/azure/Templates/AzureServiceClientRetrofitTemplate.cshtml
src/vanilla/Model/MethodJv.cs
src/vanilla/Model/ParameterJv.cs
src/vanilla/Templates/MethodGroupRetrofitTemplate.cshtml
src/vanilla/Templates/ServiceClientRetrofitTemplate.cshtml

Previously, the generator was treating this MIME type the same as the multipart/form-data MIME type. In fact, these are two unique ways of submitting data to a server, and Retrofit has support for both of them.

Add support for application/x-www-form-urlencoded

---

fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
readme.md

Since method in client is package scope, client and builder must be in same package, else `setHost` will not resolve.
Let me know if you prefer fluent got a separate JavaPackage (maybe when we do lite we really do need to extend it).

v4 fluent still need client builder at same package as client

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
generate
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
vanilla-tests/src/main/java/fixtures/bodyboolean/AutoRestBoolTestService.java
vanilla-tests/src/main/java/fixtures/bodyboolean/AutoRestBoolTestServiceBuilder.java
vanilla-tests/src/main/java/fixtures/bodyboolean/Bools.java

Provide an option to generate async client methods that return `withResponse` to include `Context` as input parameter. This is required for convenience layer to pass in user provided context from sync clients and also add additional context properties like tracing before calling autorest methods..
Fixes #560

Add context to client method

---

fluentnamer/readme.md
javagen/src/main/java/com/azure/autorest/template/EnumTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/test/java/com/azure/autorest/model/JavaFileContentsTests.java

@yungezz @ChenTanyi @xccc-msft 
Note this will force it for all places, regardless what casing used in spec.

v4 fluent naming config, fix javadoc in non-string enum

---

fluentnamer/readme.md
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/DotFish.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/DotSalmon.java
vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java

If the type using these class has @JsonFlatten, the discriminator of "odata.type" will get expanded to "odata: { type: ... }"
azure-core fixed this in https://github.com/Azure/azure-sdk-for-java/issues/10217, though it requires "@JsonFlatten" annotation and escaping of "odata.type".

escape dot in discriminator to avoid it get flatten

---

fluent-tests/prepare-tests.bat
fluent-tests/src/main/java/com/azure/management/AzureServiceClient.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
vanilla-tests/src/main/java/fixtures/bodyboolean/Bools.java

As requested in guideline, sync method need to take `Context` as optional parameter.

v4 sync client method context

---

fluentnamer/readme.md
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java

support "name-for-ungrouped-operations"
@ChenTanyi 
Pushed to `v4_fluentgen` branch.
Try add `--name-for-ungrouped-operations=ResourceProvider`.

mgmt fluent improve

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
generate
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Cookiecuttershark.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Fish.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Goblinshark.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Salmon.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Sawshark.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Shark.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/SmartSalmon.java
vanilla-tests/src/test/java/fixtures/bodycomplex/PolymorphismTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/PolymorphismrecursiveTests.java

This PR adds a new option `required-field-as-ctor-args` that when set to `true` will generate models with constructors that have required fields as args. There will be no setters for required fields when this option is enabled.

Add option to create models with ctor args for required params

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethodType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceAsyncClientTemplate.java

LongRunningBeginSync will generated method with return type `SyncPoller`.
LongRunningBeginAsync will generated method with return type `PollerFlux`.

support beginLRO with SyncPoller

---

azure-tests/src/main/java/fixtures/paging/Pagings.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

For single page async calls, the param grouping arguments were not correctly used to call the proxy method call. This PR fixes the bug.

Fix param grouping proxy method call args

---

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
vanilla-tests/src/main/java/fixtures/bodyfile/Files.java

FIx bug that optional parameter in client method is not inited.
Before fix,
```
@ServiceMethod(returns = ReturnType.COLLECTION)
public PagedFlux<DeploymentResourceInner> listAsync(String resourceGroupName, String serviceName, String appName) {
final Context context = null;
return new PagedFlux<>(
() -> listSinglePageAsync(resourceGroupName, serviceName, appName, version),
nextLink -> listNextSinglePageAsync(nextLink));
}
```
After fix,
```
@ServiceMethod(returns = ReturnType.COLLECTION)
public PagedFlux<DeploymentResourceInner> listAsync(String resourceGroupName, String serviceName, String appName) {
final List<String> version = null;
final Context context = null;
return new PagedFlux<>(
() -> listSinglePageAsync(resourceGroupName, serviceName, appName, version),
nextLink -> …
```

v4 fix optional paramter of wiretype

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ChoiceSchema.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/SealedChoiceSchema.java

The issue is, that there is a few same choices, with different Java name.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/azureFirewall.json#L1048-L1056
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/natGateway.json#L369-L377
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/publicIpPrefix.json#L366-L374
Apparently they need to be in different classes.
So add compare on Java name to hashCode and equals.

v4 need compare Java name in equals check

---

javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
preprocessor/readme.md
vanilla-tests/src/main/java/fixtures/bodycomplex/models/MyKind.java
vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java

The request level content-type should use the more specific `media-type` than the `known-media-type` parameter.

Fix content type to be more specific

---

fluent-tests/pom.xml
fluent-tests/src/main/java/com/azure/resourcemanager/resources/fluentcore/AzureServiceClient.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
fluentnamer/pom.xml
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/MethodPageDetails.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

fix https://github.com/Azure/autorest.java/issues/638
generated code
```
public Mono<PagedResponse<SiteInner>> changeVnetSinglePageAsync(
String resourceGroupName, String name, VirtualNetworkProfile vnetInfo, Context context) {
if (this.client.getEndpoint() == null) {
return Mono
.error(
new IllegalArgumentException(
"Parameter this.client.getEndpoint() is required and cannot be null."));
}
if (resourceGroupName == null) {
return Mono
.error(new IllegalArgumentException("Parameter resourceGroupName is required and cannot be null."));
}
if (name == null) {
return Mono.error(new IllegalArgumentException("Parameter name is required and cannot be null."));
}
if (this.client.getSubscriptionId() == null) {
return Mono
.error(
new …
```

support pagination with 1st page LRO

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java

This PR address a customer issue that was reported where the proxy methods that are reflectively accessed are being flagged as security issue because the interface is private. This PR provides options to generate the proxy service interface as public.
This also moves us a step closer in extracting the interface into its own Java file.
Fixes https://github.com/Azure/azure-sdk-for-java/issues/12829
Related - https://github.com/Azure/autorest.java/issues/635

Add option to make proxy service interface public

---

.gitignore
extension-base/src/main/java/com/azure/autorest/extension/base/jsonrpc/Connection.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMethodGroupMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentTemplateFactory.java
fluentnamer/pom.xml
fluentnamer/src/main/java/com/azure/autorest/fluent/model/FluentType.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ObjectMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java
javagen/src/main/java/com/azure/autorest/template/prototype/MethodTemplate.java
package.json
vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceBuilder.java

1. add init test framework for fluent lite
2. add `defaultPollInterval` to client/builder
3. for fluent lite, generate a complete client class (no longer need base `AzureServiceClient`)
4. support try-catch-finally block

v4 fluentlite service client

---

javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
vanilla-tests/src/main/java/fixtures/bodydate/DateOperations.java
vanilla-tests/src/main/java/fixtures/bodydatetime/DatetimeOperations.java
vanilla-tests/src/main/java/fixtures/bodydatetimerfc1123/Datetimerfc1123s.java
vanilla-tests/src/main/java/fixtures/bodyduration/DurationOperations.java
vanilla-tests/src/main/java/fixtures/bodyinteger/Ints.java
vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java

This PR changes how the media type body-param annotations are generated. If the swagger defines multiple media types, then the body param annotation uses the generic known media type value. If the swagger defines a single media type value, then that will be used for body param annotation.

Fix media types

---

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentResourceCollectionMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentResourceModelMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/arm/ResourceClientModel.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentCollectionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentModelProperty.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceModel.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/WrapperPropertyImplementationMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/WrapperPropertyTypeConversionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionInterfaceTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelInterfaceTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

Sample interface (create/update pending to be put to fluent API).
```
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
package com.azure.mgmtlitetest.storage.models;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.mgmtlitetest.storage.StorageAccountsClient;
import com.azure.mgmtlitetest.storage.models.inner.StorageAccountInner;
/** Resource collection API of StorageAccounts. */
public interface StorageAccounts {
/**
* Checks that the storage account name is valid and is not already in use.
*
* @param name The storage account name.
* @throws IllegalArgumentException …
```

v4, support interface for resoruce collections

---

androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidMapperFactory.java
androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidPrimitiveMapper.java
androidgen/src/main/java/com/azure/autorest/android/model/AndroidClientModel.java
androidgen/src/main/java/com/azure/autorest/android/model/AndroidProxyMethod.java
javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java

Adding mapping in the root mapper, given these types are imported no just for models but also for proxy parameters and client-methods.

Adding mapping for time types, Base64Url, Rfc1123DateTime

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Fish.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Shark.java
vanilla-tests/src/main/java/fixtures/bodynumber/Numbers.java
vanilla-tests/src/main/java/fixtures/bodystring/Enums.java
vanilla-tests/src/main/java/fixtures/bodystring/StringOperations.java
vanilla-tests/src/main/java/fixtures/extensibleenums/Pets.java
vanilla-tests/src/main/java/fixtures/extensibleenums/models/Pet.java

Javadocs for setter methods were getting generating for properties that were marked as required and option to move required fields to ctor was enabled. This PR removes the javadoc when no setter method is generated.

Remove javadoc for setter method when setter method is not generated

---

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java

add package-info for generate-sync-async-clients: true case; 
disable generate-client-interfaces for Android

Fix missing package-info in autorest.java for Android

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceCreate.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/implmethod/WrapperCollectionMethodTypeConversionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/implmethod/WrapperPropertyImplementationMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/implmethod/WrapperPropertyTypeConversionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/TypeConversionUtils.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java

inner to interface for `Response` type.
```
public Response<LegalHold> setLegalHoldWithResponse(
String resourceGroupName, String accountName, String containerName, List<String> tags, Context context) {
Response<LegalHoldInner> inner =
this.inner().setLegalHoldWithResponse(resourceGroupName, accountName, containerName, tags, context);
if (inner != null) {
return new SimpleResponse<>(
inner.getRequest(),
inner.getStatusCode(),
inner.getHeaders(),
new LegalHoldImpl(inner.getValue(), this.manager()));
} else {
return null;
}
}
```

v4 fluentlite, return type conversion for Response<>

---

javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java

Encountered a case that "endpoint" from client (fluent rename the "host" to "endpoint") conflict with "endpoint" from body parameter.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cdn/resource-manager/Microsoft.Cdn/stable/2020-04-15/cdn.json#L606-L614
Tried same if parameter is "host", also conflicts with "$host". So that it might also happens to data-plane.
Tried to do this in `ProxyMethodMapper`, but the current code make is very hard to check duplication, since each parameter is done independently.
```
parameters.add(Mappers.getProxyParameterMapper().map(parameter));
```
Let me know if better solution.

de-duplicate when param name conflict with existing one from client

---

fluentnamer/readme.md

@srnagar 
data-plane might want to do the same.
By default, m4 uses pascal for choice value, which removes "\_" or "-" etc. Then our CodeNamer will add the "\_" as seperator. For some value it produces very unpredictable result (e.g. "Standard_F72s_v2").

v4 fluent, config m4 to use upper for enum value

---

fluent-tests/prepare-tests.bat
fluentnamer/readme.md
javagen/src/main/java/com/azure/autorest/mapper/ChoiceMapper.java
javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java
javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
javagen/src/test/java/com/azure/autorest/util/CodeNamerTests.java

Temporary disable enum value naming by m4. It produces crazy ones like IPv4 -> I_PV4, and TLSv1_1 -> TL_SV1_1
Also collapse multiple underscore in a row to a single underscore.

v4 enum name

---

azure-tests/src/main/java/fixtures/paging/Pagings.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
vanilla-tests/src/main/java/fixtures/bodyboolean/Bools.java

sample code
```
-    public Mono<Response<DeploymentOperationInner>> getAtScopeWithResponseAsync(
+    private Mono<Response<DeploymentOperationInner>> getAtScopeWithResponseAsync(
String scope, String deploymentName, String operationId, Context context) {
if (this.client.getEndpoint() == null) {
return Mono
@@ -399,7 +399,7 @@ public final class DeploymentOperationsClient {
* @return all deployments operations for a deployment.
*/
-    public Mono<PagedResponse<DeploymentOperationInner>> listAtScopeSinglePageAsync(
+    private Mono<PagedResponse<DeploymentOperationInner>> listAtScopeSinglePageAsync(
String scope, String deploymentName, Integer top) {
if (this.client.getEndpoint() == null) {
return …
```

v4, private client method for listSinglePage/listNextPage, and Async with Context

---

azure-tests/src/main/java/fixtures/paging/Pagings.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapperFactory.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
vanilla-tests/src/main/java/fixtures/bodyboolean/Bools.java
vanilla-tests/src/main/java/fixtures/bodyfile/Files.java

Add `ClientMethodMapper.methodVisibility` to have better control on which method is private or no need to generate at all.

v4, let fluent use a different reference on client method visibility

---

fluent-tests/prepare-tests.bat
fluent-tests/spotbugs-exclude.xml
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
generate
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/MethodGroupClient.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/MethodGroupInterfaceTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientInterfaceTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
vanilla-tests/src/main/java/fixtures/bodystring/AutoRestSwaggerBATService.java
vanilla-tests/src/main/java/fixtures/bodystring/Enums.java
vanilla-tests/src/main/java/fixtures/bodystring/StringOperations.java
vanilla-tests/src/main/java/fixtures/bodystring/implementation/AutoRestSwaggerBATServiceImpl.java
vanilla-tests/src/main/java/fixtures/bodystring/implementation/AutoRestSwaggerBATServiceImplBuilder.java
vanilla-tests/src/main/java/fixtures/bodystring/implementation/EnumsImpl.java
vanilla-tests/src/main/java/fixtures/bodystring/implementation/StringOperationsImpl.java
vanilla-tests/src/main/java/fixtures/bodystring/implementation/package-info.java
vanilla-tests/src/test/java/fixtures/bodystring/EnumOperationsTests.java
vanilla-tests/src/test/java/fixtures/bodystring/StringOperationsTests.java

`--generate-client-interfaces` seems broken for quite some time. Attempt to bring it back to life.
sample interface
```
/** An instance of this class provides access to all the operations defined in ResourceGroupsClient. */
public interface ResourceGroupsClient {
/**
* Checks whether a resource group exists.
*
* @param resourceGroupName The name of the resource group to check. The name is case insensitive.
* @throws IllegalArgumentException thrown if parameters fail the validation.
* @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
* @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
* @return whether resource exists.
*/ …
```

v4, fix client interface

---

.github/CODEOWNERS
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/Project.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentManager.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceModel.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentStatic.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java
fluentnamer/readme.md
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
javagen/src/main/java/com/azure/autorest/template/PomTemplate.java

sample command
```
SET AUTOREST_CORE_VERSION=3.0.6324
SET MODELERFOUR_ARGUMENTS=--pipeline.modelerfour.additional-checks=false --pipeline.modelerfour.lenient-model-deduplication=true
SET FLUENTLITE_ARGUMENTS=--java --use:"C:\github_fork\autorest.java" %MODELERFOUR_ARGUMENTS% --azure-arm --fluent=lite --license-header=MICROSOFT_MIT_SMALL --generate-client-interfaces --sync-methods=all --required-parameter-client-methods --add-context-parameter --context-client-method-parameter --track1-naming --client-side-validations --client-logger
CALL autorest --version=%AUTOREST_CORE_VERSION% %FLUENTLITE_ARGUMENTS% --output-folder="sdk/resources/azure-resourcemanager-resource" --sdk-integration --payload-flattening-threshold=0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specific …
```

v4, fluentlite, init integration with azure-sdk-for-java

---

fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ModuleInfo.java
javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
javagen/src/main/java/com/azure/autorest/template/DefaultTemplateFactory.java
javagen/src/main/java/com/azure/autorest/template/ModuleInfoTemplate.java
javagen/src/main/java/com/azure/autorest/template/TemplateFactory.java
javagen/src/main/java/com/azure/autorest/template/Templates.java

data-plane might need it, hence I put the code to javagen (not called in javagen process).
Sample output for Fluent Lite
```
module com.azure.resourcemanager.resources.generated {
requires transitive com.azure.core.management;
exports com.azure.resourcemanager.resources.generated;
exports com.azure.resourcemanager.resources.generated.fluent;
exports com.azure.resourcemanager.resources.generated.fluent.models;
exports com.azure.resourcemanager.resources.generated.models;
opens com.azure.resourcemanager.resources.generated.fluent.models to
com.azure.core,
com.fasterxml.jackson.databind;
opens …
```

v4, module-info support

---

javagen/pom.xml
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/CustomClientParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/CustomProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
vanilla-tests/pom.xml

This PR generates APIs that will use `JsonPatchDocument` type introduced in `azure-core` version 2.10.0 if the REST operations have content-type set to `json-patch+json` and the body param is of type `List<Object>`.

Generate JsonPatchDocument if content type is json-patch+json

---

fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentExceptionMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapperFactory.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMethodGroupMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentObjectMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPrimitiveMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java

swagger is something like this
```
"administratorLoginPassword": {
"type": "string",
"format": "password",
"description": "The password of the administrator login."
}
```

v4 fluent override credential type to string

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentnamer/readme.md

the `getServiceName` method currently is only used in fluent lite. so it is safe to change without affect data-plane.

v4, rename option to service-name

---

androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java
androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceAsyncClientTemplate.java
androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceSyncClientTemplate.java

Skip writing paging functions that use Callback<Page<data>>. Ensure callback is the last parameter of all functions

[Autorest.Android] Hide direct paging functions in generated Clients

---

fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelInterfaceTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/Utils.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
readme.md

sample code
```
/**
* Gets properties of a specified container.
*
* @param id the id of the resource.
* @throws IllegalArgumentException thrown if parameters fail the validation.
* @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
* @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
* @return properties of a specified container.
*/
public BlobContainer getById(String id) {
String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
String accountName = Utils.getValueFromIdByName(id, "storageAccounts");
String containerName = Utils.getValueFromIdByName(id, "containers");
return this.getWithResponse(resourceGroupName, accountName, containerName, Context.NONE).getValue();
} …
```

v4 fluentlite, getById convenient method for Azure resource

---

fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/delete/ResourceDelete.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java

sample
```
public ImmutabilityPolicy getImmutabilityPolicyById(String id) {
String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
if (resourceGroupName == null) {
throw logger
.logExceptionAsError(
new IllegalArgumentException(
String
.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
}
String accountName = Utils.getValueFromIdByName(id, "storageAccounts");
if (accountName == null) {
throw logger
.logExceptionAsError(
new IllegalArgumentException(
String
.format("The resource ID '%s' is not valid. Missing path segment 'storageAccounts'.", id)));
}
String containerName = Utils.getValueFromIdByName(id, "containers");
if (containerName == null) {
throw logger
.logExceptionAsError(
new IllegalArgumentException(
String.format("The …
```

v4 fluentlite, support deleteById

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentMethodParameterMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java

sample code
```
public DataLakeStoreAccountImpl withFirewallRules(List<CreateFirewallRuleWithAccountParameters> firewallRules) {
this.createParameters.withFirewallRules(firewallRules);
return this;
}
public DataLakeStoreAccountImpl withFirewallRulesForUpdate(
List<UpdateFirewallRuleWithAccountParameters> firewallRules) {
this.updateParameters.withFirewallRules(firewallRules);
return this;
}
```

v4 fluentlite, deduplicate method name on generic type of same erasure

---

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/Cat.java
customization-tests/swagger/src/main/java/fixtures/bodycomplex/customization/BodyComplexCustomization.java

When customizing a method's return type, there are cases where we may need to replace the implementation completely and not just format the return value.  This PR enables replacing the entire method with custom logic. 
In the example below, the original generated code returns a `String` value. If the return type has to be changed to a `byte[]` with a special encoding, the `getBytes()` in `String` class throws a checked `UnsupportedEncodingException`. With just the formatter, changing the return type will not be possible as the try-catch block cannot be included in `return String.format(formattedString, returnValue);`
Before:
```java
public String getColor() {
return this.color;
}
```
After:
```java
public byte[] getColor() {
String returnValue = this.color;
String colorStr = returnValue; …
```

Enable customizing the method body when changing return type

---

javagen/src/main/java/com/azure/autorest/mapper/ChoiceMapper.java
javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java
javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java

It might not be all. I didn't add less used ones like `HeaderCollection` and `ResumeOperation`, or more confined ones like `ServiceClient` and `ServiceClientBuilder`.

v4, add common class/annotation of azure-core to reserved words

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentProxyTemplate.java
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java

Encountered a crazy RP.
title: SaaS
operationId: Saa_GetResource -> group Saa -> plural Saas   (this is likely a typo on Saa)
operationId: SaaS_Delete -> group SaaS
Now get 3 classes with name conflict (as case insensitive)...

v4 fluent, check name conflict as case insensitive

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java

Likely caused by error in schema, already asked service to fix ("400" should be "default").
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-04-01-preview/authorization-RoleAssignmentsCalls.json#L132-L145
Alternative we can add additional logic to exclude 4xx for pagination schema, but I think it probably better to just let it fail with improved message.
Hence add code to have a proper Exception for this case.

v4, throw error when no shared common parent found for pagination operation

---

fluent-tests/report.md
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaNameNormalization.java

This kind of rename will be logged as warning:
```
WARNING (SchemaNameNormalization): Rename schema default name, from 'ComponentsQit0EtSchemasManagedclusterpropertiesPropertiesIdentityprofileAdditionalproperties' to 'ManagedClusterPropertiesIdentityProfile'
WARNING (SchemaNameNormalization): Rename schema default name, from 'Components1Umhcm8SchemasManagedclusteridentityPropertiesUserassignedidentitiesAdditionalproperties' to 'ManagedClusterIdentityUserAssignedIdentities'
WARNING (SchemaNameNormalization): Rename schema default name, from 'Components1Q1Og48SchemasManagedclusterAllof1' to 'BaseManagedCluster'
```
For premium, we might need to use `rename-model` option to maintain backward compatibility.

v4 fluent rename unnamed type

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

Root cause is naming conflict in preprocessor.
Before fixing the root cause, for now, throw an Exception on this case.
Sample, note that both `OrganizationResource-properties` and `OrganizationResourceProperties` in default get renamed to same `OrganizationResourceProperties` in java.
```
- &id095
apiVersions:
- {version: 2020-03-01-preview}
extensions: {xmsAzureResource: false, xmsClientFlatten: true, xmsFlattened: true,
xmsLongRunningOperation: false, xmsSkipUrlEncoding: false}
language:
default: {description: Organization resource properties, name: OrganizationResource-properties}
java: {description: Organization resource properties, name: OrganizationResourceProperties}
maxProperties: 0.0
minProperties: 0.0
parents:
all:
- &id098 …
```

v4, throw exception on same parent name

---

fluentnamer/readme.md
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

It is too early to fail in `ModelMapper`. Some model will be flattened and hence not generated, hence it would not hurt if they having problem. Therefore move to `ModelTemplate` which should break since it writes to file (and such Java file will not compile pass).

v4, move exception on parent name conflict to template

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentCollectionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentActionMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/WrapperClientMethodTemplate.java

Add a convenient method `ClientMethod.getMethodInputParameters` (for getting parameters used as method input. When onlyRequiredParameters=true, this excludes optional parameters), as the same pattern is used multiple places, and seems better to add as a class method.
Currently method name in `ClientMethod` might not be very clear. It is hard to tell the difference of `getParameters` and `getMethodParameters` without looking at the source code. Hope adding this `getMethodInputParameters` does not increase this problem.

v4, add ClientMethod.getMethodInputParameters

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Value.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java
javagen/src/main/java/com/azure/autorest/mapper/CustomProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java

Fixes https://github.com/Azure/autorest.java/issues/877
This PR fixes the header param that is annotated with `x-ms-header-collection-prefix`. The generated `@HeaderParam` should use the prefix instead of the name when this extension is included in the swagger definition. Also, the parameter schema should be `DictionarySchema` instead of `StringSchema` when this extension is set. The fix should be done in the modeler but this PR is to temporarily unblock storage.
```java
@Put("/{queueName}")
@ExpectedResponses({201, 204})
@UnexpectedResponseExceptionType(StorageErrorException.class)
Mono<QueuesCreateResponse> create(
@HostParam("url") String url,
@PathParam("queueName") String queueName,
@QueryParam("timeout") Integer timeout,
@HeaderParam("x-ms-meta") String metadata, …
```

Fix header collection prefix params

---

azure-tests/src/main/java/fixtures/azurespecials/AutoRestAzureSpecialParametersTestClient.java
azure-tests/src/main/java/fixtures/azurespecials/AutoRestAzureSpecialParametersTestClientBuilder.java
azure-tests/src/main/java/fixtures/subscriptionidapiversion/MicrosoftAzureTestUrl.java
azure-tests/src/main/java/fixtures/subscriptionidapiversion/MicrosoftAzureTestUrlBuilder.java
customization-tests/src/main/java/fixtures/bodycomplex/AutoRestComplexTestServiceBuilder.java
customization-tests/src/main/java/fixtures/bodycomplex/implementation/AutoRestComplexTestServiceImpl.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
package.json
preprocessor/readme.md
vanilla-tests/src/main/java/fixtures/bodycomplex/AutoRestComplexTestService.java
vanilla-tests/src/main/java/fixtures/bodycomplex/AutoRestComplexTestServiceBuilder.java
vanilla-tests/src/main/java/fixtures/validation/AutoRestValidationTest.java
vanilla-tests/src/main/java/fixtures/validation/AutoRestValidationTestBuilder.java

This PR makes a couple of changes:
- enables configuring service versions through the builder (fixes #889 )
- Fixes compilation failure of generated code when the parameter group name is the same as the proxy method arg name (fixes #902 )

Make service version configurable and fix property name collision

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java

As azure-core is likely upgrading more frequently than azure-core-management.
sample 
```
<dependencies>
<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-core</artifactId>
<version>1.13.0</version> 
</dependency>
<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-core-management</artifactId>
<version>1.1.1</version> 
</dependency>
</dependencies>
```

v4 fluentlite, put core version to pom as well

---

customization-base/pom.xml
extension-base/pom.xml
javagen/pom.xml
postprocessor/pom.xml
postprocessor/src/main/resources/readme/pom.xml
preprocessor/pom.xml

core is currently using 2.11, and Alan is planning to upgrade to 2.12.

v4, update jackson to 2.11.3 to fix security alert

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentConstructorByInner.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentConstructorByName.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java
fluentgen/src/test/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/FluentMethodTests.java

To avoid conflict of e.g. `NetworkManager` with a resource called `NetworkManager`.

v4 fluentlite, use fullname for Manager in impl

---

azure-tests/pom.xml
azure-tests/src/main/java/fixtures/lro/implementation/LROsClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/ProductImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/SkuImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/SubProductImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/Utils.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/ResourceProvidersClientImpl.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/ResourceProvidersImpl.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/Utils.java
fluent-tests/pom.xml
fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
fluentnamer/pom.xml
pom.xml

Some method used in fluentgen is marked as deprecated in current reactor used by SDK repo. Need to update them.

v4 fluent, update reactor via azure-core

---

fluentgen/src/test/java/com/azure/autorest/MockJavagen.java
fluentgen/src/test/java/com/azure/autorest/fluent/TestUtils.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java

Sample swagger https://github.com/Azure/azure-sdk-for-java/blob/f25746c19cfa7818f8ade5a4acfedd6f1d3bb68a/sdk/communication/azure-communication-chat/swagger/swagger.json#L52-L80
Sample proxy method (I've tweaked a bit on the 1st method for testing purpose, added a "default" and another different type for "403"; 2nd method is same as swagger above)
```
@Get("/chat/threads/{chatThreadId}/readReceipts")
@ExpectedResponses({200})
@UnexpectedResponseExceptionType(
value = CommunicationErrorResponse2Exception.class,
code = {403})
@UnexpectedResponseExceptionType(
value = CommunicationErrorResponseException.class,
code = {401, 429})
@UnexpectedResponseExceptionType(CommunicationErrorResponseException.class)
Mono<Response<ChatMessageReadReceiptsCollection>> listChatReadReceipts( …
```

v4 support multiple exceptions

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

Follow model property here https://github.com/Azure/autorest.java/blob/v4/javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java#L197-L208

v4, bug fix, should use property.getWireType().getClientType() if available

---

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ErrorTypeNormalization.java
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaCleanup.java

This would fix that `ErrorAdditionalInfo` not removed, after the error object is replace by shared `ManagementError` in azure-core-management.

v4 fluent, improve model clean up

---

javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java

Today if a client does not have an `endpoint` property, the `tokenCredential` is ignored and not added to the pipeline.
This code adds logic to detect the host parameters and build a default scope based on the host. 
Swagger:
```
...
"host": "quantum.azure.com",
...
```
Java:
```java
if (host == null) {
this.host = "https://quantum.azure.com";
}
...
if (tokenCredential != null) {
policies.add(new BearerTokenAuthenticationPolicy(tokenCredential, String.format("%s/.default", host)));
}
```
Swagger:
```
"x-ms-parameterized-host": {
"hostTemplate": "{Endpoint}/text/analytics/v3.0",
"useSchemePrefix": false,
"parameters": [
{
"$ref": "#/parameters/Endpoint"
}
]
},
```
Java:
```java
if (tokenCredential != null) {
policies.add(new BearerTokenAuthenticationPolicy(tokenCredential, …
```

Generate better default credential scopes

---

customization-base/src/main/java/com/azure/autorest/customization/Customization.java
customization-base/src/main/java/com/azure/autorest/customization/PackageCustomization.java
customization-tests/swagger/src/main/java/BodyComplexCustomization.java
package.json
postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java

This PR adds a new API to package customization to list all classes in a package. The abstract customization method is updated to include a logger, so that an debugging information can be printed out to console for debugginer when users are writing customization code.

Add API to list classes and include logger in customization method

---

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/Editor.java
customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/ls/EclipseLanguageClient.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/ls/EclipseLanguageServerFacade.java

This PR makes the following changes:
**Performance Improvements**
Some code locations that were using `StringWriter` and `PrintWriter` were replaced with using `StringBuilder`. These locations used the writers in a localized and thread-safe manner which meant there was unneeded overhead as they use synchronization to support thread safety. Now, these locations are using `StringBuilder` which isn't thread safe as isn't doesn't synchronize. This results in performance improvements around synchronization and the ability for the operation to leverage better memory locality.
**Ability to Replace Method Parameters**
The ability to replace a methods parameters was added. This API only replaces the method parameters and doesn't update its `@param` Javadocs, so when it is used if the parameter …

Code Customization Performance Improvement and Ability to Replace Method Parameters

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentMethodParameterMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java
fluentgen/src/test/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/FluentMethodTests.java

case https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2020-10-20/workbooks_API.json#L234
parameter got `sourceId`, and `Workbook` model got `sourceId` as well.

v4 fluentlite, bug fix for edge case that parameter got same name as model property

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
preprocessor/readme.md

Constant properties in models were generated with setters and constructor args. This PR prevents the constant property from being settable.

Fix constant params in model

---

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/Editor.java
customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java

Fixes #946 
This PR adds `ConstructorCustomization` which is capable of performing constructor level customizations. Additionally, `addConstructor` and `getConstructor` APIs were added to `ClassCustomization` to enable accessing or creating a `ConstructorCustomization`.

Add ConstructorCustomization

---

generate
generate.bat
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethod.java
javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java
package.json
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/BodyFormsDataURLEncoded.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/BodyFormsDataURLEncodedBuilder.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/Formdataurlencodeds.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/Paths14Hl8BdFormsdataurlencodedPetAddPetidPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/PetFood.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/PetType.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/package-info.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/package-info.java
vanilla-tests/src/test/java/fixtures/bodyformdataurlencoded/FormDataUrlEncodedTests.java

This PR adds support for proxy method params that use `x-www-form-urlencoded` content type to be annotated with `@FormParam`. 
Fixes #1004

Add support for FormParam

---

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/PropertyCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java

This PR makes the following changes:
- Fixed bugs with constructor and method signature extraction when generic parameters or multiple parameters exist.
- Fixed a bug when a replacing a constructor's or method's parameters and there existed a an annotation (ex. `@JsonProperty()`) on a parameter.
- Further centralization of parsing and symbol walking and additional hardening of the logic.

Fixed a Bug Where Adding a Constructor or Method with a Parameterized Parameter Failed

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/CodeSample.java

Use tag proposed in https://github.com/zakhenry/embedme/issues/48, instead of being smart and extract try block.

v4 fluentlite, use embedme tag instead

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsInternalAutorestAnonymousSchema.java

This can offer more info on naming of the model.
Source yaml like this:
```
extensions:
x-internal-autorest-anonymous-schema:
anonymous: true
```

v4, support x-internal-autorest-anonymous-schema extension

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsLongRunningOperationOptions.java

currently only support the m4 output.
real task would be in azure-core-management, and then codegen.
hdinsight need to use this option, else its `azure-async-operation` header is not a valid URL.
```
xmsLongRunningOperationOptions: {finalStateVia: location}
```

v4 fluent, support x-ms-long-running-operation-options

---

customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/Cookiecuttershark.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/Cookiecuttershark.java

Fix https://github.com/Azure/autorest.java/issues/1052
Process `propertyReferences` on parents, and collection the `readOnly` for `Fluent`/`Immutable`. But only add setter methods when flag is on.

v4 fix subclass fluent

---

fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java
fluentgen/src/test/java/com/azure/autorest/fluent/template/FluentExampleTests.java

```
public static void createOrUpdateAPolicyDefinitionWithAdvancedParameters(
com.azure.mgmtlitetest.rp.PolicyManager policyManager) throws IOException {
policyManager
.policyDefinitions()
.define("EventHubDiagnosticLogs")
.withMode("Indexed")
.withDisplayName("Event Hubs should have diagnostic logging enabled")
.withDescription(
"Audit enabling of logs and retain them up to a year. This enables recreation of activity trails for"
+ " investigation purposes when a security incident occurs or your network is compromised")
.withPolicyRule(
SerializerFactory
.createDefaultManagementSerializerAdapter()
.deserialize(
"{\"if\":{\"equals\":\"Microsoft.EventHub/namespaces\",\"field\":\"type\"},\"then\":{\"effect\":\"AuditIfNotExists\",\"details\":{\"type\":\"Microsoft.Insights/diagnosticSettings\", …
```

v4 fluentlite, enhance Object example when the Object is primitive type

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ExampleNode.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentBaseExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentCollectionMethodExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceCreateExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceUpdateExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/UpdateStage.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/UpdateStageMisc.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java
fluentgen/src/test/java/com/azure/autorest/fluent/template/FluentExampleTests.java

sample
```
public static void storageAccountEnableAD(com.azure.mgmtlitetest.storage.StorageManager storageManager) {
StorageAccount resource =
storageManager
.storageAccounts()
.getByResourceGroupWithResponse("res9407", "sto8596", null, Context.NONE)
.getValue();
resource
.update()
.withAzureFilesIdentityBasedAuthentication(
new AzureFilesIdentityBasedAuthentication()
.withDirectoryServiceOptions(DirectoryServiceOptions.AD)
.withActiveDirectoryProperties(
new ActiveDirectoryProperties()
.withDomainName("adtest.com")
.withNetBiosDomainName("adtest.com")
.withForestName("adtest.com")
.withDomainGuid("aebfc118-9fa9-4732-a21f-d98e41a77ae1")
.withDomainSid("S-1-5-21-2400535526-2334094090-2402026252")
.withAzureStorageSid("S-1-5-21-2400535526-2334094090-2402026252-0012")))
.apply();
}
```

v4 fluentlite support resource update in example

---

fluent-tests/src/test/java/com/azure/mgmttest/policy/HttpDebugLoggingPolicy.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java

Add null pointer protection for operation for `nextLink`.
For swagger in https://github.com/Azure/azure-rest-api-specs/pull/14035/files
However the idea on above swagger is probably not correct, as next page should be always in `GET`, not `POST`.
https://github.com/Azure/azure-rest-api-specs/issues/15136
https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-pageable

v4, null pointer guard for operation for nextLink

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java

sample code
```
public static void serverAdministratorCreate(com.azure.resourcemanager.mysql.MySqlManager mySqlManager) {
mySqlManager
.serverAdministrators()
.createOrUpdate(
"testrg",
"mysqltestsvc4",
new ServerAdministratorResourceInner()
.withAdministratorType(AdministratorType.ACTIVE_DIRECTORY)
.withLogin("bob@contoso.com")
.withSid(UUID.fromString("c6b82b90-a647-49cb-8a62-0d2d3cb7ac7c"))
.withTenantId(UUID.fromString("c6b82b90-a647-49cb-8a62-0d2d3cb7ac7c")),
Context.NONE);
}
```

v4 fluentlite, add defaultValueExpressionConverter to UUID

---

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ResourceTypeNormalization.java

If there is more than one super classes, class other than the 1st will be flattened (class erased, properties put to this class). We do not want `Resource` super class get flattened.

v4 fluent, should place Resource as 1st in super classes

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

Add `@JsonInclude(value = JsonInclude.Include.NON_NULL, content = JsonInclude.Include.ALWAYS)` to map, currently only for Fluent.
Some REST API requires setting `null` to a `key` to remove the `key`.

v4 fluent, add @JsonInclude for map

---

fluent-tests/prepare-tests.bat
fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

Case https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/cloudService.json#L2434-L2449
The flattened parameter does not have writable property.
```
UpdateDomainInner parameters = null;
return FluxUtil
.withContext(
context ->
service
.walkUpdateDomain(
this.client.getEndpoint(),
resourceGroupName,
cloudServiceName,
updateDomain,
this.client.getSubscriptionId(),
apiVersion,
parameters,
accept,
context))
.contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
```
Without this fix, the `UpdateDomainInner parameters = null;` will not be generated.

v4, fix case that the flattened parameter has only readonly properties

---

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaCleanup.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
readme.md
vanilla-tests/src/main/java/fixtures/bodyarray/Arrays.java
vanilla-tests/src/main/java/fixtures/bodydatetime/DatetimeOperations.java
vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceAsyncClient.java
vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceClient.java
vanilla-tests/src/main/java/fixtures/bodydictionary/implementation/DictionariesImpl.java
vanilla-tests/src/main/java/fixtures/bodynumber/Numbers.java
vanilla-tests/src/main/java/fixtures/header/Headers.java
vanilla-tests/src/main/java/fixtures/url/Paths.java
vanilla-tests/src/main/java/fixtures/url/Queries.java

Update javadoc on class to include `summary`.
E.g. (summary + description)
```
/**
* Planned maintenance configuration, used to configure when updates can be deployed to a Managed Cluster. See [planned
* maintenance](https://docs.microsoft.com/azure/aks/planned-maintenance) for more information about planned
* maintenance.
*/
```

v4, fix javadoc bug in return value, improve schema clean-up in fluent

---

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentBaseExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentCollectionMethodExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentMethodExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ParameterExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
fluentgen/src/test/java/com/azure/autorest/fluent/template/FluentExampleTests.java
fluentnamer/src/main/java/com/azure/autorest/fluent/model/FluentType.java

It would require `flatten-payload=false`
sample code
```
package com.azure.resourcemanager.resources;
import com.azure.core.management.serializer.SerializerFactory;
import com.azure.core.util.Context;
import com.azure.core.util.serializer.SerializerEncoding;
import com.azure.resourcemanager.resources.fluent.models.PolicyAssignmentInner;
import com.azure.resourcemanager.resources.models.EnforcementMode;
import com.azure.resourcemanager.resources.models.Identity;
import com.azure.resourcemanager.resources.models.NonComplianceMessage;
import com.azure.resourcemanager.resources.models.ParameterValuesValue;
import …
```

v4 fluent sample method for premium

---

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentBaseExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/SampleTemplate.java

inline the sample code in sample.md, instead of let sample.md to link to java files (which having problem link to correct tag in released doc)

v4 fluentlite, update sample.md to inline all java codes

---

androidgen/src/main/java/com/azure/autorest/android/model/clientmodel/AndroidProxyMethod.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodExampleMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethod.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java

1. print it in example for possible reference to swagger
2. in future, test scenario will have an additional input with operationId (but without details on operation like in m4), for constructing a e2e test
3. also add support for `x-ms-original-file` which will be added to m4 in future, to let codegen know the original file of the example

v4, add operationId to ProxyMethod

---

eng/pipelines/ci.yaml
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
package.json

Sample code (this actually caused by wrong swagger, it should have a `ScheduleTrigger` subclass with `type: ScheduleTrigger`)
```java
public static void triggersUpdate(com.azure.mgmtlitetest.rp.DataFactoryManager manager) throws IOException {
TriggerResource resource =
manager
.triggers()
.getWithResponse("exampleResourceGroup", "exampleFactoryName", "exampleTrigger", null, Context.NONE)
.getValue();
resource
.update()
.withProperties(
new Trigger()
.withDescription("Example description")
.withAdditionalProperties(
mapOf(
"typeProperties",
SerializerFactory
.createDefaultManagementSerializerAdapter()
.deserialize(
"{\"recurrence\":{\"endTime\":\"2018-06-16T00:55:14.905167Z\",\"frequency\":\"Minute\",\"interval\":4,\"startTime\":\"2018-06-16T00:39:14.905167Z\",\"timeZone\":\"UTC\"}}", …
```

v4 fluent, sample generation for additional properties

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java

It still not apply to all client method. But IMO better than flags in code.

llc, refactor to use methodVisibility for some client methods

---

.github/CODEOWNERS
fluent-tests/checkstyle-suppressions.xml
fluent-tests/pom.xml
fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java

Also add `generated` segment in namespace, to distinguish them with manual samples.
Updated code owners, after reorg.

v4 fluent, generate samples during fluent CI

---

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java

This might not a best approach.
It requires `FluentGen` and `Androidgen` to fill in `Javagen.instance`, so that `Javagen.getPluginInstance()` works (not being a null), when calling `new PluginLogger(Javagen.getPluginInstance(), ...)`.

v4, enable Javagen plugin logging when runs FluentGen

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ArrayType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/EnumType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/IType.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

Case, some "null" as return value will be rejected by spotbugs.
```
public byte[] data() {
if (this.data == null) {
return null;
}
return this.data.decodedBytes();
}
```
will have
```
Error:  Low: Should com.azure.resourcemanager.keyvault.generated.models.KeyReleasePolicy.data() return a zero length array rather than null? [com.azure.resourcemanager.keyvault.generated.models.KeyReleasePolicy] At KeyReleasePolicy.java:[line 58] PZLA_PREFER_ZERO_LENGTH_ARRAYS
```
This fix would generate
```
public byte[] data() {
if (this.data == null) {
return new byte[0];
}
return this.data.decodedBytes();
}
```
instead.

provide defaultValueExpression for IType

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java

Avoid code like
```
public void foo() {
...
fooWithResponse(...).getValue();
}
```
The last `.getValue()` is required when the method returns an object (to convert `Resposne<Bar>` to `Bar`). But when return type is void, spotbugs will report this unnecessary call.

fluent, fix sportbugs issue

---

javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProtocolExample.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClientProperty.java
javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
javagen/src/main/java/com/azure/autorest/template/ProtocolSampleTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetNotExpandable.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetReferenced.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetReferencedConstant.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutNotExpandable.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutReferenced.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutReferencedConstant.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetEmpty.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetMbcs.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetNotProvided.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetNull.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetWhitespace.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutEmpty.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutMbcs.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutNull.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutWhitespace.java

1. Use Builder pattern for `ServiceClientProperty`, add `required` to it
2. Refactor LLC sample code
3. Fill-in client property if provided in `x-ms-examples`
4. If not provided, but the client property is required, and it has default value, use default value
5. If not provided, but the client property is required, use dummy code to load it from env
Sample output:
```
public static void main(String[] args) {
ClassificationRulesClient client =
new PurviewScanningClientBuilder()
.credential(new DefaultAzureCredentialBuilder().build())
.endpoint("{Endpoint}")
.buildClassificationRulesClient();
RequestOptions requestOptions = new RequestOptions();
Response<BinaryData> response = client.deleteWithResponse("ClassificationRule1", requestOptions, Context.NONE);
}
```
```
public static void …
```

refactor LLC samples

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/XmlSerlializationFormat.java
generate
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/complexxmltag/DefaultValueClient.java
vanilla-tests/src/main/java/fixtures/complexxmltag/DefaultValueClientBuilder.java
vanilla-tests/src/main/java/fixtures/complexxmltag/models/BlobName.java
vanilla-tests/src/main/java/fixtures/complexxmltag/models/package-info.java
vanilla-tests/src/main/java/fixtures/complexxmltag/package-info.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ObjectWithXMsTextProperty.java
vanilla-tests/src/test/java/fixtures/complexxmltag/ComplexXmlTagTests.java
vanilla-tests/swagger/xml-tag-with-attribute-and-value.json

Fixes #1238 
This PR resolves a code generation issue where Swagger `xml` configurations with `x-ms-test: true` were being improperly generated with `JsonProperty` instead of `JacksonXmlText`. This resulted in improper serialization and deserialization behaviors.

Use JacksonXmlText when Swagger Contains x-ms-text: true in XML Section

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Parameter.java
fluent-tests/prepare-tests.bat
fluentnamer/readme.md
generate
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
package.json
preprocessor/readme.md
protocol-tests/src/main/java/fixtures/llcinitial/LLCAsyncClient.java
protocol-tests/src/main/java/fixtures/llcinitial/LLCClient.java
protocol-tests/src/main/java/fixtures/llcinitial/implementation/ParamsImpl.java
protocol-tests/src/main/java/fixtures/llcupdate1/LLCAsyncClient.java
protocol-tests/src/main/java/fixtures/llcupdate1/LLCClient.java
protocol-tests/src/main/java/fixtures/llcupdate1/implementation/ParamsImpl.java
protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesAsyncClient.java
protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java
protocol-tests/src/main/java/fixtures/mediatypes/implementation/MediaTypesClientImpl.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/Formdataurlencodeds.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/PathsPvivzlFormsdataurlencodedPartialconstantbodyPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java
vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java
vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType1.java

`modelerfour.seal-single-value-enum-by-default=true` is added to data-plane, to keep m4 behavior unchanged (as 4.19.x).
deduplication for this case:
```java
@Post("/mediatypes/textAndJson")
@ExpectedResponses({200})
@UnexpectedResponseExceptionType(HttpResponseException.class)
Mono<Response<String>> putTextAndJsonBody(
@HostParam("$host") String host,
@BodyParam("text/plain") String message,
@HeaderParam("Accept") String accept,
Context context);
@Post("/mediatypes/textAndJson")
@ExpectedResponses({200})
@UnexpectedResponseExceptionType(HttpResponseException.class)
Mono<Response<String>> putTextAndJsonBody(
@HostParam("$host") String host,
@BodyParam("application/json") String message,
@HeaderParam("Accept") String accept,
Context context);
```
Codegen now append media type to name if …

use latest autorest.core, m4, and testserver

---

protocol-sdk-integration-tests/test.py

core 3.7.0 seems not there, no idea why autorest uses it.

llc, fix autorest core version in test

---

androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
generate
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
readme.md
vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/AutoRestHeadExceptionTestService.java
vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/AutoRestHeadExceptionTestServiceBuilder.java
vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/HeadExceptions.java
vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/package-info.java
vanilla-tests/src/test/java/fixtures/customhttpexceptionmapping/ValidateExceptionMappingTests.java
vanilla-tests/swagger/custom-http-exception-mapping.md

This PR adds new configurations to AutoRest to enable supporting custom HTTP exception type mappings.
- `--default-http-exception-type` allows for the configuration of the default HTTP exception type.
- `--use-default-http-status-code-to-exception-type-mapping` adds support for a default status code to exception type mapping based on well-known status code to `azure-core` exception types.
- `--http-status-code-to-exception-type-mapping` allows for the configuration of a custom status code to exception type mapping.

Add Support for Custom Http Exception Type Mappings

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/AppleBarrel.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ListContainersResponse.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/StorageServiceProperties.java

Fixes #934 
This PR updates XML code generation to use `JacksonXmlElementWrapper` instead of a private static inner class to maintain the wrapped element list. The change follows better Jackson XML serialization practices as it uses an annotation that Jackson leverages to provide the best serialization experience instead of the more generalized JsonProperty. It also clues Jackson in that the deserialization type is an enumeration whereas with JsonProperty this cannot be determined.

Use JacksonXmlElementWrapper Instead of a Static Inner Wrapper Class

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/AppleBarrel.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ListContainersResponse.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/StorageServiceProperties.java

Reverts Azure/autorest.java#1274
Turns out Jackson has edge cases with wrapped element lists that require the usage of a wrapper class. Until this changes the work done in the previous PR is being reverted.

Revert "Use JacksonXmlElementWrapper Instead of a Static Inner Wrapper Class"

---

preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java

This case is more likely a bug in swagger definition. E.g. define 2 `api-version` parameter in one operation https://github.com/Azure/azure-rest-api-specs-pr/pull/5597#discussion_r761717461
m4 output will be:
```
- $key: Operations
operations:
- apiVersions:
- version: 2021-08-11-preview
parameters:
- *ref_114
- *ref_116
- *ref_115
- *ref_155
- *ref_116
```
I am not sure whether I should throw Exception and abort, or just silently deduplicate as done in this PR.
However I would want to either stop it here, or fix it here, instead of let it get to later stages, which causes non-compliable code, or other obscure error message during codegen.
Do let me know if we have validate case to have 2 same parameter reference in the operation (I think no, but not 100% sure).

client, dedpulicate proxy method parameter item

---

.gitignore
javagen/pom.xml
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/test/java/com/azure/autorest/mapper/JavagenTests.java

related https://github.com/Azure/autorest.java/issues/1256
Current code style is difficult for unit testing. This pr is for refactoring `processInternal()` method in `Javagen` class:
1. organize `Step 1: Parse input yaml as CodeModel` into separate method `parseCodeModel()`.
2. organize `Step 3: Write to templates` into separate method `writeToTemplates()`
So that main flow in `processInternal()` method will look like this:
```java
// Step 1: Parse input yaml as CodeModel
String fileName = files.get(0);
CodeModel codeModel = parseCodeModel(fileName);
// Step 2: Map
Client client = Mappers.getClientMapper().map(codeModel);
// Step 3: Write to templates
JavaPackage javaPackage = writeToTemplates(settings, codeModel, client);
// Step 4:......
```
Will open another pr for adding unit test to …

refactor javagen code

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java

This PR updates Fluent generation to no longer generate a RevApi configuration in the projects POM file. This is being removed as previously all Fluent generated libraries had a specialty exclusion which has been propagated into the RevApi configuration in azure-sdk-for-java, making the specialty configuration no longer necessary therefore meaning the code generation can be removed.

Remove RevApi from Fluent Gen POM

---

javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
protocol-tests/src/main/java/fixtures/lro/LROsAsyncClient.java
protocol-tests/src/main/java/fixtures/lro/LROsClient.java
protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java
vanilla-tests/src/main/java/fixtures/lro/LROs.java
vanilla-tests/src/main/java/fixtures/lro/models/LROsPatch201RetryWithAsyncHeaderHeaders.java
vanilla-tests/src/main/java/fixtures/lro/models/LROsPatch201RetryWithAsyncHeaderResponse.java
vanilla-tests/src/main/java/fixtures/lro/models/LROsPatch202RetryWithAsyncAndLocationHeaderHeaders.java
vanilla-tests/src/main/java/fixtures/lro/models/LROsPatch202RetryWithAsyncAndLocationHeaderResponse.java

This PR removes adding the codesnippet configurations to generated POM files as they are no longer used.

Remove Stale Codesnippet Configurations from Generation

---

javagen/src/main/java/com/azure/autorest/template/ProtocolSampleTemplate.java

fix https://github.com/Azure/autorest.java/issues/1313
case of the parameter not in method signature already fixed in https://github.com/Azure/autorest.java/pull/1311
this PR fix the case of the parameter in method signature (usually path parameter and body parameter).

LLC, fix example generation with x-ms-client-name

---

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java
javagen/src/main/java/com/azure/autorest/Javagen.java
postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java

Current codegen does not work correctly in "batch" mode in autorest.
https://github.com/Azure/azure-sdk-for-java/blob/438424541172d5b19ae5c89a05817f01b5c88414/sdk/purview/azure-analytics-purview-administration/swagger/README_SPEC.md
I haven't dig deep. Quick idea: in batch mode, our module only has 1 instance overall, but autorest call multiple "Process" on our instance to process multiple inputs.
This is only part of the immediate fix. We still have quite some date cached in Mapper, which is likely not correct given different content.
E.g. (this one probably OK as it uses object as key, which is likely to cause conflict)
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java#L59
If possible, future code should avoid …

client, clear data in singleton at Process

---

azure-tests/src/main/java/fixtures/lro/fluent/LROsClient.java
azure-tests/src/main/java/fixtures/lro/fluent/LroRetrysClient.java
azure-tests/src/main/java/fixtures/lro/fluent/LrosCustomHeadersClient.java
azure-tests/src/main/java/fixtures/lro/fluent/LrosaDsClient.java
azure-tests/src/main/java/fixtures/lro/implementation/LROsClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersClientImpl.java
azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsClientImpl.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/fluent/ResourceProvidersClient.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/ResourceProvidersClientImpl.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/util/ReturnTypeDescriptionAssembler.java
javagen/src/main/java/com/azure/autorest/util/returntype/ReturnTypeDescriptionAssembler.java
protocol-tests/src/main/java/fixtures/lro/LROsAsyncClient.java
protocol-tests/src/main/java/fixtures/lro/LROsClient.java
protocol-tests/src/main/java/fixtures/lro/LroRetrysAsyncClient.java
protocol-tests/src/main/java/fixtures/lro/LroRetrysClient.java
protocol-tests/src/main/java/fixtures/lro/LrosCustomHeaderAsyncClient.java
protocol-tests/src/main/java/fixtures/lro/LrosCustomHeaderClient.java
protocol-tests/src/main/java/fixtures/lro/LrosaDsAsyncClient.java
protocol-tests/src/main/java/fixtures/lro/LrosaDsClient.java
protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java
protocol-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java
protocol-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java
protocol-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java
vanilla-tests/src/main/java/fixtures/lro/LRORetrys.java
vanilla-tests/src/main/java/fixtures/lro/LROs.java
vanilla-tests/src/main/java/fixtures/lro/LROsCustomHeaders.java
vanilla-tests/src/main/java/fixtures/lro/LrosaDs.java

Fix https://github.com/Azure/autorest.java/issues/1318
This PR mainly does two thing:
1. Refactor return type javadoc implementation according to suggestion.
2. Fix LRO return type javadoc bug.
Modification done in `ReturnTypeDescriptionAssembler` and `ClientMethodMapper`.

Fix lro javadoc

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
generate
generate.bat
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethodParameter.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethodType.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/template/WrapperClientMethodTemplate.java
protocol-tests/src/main/java/fixtures/dpgcustomization/DpgAsyncClient.java
protocol-tests/src/main/java/fixtures/dpgcustomization/DpgClient.java
protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java
protocol-tests/src/main/java/fixtures/llcupdate1/DpgAsyncClient.java
protocol-tests/src/main/java/fixtures/llcupdate1/DpgClient.java
protocol-tests/src/main/java/fixtures/llcupdate1/implementation/ParamsImpl.java
protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java
protocol-tests/src/test/java/fixtures/dpgcustomization/DpgSendRequestTests.java
protocol-tests/src/test/java/fixtures/dpgupdate/DpgUpdateTests.java
vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceAsyncClient.java
vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceClient.java
vanilla-tests/src/main/java/fixtures/bodydictionary/implementation/DictionariesImpl.java

Fix https://github.com/Azure/autorest.java/issues/1356
- code https://github.com/Azure/autorest.java/commit/f036597657d52ba9a7177afb409538c2f22faa11
- example https://github.com/Azure/autorest.java/pull/1363/commits/54d095e4695f2ff86bb930c56f58c9e026d2d12f
- test https://github.com/Azure/autorest.java/commit/f68d6d4fcf2adbbb00ca76eb321f2a811bc838e0
Client
```java
/**
* Sends the {@code httpRequest}.
*
* @param httpRequest The HTTP request to send.
* @param context The context to associate with this operation.
* @return the response body along with {@link Response}.
*/
@Generated
public Response<BinaryData> sendRequest(HttpRequest httpRequest, Context context) {
return this.serviceClient.sendRequest(httpRequest, context);
}
```
Implementation …

dpg, support sendRequest method

---

javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java

So now it compares Object (usually be a Map or List), instead of String. This way, difference in JSON formatting will not affect result.
```java
Assertions.assertEquals(
BinaryData.fromString(
"{\"name\":\"mycollection1\",\"collectionProvisioningState\":\"Succeeded\",\"friendlyName\":\"Finance\",\"parentCollection\":{\"type\":\"CollectionReference\",\"referenceName\":\"myParentCollection1\"}}")
.toObject(Object.class),
response.getValue().toObject(Object.class));
```

dpg, test codegen, compare Object instead of String

---

protocol-sdk-integration-tests/data-specs.json
protocol-sdk-integration-tests/test.py

Include all released data-plane SDK in smoke test.
At present, the whole list need to be triggered manually via `python protocol-sdk-integration-tests/test.py --all`
CI only test first 2, which cover AADToken and AzureKey, also include samples/tests.
webpubsub is skipped as it does not contain x-ms-examples.

dpg, prepare smoke tests

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/CodeSample.java

Previously it only work for first `@Test`.
Seems nothing would block it from trying to read from next test method.

mgmt, fix extract example from test

---

customization-base/pom.xml
javagen/src/main/java/com/azure/autorest/template/ProtocolSampleBlankTemplate.java
javagen/src/main/java/com/azure/autorest/template/ProtocolSampleTemplate.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetNotExpandable.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetReferenced.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumGetReferencedConstant.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutNotExpandable.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutReferenced.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/EnumPutReferencedConstant.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetEmpty.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetMbcs.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetNotProvided.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetNull.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringGetWhitespace.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutEmpty.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutMbcs.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutNull.java
protocol-tests/src/samples/java/fixtures/bodystring/generated/StringPutWhitespace.java
protocol-tests/src/samples/java/fixtures/url/multi/generated/QueriesArrayStringMultiEmpty.java
protocol-tests/src/samples/java/fixtures/url/multi/generated/QueriesArrayStringMultiNull.java
protocol-tests/src/samples/java/fixtures/url/multi/generated/QueriesArrayStringMultiValid.java

As https://github.com/Azure/azure-sdk-tools/pull/2909, space is not required in `BEGIN`, `END`, `src_embed`, `end`
Remove the space to avoid line break by formatter.
Require codesnippet-maven-plugin 1.0.0-beta.7
Fix https://github.com/Azure/autorest.java/issues/1389

dpg, remove space in sample identifier

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/AutorestSettings.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
package.json

mgmt does not use the readme, so there is not effect.
But DPG is going to rely on readme.java.md in spec repo. And its `output-folder` is better to be consistent as e.g. `$(java-sdks-folder)/sdk/foo/bar` for consistency with other languages.

client, use java-sdks-folder for consistency

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientBuilderTrait.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java

Avoid 2 `httpPipeline` null check and init code in Builder for mgmt.
Previously the httpPipeline in trait will generate some code in `buildClient`, then the one in serviceClient will also generate code.

mgmt, remove duplicate property init code

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
package.json

2 fixes that only apply to mgmt
- ignore Header class in LRO, as LRO does not have a method with Response as return type
- management does not use Trait yet, so skip it

mgmt, bug fix on unused Header class

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseBoolHeaders.java
vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseDoubleHeaders.java
vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseFloatHeaders.java
vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseIntegerHeaders.java
vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseLongHeaders.java

Modifies code generation when `custom-strongly-typed-header-deserialization` is set to true.
- Fixes a bug where multiple `HeaderCollections` would result in the same variable being initialized multiple times (was hardcoded to `headerCollection`).
- Improved handling nullable primitives that were null checked to use primitive parsing instead of nullable parsing to remove boxing of primitives.

Updates to Headers Deserialization

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/FluentProject.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java

Let me know if anyone has concerns over it.
It is not a change that must get in. But it makes dev easier to see which autorest flag takes affect.
---
sample output
```
info    | JavaSettings | Option, string, title : Azure Communication Services
info    | JavaSettings | Option, string, security : AADToken
info    | JavaSettings | Option, string, security-scopes : https://communication.azure.com//.default
info    | JavaSettings | Option, string, security-header-name : null
info    | JavaSettings | Option, string, tag : package-phonenumber-2021-03-07
info    | JavaSettings | Option, string, base-folder : .
info    | JavaSettings | Option, string, output-folder : C:/github/azure-sdk-for-java//sdk/communication/azure-communication-phonenumbersdemo
info    | JavaSettings | Option, string, …
```

log autorest options

---

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java

Fix https://github.com/Azure/autorest.java/issues/1441
`resourceGroupName` is a very useful help method for most Azure resource. First add it to resource that feels "safe" to have it (i.e., those is based on "resourceGroup" in path/ID, and supports both create and update).

mgmt, support resourceGroupName() method

---

customization-base/src/main/java/com/azure/autorest/customization/AnnotationCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/CodeCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/ConstantCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/PropertyCustomization.java
customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java

Fixes #1444 
Fixes #1419 
- Added `ConstantCustomization` to enable customization of static fields, such as on `ExpandableStringEnum` types.
- Added the ability to add imports to `ClassCustomization` directly rather than requiring the use of a method that takes a list of imports to add.
- Added overloads to parameter and body replacement methods in `ConstructorCustomization` and `MethodCustomization` which enable adding imports required by the code modifications.
- Fixed minor bug in `JavadocCustomization` where deprecation tag would be dropped if it was the only javadoc tag.
- Fixed a bug where removing a method without Javadocs but with annotations would leave dangling annotations.

Added Ability to Customize Constants and Miscellaneous Improvements

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/CustomProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodParameter.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/main/java/com/azure/autorest/template/WrapperClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java

This PR changes the `lowLevelClient` term to `dataPlaneClient` to match the JavaSettings name. Also, the term `lowLevelClient` is not longer used.

Change lowlevelclient to dataplaneclient

---

javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java

Case: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json#L8604-L8624
1st allOf is not polymorphic.
2nd allOf `AutoMLVertical` is polymorphic.
Existing code takes first parent to keep, and flatten the rest.
It would fail the polymorphic hierarchy if that polymorphic chain is not via first parent.
Fix: for polymorphic, takes the one in hierarchy as parent to keep.

mgmt, choose parent with polymorphic

---

javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java

the `content-length` in sample is not filled correctly (and the body).
```java
BinaryData file = BinaryData.fromString("\"examplefile.csv\"");
RequestOptions requestOptions = new RequestOptions().addQueryParam("includeTermHierarchy", "true");
SyncPoller<BinaryData, BinaryData> response =
glossaryClient.beginImportGlossaryTermsViaCsvByGlossaryName("Glossary", file, 0L, requestOptions);
```

dpg, fix sample gen, for the List type and primitive type with no value

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
javagen/src/test/java/com/azure/autorest/MockUnitJavagen.java
preprocessor/src/test/java/com/azure/autorest/MockPreprocessor.java

There is certain code that implicitly assume certain pattern for namespace, e.g. not start with `java.lang`.
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java#L158
Ideally, we should throw when namespace is empty or invalid.
But autorest seems having problem when configure is `--java.namespace=<>`, preprocess cannot read it, but javagen can.

client, improve the check of whether type is client model

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/AutorestSettings.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java

sample output (Wes/Laurent ask to use "require" instead of "input-file"):
```yaml
require: c:/github/azure-rest-api-specs/specification/purview/data-plane/Azure.Analytics.Purview.Account/readme.md
output-folder: ../
java: true
regenerate-pom: false
title: PurviewAccountClient
data-plane: true
generate-tests: true
generate-samples: true
namespace: com.azure.analytics.purview.account
service-versions:
- 2019-11-01-preview
```

dpg, use require first, in swagger/readme.md

---

azure-tests/src/main/java/fixtures/lro/LroManager.java
azure-tests/src/main/java/fixtures/lro/implementation/AutoRestLongRunningOperationTestServiceBuilder.java
azure-tests/src/main/java/fixtures/lro/implementation/AutoRestLongRunningOperationTestServiceImpl.java
azure-tests/src/main/java/fixtures/lro/models/ProductPropertiesProvisioningStateValues.java
azure-tests/src/main/java/fixtures/lro/models/SubProductPropertiesProvisioningStateValues.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/LroparameterizedendpointsManager.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/LroWithParamaterizedEndpointsBuilder.java
azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/LroWithParamaterizedEndpointsImpl.java
eng/pipelines/ci.yaml
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ConstantMapper.java
javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
javagen/src/main/resources/data-plane.md
preprocessor/data-plane.md

with a bug fix, that we do not generate test on model if e.g.
```java
public DocumentTranslationsGetTranslationsStatusHeaders(HttpHeaders rawHeaders) {
if (rawHeaders.getValue("Retry-After") != null) {
this.retryAfter = Integer.parseInt(rawHeaders.getValue("Retry-After"));
}
this.eTag = rawHeaders.getValue("ETag");
}
```
as,
1. in future, we might want to make it immutable, i.e., no setter, exception from ctor
2. making the HttpHeaders from headers could be complicated at this stage, and might not worth the effort

DPG, enable CI of maven javadoc for protocol test

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionInterfaceTemplate.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java

used for https://github.com/Azure/azure-sdk-for-java/pull/29582
for now, only expose async methods in `serviceClient()`.

mgmt, option to include async methods

---

javagen/src/main/java/com/azure/autorest/template/EnumTemplate.java
package.json

bug 
```java
@JsonCreator
public static FirewallPolicyIdpsSignatureMode fromInt(int value) {
if (value == null) {
return null;
}
FirewallPolicyIdpsSignatureMode[] items = FirewallPolicyIdpsSignatureMode.values();
for (FirewallPolicyIdpsSignatureMode item : items) {
if (item.toInt() == value) {
return item;
}
}
return null;
}
```
Need to skip null-check when value is primitive.

bug fix, skip null check if enum value is primitive

---

androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java
androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ParameterSynthesizedOrigin.java
javagen/src/main/java/com/azure/autorest/util/MethodUtil.java

PR is only refactor, for future work (so that we can create ClientMethod for DPG as both protocol method and convenience method in one pass), logic should be identical.
We had too much dependency on the `JavaSettings.isDataPlaneClient()`, should try to confine its usage, as basically it is just a global static variable.

DPG, refactor createClientMethods to take isProtocolMethod

---

fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaNameNormalization.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/Utils.java

It is named as "name of parent object" + "singular of property name" (as that property is an array)
PR in https://github.com/Azure/azure-sdk-for-java/pull/30480
source of the problem https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2022-05-15/managedCassandra.json#L1010
Since "dataCenters" and "items" is also unnamed, the final name is now `CassandraClusterPublicStatusDataCentersItemNode` = "CassandraClusterPublicStatus" + "DataCenters" + "Item" (up to this is done by m4) + "Node".

mgmt, auto rename for unnamed array>object

---

.github/CODEOWNERS
cadl-extension/package.json
cadl-tests/cadl-project.yaml
cadl-tests/package.json

currently these version are the latest.
also removed a few not required dependency in cadl-tests (which was used to generate openapi spec for reference).

CADL, specify the version for cadl-lang packages

---

cadl-extension/src/main/java/com/azure/autorest/CadlPlugin.java
cadl-extension/src/main/java/com/azure/cadl/mapper/CadlClientMapper.java
cadl-extension/src/main/java/com/azure/cadl/mapper/CadlMapperFactory.java
cadl-extension/src/main/java/com/azure/cadl/util/ModelUtil.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java

separate logic in Javagen and Cadl.
Javagen distinguishes
1. DPG, no model
2. DPG with setting to generate models (so far not used in production)
3. Other (vanilla and fluent)
For (2) and (3), further check that there exists model as class.
---
Cadl would use the same logic as when writing class.
Basically, the class is used in convenience method, but not only in error response.

cadl, refactor code based on whether model needs to be written to class

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java

1. 1st commit on bug of duplicate `content-type`, one generated by codegen for optional Body, another included in cadl parameter definition
2. 2nd commit on bug of model generation of Header model in convenience method `ResponseBase<ProjectsCreateOrUpdateHeaders, Project> createOrUpdateWithResponse(...)`

Cadl/DPG, bug fix on content-type and header model

---

cadl-extension/package.json
cadl-extension/src/main/java/com/azure/autorest/CadlPlugin.java
cadl-extension/src/main/java/com/azure/cadl/Main.java
cadl-extension/src/test/java/com/azure/cadl/util/ModelUtilTests.java
cadl-tests/generate.sh
cadl-tests/package.json
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPomMapper.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/Pom.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
javagen/src/test/java/com/azure/autorest/JavagenUnitTests.java

for codegen to generate README.md, CHANGELOG.md, etc. in output.
also try generate the pom fitting the SDK repo, if `outputPath` can be reorganized as under `sdk`.
`outputPath` might not be the best option, we might improve later, when we have side-car.
---
```
cadl compile main.cadl --outputPath=../azure-sdk-for-java/sdk/<service>/<module>
```

Cadl, enable sdk-integration

---

cadl-extension/src/emitter.ts
cadl-extension/src/main/java/com/azure/cadl/Main.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModel.java

temporary solution (before side-car is ready)
java.json as
```json
{
"namespace": "com.azure.storage"
}
```
gets to code-model.yaml
```yaml
...
configuration:
namespace: com.azure.storage
```

cadl, load "java.json" and read namespace (temporary solution)

---

cadl-tests/src/test/java/com/models/property/types/BooleanOperationClientTest.java
cadl-tests/src/test/java/com/models/property/types/BytesClientTest.java
cadl-tests/src/test/java/com/models/property/types/CollectionsIntClientTest.java
cadl-tests/src/test/java/com/models/property/types/CollectionsModelClientTest.java
cadl-tests/src/test/java/com/models/property/types/CollectionsStringClientTest.java
cadl-tests/src/test/java/com/models/property/types/DatetimeOperationClientTest.java
cadl-tests/src/test/java/com/models/property/types/DurationOperationClientTest.java
cadl-tests/src/test/java/com/models/property/types/EnumClientTest.java
cadl-tests/src/test/java/com/models/property/types/ExtensibleEnumClientTest.java
cadl-tests/src/test/java/com/models/property/types/FloatOperationClientTest.java
cadl-tests/src/test/java/com/models/property/types/IntClientTest.java
cadl-tests/src/test/java/com/models/property/types/ModelClientTest.java
cadl-tests/src/test/java/com/models/property/types/StringOperationClientTest.java

cadl-ranch has mock api for models/property/types. I added the corresponding tests in our autorest.java.

Add tests for cadl-ranch models/property-types

---

cadl-extension/src/emitter.ts
cadl-tests/src/main/java/com/cadl/testserver/servicedriven1/implementation/ParamsImpl.java
cadl-tests/src/main/java/com/cadl/testserver/servicedriven2/ResiliencyServiceDriven2AsyncClient.java
cadl-tests/src/main/java/com/cadl/testserver/servicedriven2/ResiliencyServiceDriven2Client.java
cadl-tests/src/main/java/com/cadl/testserver/servicedriven2/implementation/ParamsImpl.java

instead of from CWD
test change due to cadl-ranch

cadl-java, find the jar from relative path of the JS file

---

cadl-extension/src/code-model-builder.ts

e.g., on authoring
```
warning: Rename Cadl model 'OptionalProperties<UpdateableProperties<DefaultKeyVisibility<Project, read>>>' to 'ProjectRequest'
warning: Rename Cadl model 'Azure.Core.Foundations.CustomPage<Project, (anonymous model)>' to 'CustomPageProject'
warning: Rename Cadl model 'Azure.Core.Foundations.CustomPage<Deployment, {}>' to 'CustomPageDeployment'
```

cadl, log warning when rename templated model

---

fluent-tests/prepare-tests.bat
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/UnitTestParser.java

bug fix
- no UT for Headers models (too much trouble about `HttpHeaders` in ctor)
- no UT for GET LRO (not supported in core-management)

mgmt, enable generate-tests for fluent lite

---

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java
cadl-extension/src/main/java/com/azure/cadl/Main.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/NewPlugin.java
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/test/java/com/azure/autorest/extension/base/plugin/YamlPropertyTest.java
fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java
preprocessor/src/test/java/com/azure/autorest/MockPreprocessor.java

Fixes #1702 
Resolves a few issues when using custom strongly-typed header deserialization:
- Added direct support for `UUID` and `URL`.
- Added try-catching for `URL` and when `JacksonAdapter` is used.

Fix Issues with HttpHeaders Custom Deserialization

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java

fix https://github.com/Azure/autorest.java/issues/1703
the `nextMethods` is empty since the option is to generate no method at all...

client, avoid error when sync-method=none

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java

fix https://github.com/Azure/autorest.java/issues/1707
Root cause is that the spec has "apps_list_regions_response", hence the model as "AppsListRegionsResponse".
Then there is client response "AppsListRegionsResponse" from "Apps" and "ListRegions".
In usual usage, we recommend `--generic-response-type=true` option.
---
Also fix another issue of conflict with reserved Java keyword ("private" in this case).
Escape name from keyword should happen after camel casing or pascal casing, as changing case would make non-keyword to keyword ("Private" to "private" in this case).

Client, deduplicate class name, avoid Java keyword

---

.gitignore
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/UnitTestParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java
javagen/src/main/java/com/azure/autorest/util/PossibleCredentialException.java

ref https://github.com/Azure/autorest.java/issues/1711
exclude model with JSON object keys that has word "key", "code", "credential", "token".
```
warning | JavaPackage | Skip unit test for model 'AccountInfoSecureInner', caused by key 'apiKey'
warning | JavaPackage | Skip unit test for model 'VMExtensionPayloadInner', caused by key 'ingestionKey'
warning | JavaPackage | Skip unit test for model 'MonitorProperties', caused by key 'ingestionKey'
warning | JavaPackage | Skip unit test for model 'DynatraceEnvironmentProperties', caused by key 'ingestionKey'
warning | JavaPackage | Skip unit test for model 'EnvironmentInfo', caused by key 'ingestionKey'
warning | JavaPackage | Skip unit test for model 'MonitorResourceUpdate', caused by key 'ingestionKey'
```
Though only …

mgmt, improve generated tests

---

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
vanilla-tests/src/main/java/fixtures/bodyfile/Files.java

Fixes #1755 
Replaces `.flatMapMany(Response::getValue)` with `.flatMapMany(fluxByteBufferResponse -> fluxByteBufferResponse.getValue())` to fix a compiler warning in generated code.

Replace Usage of Response::getValue

---

javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java

Fix  this build error: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1912619&view=logs&j=2e58d666-b5db-5758-0ec7-32f7d1b2592f&t=846c2b5b-32b8-5a48-6bf5-0ea739aa23f0&l=104

fix credential check error, add 'secret' as key word

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java

Guards the creation of the basic paging `ClientMethod` with a check against `SyncMethodsGeneration` similar to what is done for the first page retrieval `ClientMethod`. This resolves an issue where a paging overload without `Context` would be generated and attempt to call the get page APIs with `Context` required.

Guard Paging ClientMethod Creation with Check

---

javagen/src/main/java/com/azure/autorest/template/ServiceVersionTemplate.java

`v1.1` previous gets enum value `VV1_1`

dpg, bug fix, extra V when version is v1.1

---

cadl-extension/src/code-model-builder.ts
cadl-extension/src/common/client.ts
cadl-extension/src/common/code-model.ts
cadl-tests/cadl/response.cadl

link https://github.com/Azure/autorest.java/pull/1815
sample yaml
```yaml
clients:
- language:
default:
name: CoreClient
description: Cadl Core
protocol: {}
operationGroups:
- language:
default:
name: ''
description: ''
protocol: {}
$key: ''
operations:
- *ref_20
- *ref_21
- *ref_22
- *ref_23
- language:
default:
name: ResponseClient
description: Response
protocol: {}
operationGroups:
- language:
default:
name: ResponseOp
description: ''
protocol: {}
$key: ResponseOp
operations:
- *ref_24
- *ref_25
- *ref_26
- *ref_27
```
Java part will be much more complex. It should switch to process this "clients", instead of from codemodel.

Cadl, emitter for multi-client

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/mapper/MockUnitTestParser.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentMethodMockUnitTest.java
fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentMethodMockTestTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentMethodTestTemplate.java
fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethod.java
javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/GoblinsharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyDerivedTypeTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SawsharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java

support SimpleSyncRestResponse
using same PR for test https://github.com/Azure/azure-sdk-for-java/pull/31881
mostly this commit https://github.com/Azure/azure-sdk-for-java/pull/31881/commits/edb9a65a8ec921262a51a88232816a7426576b66 (it contains some errors that fixed later)

mgmt, support more type for generated mock test

---

cadl-extension/src/code-model-builder.ts

Fix the bug mentioned for ADP: https://github.com/Azure/autorest.java/issues/1800#issuecomment-1348125787
ADP API view: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1#com.adp.datamanagement.DataManagementClient
ADP generated code: https://github.com/haolingdong-msft/autorest.java/blob/adp-new-codegen/cadl-tests/cadl/adp/DataManagement/cadl-output/src/main/java/com/adp/datamanagement/DataManagementClient.java

fetch operation and add to operationCache if not hit

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/PrimitiveType.java

link https://github.com/Azure/autorest.java/issues/1861
fix generate-tests for keyvault
generated code before: 
```java
Assertions.assertEquals(new Long(), model.properties().attributes().notBefore())
```
after:
```java
Assertions.assertEquals(598622795111508954L, model.properties().attributes().notBefore())
```

fix default value converter for unixtimelong

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
package.json

code is in javagen, but only fluentgen would try to distinguish `nextLink().toString()` for URL and `nextLink()` for String in template.
Though now the default flag is treat URL as String.

mgmt, bug fix, nextLink in parent model

---

cadl-extension/src/code-model-builder.ts
cadl-tests/cadl/union.cadl
cadl-tests/src/main/java/com/cadl/union/UnionServiceVersion.java
cadl-tests/src/main/java/com/resiliency/servicedriven2/ServiceDriven2ServiceVersion.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Client.java
javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java

https://github.com/Azure/autorest.java/issues/1889
`apiVersions` now put under `client` of code-model.
It is not yet a full support for multiple server.

Cadl, support list of versions from Cadl source

---

cadl-tests/pom.xml
customization-base/pom.xml
fluent-tests/pom.xml
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
protocol-sdk-integration-tests/eng/versioning/version_client.txt

will try to enhance the sync_version script, so that it covers `Project.java` and that `version_client.txt` in test folder.

client, bump identity version

---

azure-dataplane-tests/pom.xml
cadl-tests/pom.xml
cadl-tests/src/test/java/com/_specs_/azure/core/CoreTests.java
cadl-tests/src/test/java/com/azure/lro/LroTests.java
eng/versioning/external_dependencies.txt
vanilla-tests/pom.xml

Use `StepVerifier`. No logic change.
Add a test for lro-basic. Cadl-ranch is not correct, hence use protocol API. https://github.com/Azure/autorest.java/pull/1973/commits/71b1295fe06f6a23f16e5231129863dc81eb0ac9

cadl, use reactor-test

---

eng/pipelines/fluent_integration.yaml

Updating used pool to compliant image, v. 2022:
- https://github.com/Azure/azure-sdk-tools/issues/3407

Update pool used by `eng/pipelines/fluent_integration.yaml` to azsdk-pool-mms-win-2022-general / MMS2022Compliant

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java
javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
protocol-sdk-integration-tests/test.py

fix https://github.com/Azure/autorest.java/issues/1979
We likely need to add `-Djacoco.skip` in automation
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/mgmt/automation/generate_data.py#L392

client, default pom enable jacoco

---

cadl-tests/cadl/odata.cadl
cadl-tests/src/main/java/com/cadl/odata/OdataAsyncClient.java
cadl-tests/src/main/java/com/cadl/odata/OdataClient.java
cadl-tests/src/main/java/com/cadl/odata/implementation/OdataClientImpl.java

This was unexpectedly affected, when the default of array in query be changed from csv to multi.

cadl, revert to csv in odata test case

---

azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/implementation/models/PathsV3R3RxOauth2TokenPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java

Use `x-ms-default-value` when stream-style serialization is being generated.

Set Default Value when Stream-Style Serialization is Used

---

azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/OciImageManifest.java
fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentgen/src/main/java/com/azure/autorest/fluent/checker/JavaFormatter.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/SampleTemplate.java
fluentgen/src/test/java/com/azure/autorest/fluent/checker/JavaFormatterTests.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
package.json

https://github.com/Azure/autorest.java/pull/2033/commits/871a245fd438c7bfaa5f2a1b786b2f3f13ef5064
The case when swagger write 404 without schema.
data-plane and mgmt-plane would fallback to different Exception class.
---
Also disable `fixOverlongStringLiteral` (was for overlong string like URL)

mgmt, bug fix on proxy method default Exception

---

Generate-TypeSpec.ps1
fluentgen/src/test/java/com/azure/autorest/fluent/template/FluentExampleTests.java
javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java
javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java

Previously redact happen to Model properties (but not for values in Map)
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2669462&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81&l=102

mgmt, redact "authorization" property, also redact values in Map

---

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/DictionarySchema.java
javagen/src/main/java/com/azure/autorest/mapper/DictionaryMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/MapType.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java
typespec-tests/src/main/java/com/cadl/builtin/BuiltinClient.java
typespec-tests/src/main/java/com/cadl/builtin/implementation/BuiltinClientImpl.java
typespec-tests/src/main/java/com/cadl/builtin/models/Builtin.java
typespec-tests/src/test/java/com/dictionary/NullableFloatValueClientTests.java
typespec-tests/tsp/builtin.tsp

tsp: `Record<float64 | null>`
m4: `nullableItems=true` in DictionarySchema https://github.com/Azure/autorest/blob/main/packages/libs/codemodel/src/model/common/schemas/dictionary.ts#L14
code: `JsonInclude(value = %1$s, content = JsonInclude.Include.ALWAYS)` line on Map
Currently only enabled for DPG.
Mgmt always true.

tsp, support possible null value in Dictionary

---

eng/versioning/external_dependencies.txt
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
protocol-sdk-integration-tests/eng/versioning/version_client.txt

We will use this lib for `OperationLocationPollingStrategy`
https://github.com/Azure/azure-sdk-for-java/pull/34525
The lib should not be included in POM, if this feature is not used in that SDK.
---
If possible, we should use the "external" feature, e.g. https://github.com/Azure/autorest.java/issues/1967
But we may still go with hardcoded reference to azure-core-experimental for this one.

client, add azure-core-experimental in Project

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java

Fixes stream-style serialization generation for Unix times. They were missing configuration on how they should be handled and resulted in an exception being thrown about them not being supported when attempting to generate Key Vault Administration with stream-style serialization.

Fix Stream Style Serialization Generation for Unix Times

---

typespec-tests/src/test/java/com/resiliency/servicedriven/ServiceDrivenTests.java

We not actually support `@added` yet.
But the case of adding optional parameter to no param or only required param would work anyway...

tsp, add test for resiliency case (that works without actually doing the resiliency)

---

typespec-extension/src/code-model-builder.ts
typespec-tests/Generate.ps1

just to output warning
```
warning typespec-java: Unrecognized query parameter type: 'ssv'.
warning typespec-java: Unrecognized query parameter type: 'tsv'.
warning typespec-java: Unrecognized query parameter type: 'pipes'.
```
tsp http lib got bug, that union does not have these.
will wait for their next release, rather than coding `as any` (no one really need these right now, except cadl-ranch).

tsp, warning on unknown query format

---

androidgen/pom.xml
azure-dataplane-tests/pom.xml
azure-tests/pom.xml
customization-base/pom.xml
customization-base/src/main/resources/pom.xml
customization-tests/pom.xml
fluent-tests/pom.xml
fluentgen/src/test/java/com/azure/autorest/fluent/util/RetryOptionsTests.java
fluentnamer/pom.xml
javagen/pom.xml
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
partial-update-tests/pom.xml
protocol-resilience-test/pom.xml
protocol-sdk-integration-tests/eng/versioning/version_client.txt
protocol-tests/pom.xml
typespec-extension/pom.xml
typespec-extension/src/utils.ts
typespec-tests/pom.xml
typespec-tests/src/main/java/com/_specs_/azure/core/traits/TraitsAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/traits/TraitsClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/traits/implementation/TraitsClientImpl.java
typespec-tests/src/test/java/com/_specs_/azure/core/traits/TraitsTests.java
vanilla-tests/pom.xml

manual change after core upgrade https://github.com/Azure/autorest.java/pull/2124/commits/a629bc7a0491a7e311e5ac8025889a428e9d02cf
fix for cadl-ranch upgrade https://github.com/Azure/autorest.java/pull/2124/commits/1e9b08faea01db6ec5bd69d1e3b806b4913b7ea4
remove x-ms-client-request-id from method signature https://github.com/Azure/autorest.java/pull/2124/commits/773558b016b7d27a46c7d9e82ce55f70fd0efb10 (https://github.com/Azure/autorest.java/issues/2064)

client, adapt reflection code, upon sync version with new azure-core

---

fluentgen/pom.xml
fluentgen/src/test/java/com/azure/autorest/fluent/checker/JavaFormatterTests.java

there is some profile in sdk repo to only do this for 
```xml
<activation>
<jdk>[9,)</jdk>
</activation>
```
but probably too much for here (as it already had profiles).

mgmt, disable test as pipeline could be java8

---

eng/pipelines/ci-typespec-java-dev-nightly.yaml

skip no-diff, since there is lots of javadoc diff

tsp, nightly, disable no-diff

---

typespec-extension/changelog.md
typespec-extension/package.json
typespec-extension/src/code-model-builder.ts
typespec-tests/package.json
typespec-tests/src/main/java/com/cadl/response/CoreClientBuilder.java
typespec-tests/src/main/java/com/cadl/response/ResponseAsyncClient.java
typespec-tests/src/main/java/com/cadl/response/ResponseClient.java
typespec-tests/src/main/java/com/cadl/response/ResponseClientBuilder.java
typespec-tests/src/main/java/com/cadl/response/ResponseServiceVersion.java
typespec-tests/src/main/java/com/cadl/response/implementation/CoreClientImpl.java
typespec-tests/src/main/java/com/cadl/response/implementation/ResponseClientImpl.java
typespec-tests/tsp/response.tsp

Enhancement for response error.
"*" is regarded as error, model with `@error` is regarded as error e.g. https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/lib/foundations.tsp#L113-L124
Else be normal response (non-error response).
Most for the case of HEAD with 200+404 response. Detail https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1684272172008?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1684272172008&teamName=Azure%20SDK&channelName=TypeSpec%20(Cadl)%20Discussion%20%F0%9F%90%AE&createdTime=1684272172008

tsp, support head boolean

---

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
typespec-tests/src/main/java/com/encode/duration/implementation/QueriesImpl.java
typespec-tests/src/test/java/com/encode/duration/EncodeDurationTests.java

bug fix of `List<ClientType>` to `List<WireType>` to `String`, in query/header.
bug is in above case, code were directly `List<ClientType>` to `String`, missing the middle convertion.

tsp, fix duration array in query/header

---

typespec-tests/Generate.ps1

use `client.tsp` in cadl-ranch, if exists. If not, use usual `main.tsp`

tsp, cadl-ranch, try use client.tsp if exists

---

javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java
typespec-extension/changelog.md
typespec-extension/package.json
typespec-tests/package.json

fix following, `requestOptions` would trigger spotbugs on dead store.
```java
public SyncPoller<ResourceOperationStatusWidgetWidgetError, Void> beginDeleteWidget(String widgetName) {
// Generated convenience method for beginDeleteWidgetWithModel
RequestOptions requestOptions = new RequestOptions();
return client.beginDeleteWidget(widgetName).getSyncPoller();
}
public PagedIterable<Widget> listWidgets() {
// Generated convenience method for listWidgets
RequestOptions requestOptions = new RequestOptions();
return new PagedIterable<>(client.listWidgets());
}
```
besides the `requestOptions` line, these lines are likely also not required
https://github.com/Azure/autorest.java/blob/9041648f93f87f8a0573f7ae55ecd9eeb3616b51/javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTempla …

tsp, fix dead store in non sync stack

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/PrimitiveType.java
typespec-extension/src/code-model-builder.ts
typespec-extension/src/main/java/com/azure/typespec/mapper/TypeSpecPrimitiveMapper.java
typespec-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java
typespec-tests/src/main/java/com/cadl/builtin/BuiltinClient.java
typespec-tests/src/main/java/com/cadl/builtin/implementation/BuiltinClientImpl.java
typespec-tests/src/main/java/com/cadl/builtin/models/Encoded.java
typespec-tests/src/test/java/com/cadl/builtin/EncodeTests.java
typespec-tests/tsp/builtin.tsp
vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/models/TransformationAsRequiredFields.java

fix https://github.com/Azure/autorest.java/issues/2168
got confirmation that wire type of unixTimestamp is long.

tsp, encode unixTimestamp

---

androidgen/pom.xml
azure-dataplane-tests/pom.xml
azure-tests/pom.xml
customization-base/src/main/resources/pom.xml
customization-tests/pom.xml
fluent-tests/pom.xml
fluentnamer/pom.xml
javagen/pom.xml
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
partial-update-tests/pom.xml
protocol-resilience-test/pom.xml
protocol-sdk-integration-tests/eng/versioning/version_client.txt
protocol-tests/pom.xml
typespec-extension/pom.xml
typespec-extension/src/code-model-builder.ts
typespec-tests/pom.xml
vanilla-tests/pom.xml

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2821774&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cf4477f9-109f-5399-1612-bcbe5909c9f2
`@format` on string should be deprecated. Why it is here?
https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/lib/models.tsp#L262-L263
Anyway, Java treats eTag as String.

tsp, ignore string format=eTag for nightly build

---

fluent-tests/pom.xml
fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
protocol-sdk-integration-tests/eng/versioning/version_client.txt
typespec-extension/changelog.md
typespec-extension/package.json
typespec-extension/src/code-model-builder.ts
typespec-tests/package.json
typespec-tests/pom.xml
typespec-tests/src/test/java/com/_specs_/azure/core/basic/CoreTests.java

Other change
- log warning instead of error when find string `@format` not recognized (fallback to string)
- minor change in test
- bump azure-identity to latest June

tsp, version 0.7.4

---

.github/workflows/generate-test-code.yml
Generate.ps1
fluent-tests/src/test/java/com/azure/mgmttest/policy/HttpDebugLoggingPolicy.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
protocol-tests/src/main/java/fixtures/specialheader/implementation/HeadersImpl.java
typespec-tests/src/main/java/com/_specs_/azure/core/traits/implementation/TraitsClientImpl.java
typespec-tests/src/main/java/com/cadl/specialheaders/implementation/SpecialHeadersClientImpl.java
typespec-tests/src/main/java/com/specialheaders/repeatability/implementation/RepeatabilityClientImpl.java

`HttpHeaders.getValue(String)` is deprecated in core.

client, use HttpHeaders.getValue(HttpHeaderName)

---

javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/template/util/ModelTemplateHeaderHelper.java
typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/_specs_/azure/core/traits/TraitsAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/traits/TraitsClient.java
typespec-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java
typespec-tests/src/main/java/com/cadl/builtin/BuiltinClient.java
typespec-tests/src/main/java/com/cadl/enumservice/EnumServiceAsyncClient.java
typespec-tests/src/main/java/com/cadl/enumservice/EnumServiceClient.java
typespec-tests/src/main/java/com/cadl/naming/NamingAsyncClient.java
typespec-tests/src/main/java/com/cadl/naming/NamingClient.java
typespec-tests/src/main/java/com/cadl/optional/OptionalAsyncClient.java
typespec-tests/src/main/java/com/cadl/optional/OptionalClient.java
typespec-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersAsyncClient.java
typespec-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersClient.java

String based API was deprecated
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RequestOptions.java#L207-L208

tsp, use HttpHeaderName for headers on RequestOptions

---

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/XmlSequenceWrapper.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/XmlSequenceWrapperTemplate.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/implementation/models/BananaWrapper.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/implementation/models/SignedIdentifierWrapper.java

Adds support for XML namespace in more locations in stream-style serialization. 
Internal methods for setting XML wrapped values have been removed as #2182 changed stream-style serialization to no longer need a wrapping class for wrapped XML elements as that is handled within serialization and deserialization in `toXml` and `fromXml`.
Checking the discriminator field for XML deserialization is also fixed for code generation that doesn't have required properties be part of the class constructor.
Also fixes a bug where `ClassCustomization.rename` could rename other classes that ended with the same string as the class being renamed, ex `RuleFilter` being renamed changing the name of `SqlRuleFilter` as both ended with `RuleFilter`. This now checks that the full class name is equal to what is …

Support XML namespaces in more locations in stream-style serialization

---

typespec-extension/src/code-model-builder.ts
typespec-extension/src/models.ts
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/RpcAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/RpcClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/implementation/RpcClientImpl.java

automatically skip the `getImageOperationStatus` op in https://github.com/glecaros/azure-rest-api-specs/blob/8a2813190adba6fcd71460dc1d1e69fe7868025f/specification/cognitiveservices/OpenAI.Inference/routes.tsp#L55-L80, as it was used by LRO `startGenerateImage` in `@pollingOperation`

tsp, skip operation used in pollingOperation

---

typespec-extension/changelog.md
typespec-extension/package.json
typespec-extension/src/code-model-builder.ts
typespec-extension/src/operation-utils.ts
typespec-tests/package.json

fix an issue that tsp does not use LRO template in Azure.Core, but wrote one that almost same as that in Azure.Core
e.g. https://github.com/Azure/azure-rest-api-specs/pull/24382

tsp, enlarge the scope of new lro strategy

---

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java

To avoid model generated with XML support, as mgmt does not depend on jackson-dataformat-xml (so e.g. `JacksonXmlRootElement` in model code won't compile)

mgmt, remove xml from serializationFormats

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/ReadmeTemplate.java
fluentgen/src/main/resources/Readme.txt
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
javagen/src/main/java/com/azure/autorest/template/ReadmeTemplate.java
javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java
javagen/src/main/resources/Readme_protocol.txt

fix https://github.com/Azure/autorest.java/issues/2070
e.g. end of readme.md
```
```
Above would be empty if we cannot find the path ("sdk/datafatory/azure-resourcemanager-datafactory").

client, readme.md include impression pixel

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java

link https://github.com/Azure/autorest.java/issues/2200
We've got a few queries on error when formatting output code, when namespace is not set.
Cause of the error is the code like `package .` or `import .models`.
I figure it be better provide a default namespace, if user does not provide one.
Currently, I use `com.mycompany.app` as https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

client, default namespace as com.mycompany.app

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java

problem: service got a model that inherit from `ErrorResponse`, but the model is not used in Error/Exception (its in 200/202).
https://github.com/Azure/azure-rest-api-specs/blob/1968865/specification/managednetworkfabric/resource-manager/Microsoft.ManagedNetworkFabric/stable/2023-06-15/common.json#L162-L193
This probably not a complete fix, as such model could be used both in success response and error response. But in practice, this case is already extreme rare.
--- 
Also fix of `BinaryData` in sync method return type. Mgmt still uses `Flux<ByteBuffer>`.

mgmt, fix for model inherit error, whether it is used in Exception

---

typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/cadl/flatten/FlattenAsyncClient.java
typespec-tests/src/main/java/com/cadl/flatten/FlattenClient.java
typespec-tests/src/main/java/com/cadl/flatten/implementation/FlattenClientImpl.java
typespec-tests/src/main/java/com/cadl/union/UnionAsyncClient.java
typespec-tests/src/main/java/com/cadl/union/UnionClient.java
typespec-tests/src/main/java/com/cadl/union/implementation/UnionClientImpl.java
typespec-tests/src/main/java/com/parameters/spread/AliasAsyncClient.java
typespec-tests/src/main/java/com/parameters/spread/AliasClient.java
typespec-tests/src/main/java/com/parameters/spread/implementation/AliasImpl.java

Provide a name for model of alias, so that during generateJavadoc, it can find the correct request body model.
Without a name, all model that get flattened would be named as `""`, which causes problem when find the correct one.

tsp, fix javadoc for alias/flatten

---

javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java

Mostly for typespec. 
Even I don't know what will be the body parameter name, after all these templates.
So have "body" as fallback.
Effect https://github.com/Azure/azure-sdk-for-java/pull/35372/commits/03a94311b3481fc7e13538ab73a3613697fa9c9a#diff-675194c20c2981ba3865b41512445e449629a1963a0b0f3308d9b45c38a211bf

client, fallback to "body" for request body

---

fluent-tests/prepare-tests.bat
fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java
fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java
package.json

cause: ErrorDetails shared in exception and output
https://github.com/Azure/azure-rest-api-specs/blob/8fa9b5051129dd4808c9be1f5b753af226b044db/specification/iothub/resource-manager/Microsoft.Devices/stable/2023-06-30/iothub.json#L298-L303
It likely a bug that 404 does not have x-ms-error-response...
It reverted change in https://github.com/Azure/autorest.java/pull/2235, as later it uses another solution (composition instead of inheritance).
Origin issue: https://github.com/Azure/autorest.java/issues/2241

mgmt, bug fix on Error used both in exception and output

---

Generate.ps1
androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidPrimitiveMapper.java
androidgen/src/main/java/com/azure/autorest/android/model/clientmodel/AndroidProxyMethodParameter.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/mapper/CustomProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ArrayType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodParameter.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/PatchModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/util/ModelTemplateHeaderHelper.java
typespec-tests/src/main/java/com/cadl/builtin/models/Encoded.java
typespec-tests/src/main/java/com/cadl/wiretype/models/SubClassBothMismatch.java
typespec-tests/src/main/java/com/encode/bytes/models/Base64UrlBytesProperty.java
vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/models/TransformationAsRequiredFields.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/Sawshark.java
vanilla-tests/src/main/java/fixtures/url/Queries.java

Changes the default behavior in `ArrayType` to return `null` instead of `new byte[0]` when the `defaultValueExpression` is null. To provide a way for backwards compatibility a new configuration `default-byte-array-returns-empty-array` has been added to `JavaSettings`. Additionally, the previous behavior has a minor improvement by reusing a static singleton for the empty byte array instead of creating a new instance on each get call.

Return null by default for byte[] getters

---

javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java
javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java
javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java
readme.md

For cases that response body is not a JSON object, only a JSON string or JSON boolean etc.
Crystal has a pending cadl-ranch test.

tsp, bug fix for response as primitive type

---

fluentnamer/readme.md

```java
public byte[] data() {
if (this.data == null) {
return null;
}
return this.data.decodedBytes();
}
```
```
[ERROR] Low: Should com.azure.resourcemanager.keyvault.generated.models.KeyReleasePolicy.data() return a zero length array rather than null? [com.azure.resourcemanager.keyvault.generated.models.KeyReleasePolicy] At KeyReleasePolicy.java:[line 58] PZLA_PREFER_ZERO_LENGTH_ARRAYS
[ERROR] Low: Should com.azure.resourcemanager.keyvault.generated.models.ManagedHsmKeyReleasePolicy.data() return a zero length array rather than null? [com.azure.resourcemanager.keyvault.generated.models.ManagedHsmKeyReleasePolicy] At ManagedHsmKeyReleasePolicy.java:[line 58] PZLA_PREFER_ZERO_LENGTH_ARRAYS
```
ref change https://github.com/Azure/autorest.java/pull/2317

mgmt, set null-byte-array-maps-to-empty-array to true

---

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java

Single page pageable didn't produce proper Java code and was missing a closing `);`.

Fix regression where single page paging API generates invalid code

---

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
typespec-extension/src/main/java/com/azure/autorest/TypeSpecPlugin.java

Alternative is to do a merge of json files from different tag, e.g. resources + subscriptions + policy + features. But it is unnecessarily complicated.
A bit of hack to generate
```
azure-resourcemanager-resources/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-resources_subscription
```
for `subscriptions`.
instead of
```
azure-resourcemanager-resources/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-resources
```
ref https://github.com/Azure/azure-sdk-for-java/pull/37195

mgmt, add graalvm-config-suffix option

---

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java

fix https://github.com/Azure/autorest.java/issues/2348
`sync-methods=sync-only`
Use `isGenerateAsyncMethods()` and `isGenerateSyncMethods()` for most cases (except for one case of NONE which still generate `SimpleAsyncRestResponse` type; but `SYNC_ONLY` won't).
If `SYNC_ONLY`, do not generate Async proxy methods.
---
tested locally for simple API and pageable API

tsp, generic core, sync-only for sync-methods option

---

azure-tests/src/main/java/fixtures/azureparametergrouping/models/Grouper.java
azure-tests/src/main/java/fixtures/azurespecials/models/Error.java
javagen/src/main/java/com/azure/autorest/implementation/ClientModelPropertiesManager.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
typespec-tests/src/main/java/com/cadl/enumservice/models/Operation.java
typespec-tests/src/main/java/com/cadl/literalservice/models/Model.java
vanilla-tests/src/main/java/fixtures/bodyformdataurlencoded/models/PathsPvivzlFormsdataurlencodedPartialconstantbodyPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java
vanilla-tests/src/main/java/fixtures/bodystring/models/RefColorConstant.java
vanilla-tests/src/main/java/fixtures/constants/models/NoModelAsStringNoRequiredOneValueDefault.java
vanilla-tests/src/main/java/fixtures/constants/models/NoModelAsStringNoRequiredOneValueNoDefault.java
vanilla-tests/src/main/java/fixtures/constants/models/NoModelAsStringRequiredOneValueDefault.java
vanilla-tests/src/main/java/fixtures/constants/models/NoModelAsStringRequiredOneValueNoDefault.java
vanilla-tests/src/main/java/fixtures/validation/models/ChildProduct.java
vanilla-tests/src/main/java/fixtures/validation/models/ConstantProduct.java
vanilla-tests/src/main/java/fixtures/validation/models/Product.java

fix below case
model https://github.com/bterlson/openai-in-typespec/blob/main/fine-tuning/models.tsp#L4-L44
```java
public final class FineTune implements JsonSerializable<FineTune> {
/*
* The object identifier, which can be referenced in the API endpoints.
*/
@Generated private final String id;
/*
* The object type, which is always "fine-tune".
*/
@Generated private final String object = "fine-tune";
...
private FineTune(
String id,
OffsetDateTime createdAt,
OffsetDateTime updatedAt,
...
List<OpenAiFile> resultFiles) {
object = "fine-tune";
...
}
public static FineTune fromJson(JsonReader jsonReader) throws IOException {
...
new FineTune(
id,
object,
createdAt,
updatedAt,
...
}
```
The `object` is a constant, so it should not appear in ctor nor in the place invoking ctor.
This may not be …

client, fix bug on constant property in stream style

---

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java
javagen/src/main/java/com/azure/autorest/template/TemplateHelper.java

may add them back, if they appear again in generic-core
https://github.com/Azure/autorest.java/issues/2322
now we had 1 error in ClientBuilder, no error in ClientImpl, 2 types of errors in Client
sample
ClientBuilder
```java
@Generated
private OpenAiClientImpl buildInnerClient() {
OpenAiClientImpl client = new OpenAiClientImpl(this.createHttpPipeline());
return client;
}
@Generated
private HttpPipeline createHttpPipeline() {
HttpPipeline httpPipeline = HttpPipelineBuilder.createDefaultPipeline();
return httpPipeline;
}
/**
* Builds an instance of OpenAiClient class.
*
* @return an instance of OpenAiClient.
*/
@Generated
public OpenAiClient buildClient() {
return new OpenAiClient(buildInnerClient());
}
```
ClientImpl
```java
public OpenAiClientImpl(HttpPipeline httpPipeline) { …
```

tsp, unbranded, remove Trait, Policy, SerializerAdapter

---

typespec-extension/src/code-model-builder.ts

https://github.com/Azure/azure-rest-api-specs-pr/blob/feature/documentintelligence-tsp/specification/cognitiveservices/DocumentIntelligence/models.tsp#L304-L306 uses "analyzeResult"
However, the extraction logic is built-in core-experimental, it can only handle "result" https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-experimental/src/main/java/com/azure/core/experimental/util/polling/implementation/PostPollResult.java#L9-L17
Maybe we need to make the "result" in core-experimental configurable.

tsp, mitigate lro use of property other than "result"

---

customization-base/pom.xml
customization-base/src/main/java/com/azure/autorest/customization/implementation/ls/EclipseLanguageServerFacade.java

Externalizes the Eclipse language server to download during runtime instead of being bundled into the uber JARs. The language server will be downloaded to a well-known path in the temp directory, `/<temp directory>/autorest-java-language-server`. Since the language server is no longer bundled it allows for different versions to be selected based on the JVM running code generation, right now there is two choices of `1.12.0` while using Java [11, 17) and `1.29.0` when using Java[17,). In the future this may change when there is a new version of Eclipse language server that requires Java 21+.

Move Eclipse language server to download during runtime

---

typespec-extension/package.json
typespec-extension/src/code-model-builder.ts
typespec-extension/src/common/code-model.ts
typespec-extension/src/emitter.ts
typespec-extension/src/main/java/com/azure/autorest/fluent/TypeSpecFluentPlugin.java
typespec-extension/src/main/java/com/azure/typespec/Main.java
typespec-extension/src/main/java/com/azure/typespec/model/EmitterOptions.java

1. When @extension("x-ms-long-running-operation") is present on operation, add x-ms-long-running-operation to operation code model.
2. Switch `fluent` to `arm` in `EmitterOptions`.
3. Remove `typespec-azure-resource-manager` and `typespec-providerhub` from dependencies.
generated LRO method: 
```java
private Mono<TrackedResourceAssociationPropertiesInner> createOrUpdateAsync(String subscriptionId,
String resourceGroupName, String trafficControllerName, String associationName, AssociationInner resource) {
return beginCreateOrUpdateAsync(subscriptionId, resourceGroupName, trafficControllerName, associationName,
resource).last().flatMap(this::getLroFinalResultOrError);
}
```

mpg, support lro

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
typespec-extension/src/code-model-builder.ts
typespec-extension/src/external-schemas.ts
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/RpcAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/RpcClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/implementation/RpcClientImpl.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/standard/StandardAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/standard/StandardClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/lro/standard/implementation/StandardClientImpl.java
typespec-tests/src/main/java/com/cadl/protocolandconvenient/ProtocolAndConvenientAsyncClient.java
typespec-tests/src/main/java/com/cadl/protocolandconvenient/ProtocolAndConvenientClient.java
typespec-tests/src/main/java/com/cadl/protocolandconvenient/implementation/ProtocolAndConvenientClientImpl.java
typespec-tests/src/main/java/com/cadl/union/UnionAsyncClient.java
typespec-tests/src/main/java/com/cadl/union/UnionClient.java
typespec-tests/src/main/java/com/cadl/union/implementation/UnionClientImpl.java
typespec-tests/src/main/java/com/cadl/versioning/VersioningAsyncClient.java
typespec-tests/src/main/java/com/cadl/versioning/VersioningClient.java
typespec-tests/src/main/java/com/cadl/versioning/implementation/VersioningClientImpl.java
typespec-tests/src/test/java/com/_specs_/azure/core/lro/rpc/RpcTests.java
typespec-tests/src/test/java/com/_specs_/azure/core/lro/standard/LroCoreTests.java

`PollResult` moved to azure-core and get renamed to `PollOperationDetails`.

tsp, drop PollResult from core-experimental, use PollOperationDetails in core

---

typespec-tests/src/test/java/com/type/property/optional/BooleanLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/FloatLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/IntLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/StringLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/UnionFloatLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/UnionIntLiteralClientTests.java
typespec-tests/src/test/java/com/type/property/optional/UnionStringLiteralClientTests.java

1. Add test cases for fix [issues#2436](https://github.com/Azure/autorest.java/issues/2436).
2. Now there are four test cases that are not working due to `NullPointer` exception occurs. 
The detail info following as : 
3. Disabled not working test cases, the tag is `NullPointer Cannot invoke "java.lang.Long.longValue()"`.

Add test cases for tsp, cadl-ranch Type/Property/Optional

---

Generate.ps1
eng/pipelines/fluent_integration.yaml
fluent-tests/Initialize-Tests.ps1
fluent-tests/pom.xml
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
typespec-tests/src/main/java/com/type/model/inheritance/nesteddiscriminator/models/GoblinShark.java
typespec-tests/src/main/java/com/type/model/inheritance/nesteddiscriminator/models/SawShark.java
typespec-tests/src/main/java/com/type/model/inheritance/nesteddiscriminator/models/Shark.java

Fixes a bug where models with polymorphic discriminator properties which are also required properties would serialize the polymorphic discriminator property twice. One value would be the constant defined in Swagger and the other would be the value passed during creation of the object. Now, only the property passed during creation of the object will be used.
fluentgen CI now uses Linux as the command script used to prepare test code was ported to PowerShell, now supporting all OSes.

Fix polymorphic discriminator, use Linux for fluentgen CI

---

typespec-tests/src/test/java/com/type/property/valuetypes/DecimalTests.java
typespec-tests/src/test/java/com/type/scalar/DecimalTests.java

wasn't aware there is another decimal test case under type/property/valuetypes

tsp, add missing decimal test for cadl-ranch

---

javagen/src/main/java/com/azure/autorest/Javagen.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ModuleInfo.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java

Previously we rely on the model in azure-core-experimental to figure out whether the generated SDK requires experimental lib.
However, we moved that model into azure-core.
Code is not great. We don't have final design on external lib/model. Maybe future we don't need this code (e.g. the PollingStrategy get moved to azure-core as well); maybe we are going to improve it.

tsp, fix bug that azure-core-experimental missing from pom/module-info

---

eng/pipelines/ci-typespec-java-dev-nightly.yaml

after Patrick switch to `npm ci`, now after update package.json, CI need to run `npm install` first (to generate the new package-lock.json).

eng, fix tsp nightly ci

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
typespec-tests/src/main/java/com/cadl/internal/implementation/models/StandAloneUnion.java
typespec-tests/src/main/java/com/cadl/multipart/models/FormData.java
typespec-tests/src/main/java/com/cadl/union/models/Result.java
typespec-tests/src/main/java/com/cadl/union/models/SendLongOptions.java
typespec-tests/src/main/java/com/cadl/union/models/SubResult.java
typespec-tests/src/main/java/com/payload/multipart/models/MultiPartRequest.java
typespec-tests/src/main/java/com/type/union/models/EnumsOnlyCases.java
typespec-tests/src/main/java/com/type/union/models/GetResponse5.java
typespec-tests/src/main/java/com/type/union/models/MixedLiteralsCases.java
typespec-tests/src/main/java/com/type/union/models/MixedTypesCases.java
typespec-tests/src/main/java/com/type/union/models/StringAndArrayCases.java
typespec-tests/src/test/java/com/cadl/union/UnionTests.java

fix a regression introduced in https://github.com/Azure/autorest.java/pull/2466
test case https://github.com/Azure/autorest.java/commit/8a26a51ada8ce256a718d15a7581622612d52901
remembered the reason I wrote the null protection logic -- the non-azure OpenAI fails the chat completion request upon "function: null"...

tsp, fix regression on BinaryData serialization

---

typespec-tests/customization/src/main/java/CustomizationEncodeBytes.java
typespec-tests/src/main/java/com/encode/bytes/models/Base64UrlArrayBytesProperty.java

In stream-serialization, we don't need the JsonCreator annotations.

tsp, update one test customization code for stream-serialization

---

customization-base/src/main/java/com/azure/autorest/customization/Customization.java
customization-base/src/test/java/com/azure/autorest/customization/AnnotationTests.java
extension-base/src/main/java/com/azure/autorest/extension/base/util/FileUtils.java
fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java
postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java

Adds an environment configuration `codegen.java.temp.directory` which allows for configuring the directory used when creating temporary folders. This allows for a few things:
- Clearer location and management of temporary files generated by Autorest Java. Allows to use a non-standard temporary directory that can more clearly show working files of Autorest Java.
- Potential optimizations of the temporary directory, such as using Windows Dev Drive.

Allow setting the working directory

---

typespec-extension/src/main/java/com/azure/autorest/TypeSpecPlugin.java
typespec-extension/src/main/java/com/azure/typespec/model/EmitterOptions.java

There is a usecase in Event Grid where the `models` package is renamed to `systemevents`. So, enabling the `models-subpackage` option in TypeSpec. This is already supported by autorest.

Add models-subpackage option for TypeSpec

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
typespec-tests/src/main/java/com/cadl/multipart/models/FormData.java
typespec-tests/src/main/java/com/payload/multipart/models/BinaryArrayPartsRequest.java
typespec-tests/src/main/java/com/payload/multipart/models/ComplexPartsRequest.java
typespec-tests/src/main/java/com/payload/multipart/models/JsonArrayPartsRequest.java
typespec-tests/src/main/java/com/payload/multipart/models/JsonPartRequest.java
typespec-tests/src/main/java/com/payload/multipart/models/MultiBinaryPartsRequest.java
typespec-tests/src/main/java/com/payload/multipart/models/MultiPartRequest.java

fix https://github.com/Azure/autorest.java/issues/2473
Add this for case that the model does not need any serialization code.
```java
private static boolean modelRequireSerialization(ClientModel model) {
// TODO (weidxu): any other case? "binary"?
return !model.getSerializationFormats().contains("multipart");
}
```
`model.getSerializationFormats()` is due to https://github.com/Azure/autorest.java/pull/2494 (if any recommendation for this, I can improve here as well)

tsp, remove serialization interface/code from multipart model

---

eng/pipelines/ci-typespec-java.yaml
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourceImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/OperationsImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ResourceManagerUtils.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/TopLevelArmResourceImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/TopLevelArmResourceInterfacesImpl.java

typespec now depends on fluentgen/fluentnamer, so typespec CI cannot exclude fluentgen/fluentnamer folder
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3411946&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=c310a698-906e-53a5-78f7-614142e7c740

eng, typespec now handles mgmt, so we cannot exclude fluent*

---

eng/versioning/sync_versions.py
fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
package.json

```xml
<dependency>
<groupId>net.bytebuddy</groupId>
<artifactId>byte-buddy</artifactId>
<version>1.14.8</version> 
<scope>test</scope>
</dependency>
<dependency>
<groupId>net.bytebuddy</groupId>
<artifactId>byte-buddy-agent</artifactId>
<version>1.14.8</version> 
<scope>test</scope>
</dependency>
```
The tag has prefix `testdep_`.

mgmt, fix bytebuddy version update tag

---

eng/pipelines/ci-typespec-java.yaml
package-lock.json
typespec-tests/package.json

Don't know which version of cadl-ranch now require we set `generatorMode` option
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3419707&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=697bc912-22e6-55aa-4251-5cc4b0487ace

eng, cadl-ranch, it requires generatorMode

---

typespec-extension/changelog.md
typespec-extension/src/code-model-builder.ts

However, saw a critical problem when trying to write a test. The `properties` property is in lib, not in service tsp...
https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/models.tsp#L23
Locally, I've tested on other property. Not checked in. We should got a cadl-ranch case soon.

mgmt, support flattenProperty

---

typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/cadl/armresourceprovider/ArmResourceProviderManager.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/ArmResourceProviderClient.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ArmResourceProviderClientBuilder.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ArmResourceProviderClientImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesClientImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/OperationsClientImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/TopLevelArmResourceInterfacesClientImpl.java

- issue: https://github.com/Azure/autorest.java/issues/2484
Not sure if we want to modify the synthesized server in typespec-azure-resource-manager. Add one in our emitter first.

mpg, add host parameter if `server` is synthesized by `@armProviderNamespace`

---

typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/ChildResourcesInterfacesClient.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourceImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesClientImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/models/ChildResource.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/models/ChildResourcesInterfaces.java
typespec-tests/tsp/arm.tsp

real world case is from storage:
```typespec
objectLevelWorm is ArmResourceActionAsync<
BlobContainer,
void,
void,
BaseParameters<BlobContainer>,
ArmLroLocationHeader
>;
}
```
https://github.com/Azure/azure-rest-api-specs/pull/27553/files#diff-cc363d7071d0375729f9b250b79189bac6cf7fb956d6f399b58c7a558bd214c7R117-R123

mpg, fix void request body

---

javagen/src/main/resources/MultipartFormDataHelper.java
typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-tests/package.json
typespec-tests/src/main/java/com/cadl/multipart/implementation/MultipartFormDataHelper.java
typespec-tests/src/main/java/com/payload/multipart/implementation/MultipartFormDataHelper.java
typespec-tests/src/test/java/com/payload/multipart/MultipartTests.java

tsp, multipart file field can have no filename; update filename encoding

---

typespec-tests/src/test/java/com/cadl/patch/PatchClientTest.java

When a map's key is `null`, it should throw error when doing serialization both in `toJson()` and `toJsonMergePatch()`.
We will throw `NullPointorException` when map's key value is `null`. This PR add a test case for this.

json-merge-patch, add test case for map's key is `null`

---

customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/DotFish.java
customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/DotSalmon.java
extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
readme.md
vanilla-tests/src/main/java/fixtures/bodycomplex/models/DotFish.java
vanilla-tests/src/main/java/fixtures/bodycomplex/models/DotSalmon.java
vanilla-tests/src/main/java/fixtures/inheritance/passdiscriminator/models/MetricAlertCriteria.java
vanilla-tests/src/main/java/fixtures/inheritance/passdiscriminator/models/MetricAlertSingleResourceMultipleMetricCriteria.java
vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/DotFish.java
vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/DotSalmon.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/DotFish.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/DotSalmon.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationimmutableoutput/models/DotFish.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationimmutableoutput/models/DotSalmon.java

Removes the setting `require-x-ms-flattened-to-flatten` as flattening should always require `x-ms-flattened` to be enabled to produce flattened objects.

Remove JSON flatten setting

---

javagen/src/main/java/com/azure/autorest/template/TemplateHelper.java

https://github.com/Azure/azure-sdk-for-java/blob/feature/generic-sdk-core-2/sdk/generic-sdk-core/generic-core/src/main/java/com/generic/core/http/policy/KeyCredentialPolicy.java#L42
Azure KeyCredentialPolicy has overload of both 2 and 3.

tsp, generic KeyCredentialPolicy ctor has 3 arguments

---

typespec-tests/src/test/java/com/_specs_/azure/core/scalar/ScalarTests.java

Add test cases for for tsp, cadl-ranch Azure.Core.Scalar
`put/hearderMethod/query` has no return value, so it only invoke .

tsp, add test for cadl-ranch Azure.Core.Scalar

---

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ArmResourceProviderClientImpl.java
vanilla-tests/src/test/java/fixtures/inheritance/passdiscriminator/ValidateDiscriminatorIsPassedTests.java

Make sure any change to `setKind` won't break Jackson scenario.
a minor code change to avoid mgmt generated code calling deprecated core API
https://github.com/Azure/autorest.java/pull/2622/commits/c9f8a71668d75cfb7610acbe081dbca3654968b7

client, add test case for Jackson serialization

---

typespec-extension/src/code-model-builder.ts
typespec-extension/src/operation-utils.ts

fix https://github.com/Azure/autorest.java/issues/2635
2 fallback logic
- if example folder not found based on CWD, fallback to path relative to `program.projectRoot` https://github.com/Azure/autorest.java/pull/2637/commits/f7c3c321cfc9f8624d55bbb675fa23e7d57fddaf
- if example not found for an `operation`, fallback to check `operation.sourceOperation` https://github.com/Azure/autorest.java/pull/2637/commits/7c92381bc3583a44788feb20a5a2d11b15a244f0

tsp, fix examples loading

---

typespec-tests/src/main/java/com/cadl/optional/OptionalAsyncClient.java
typespec-tests/src/main/java/com/cadl/optional/OptionalClient.java
typespec-tests/src/main/java/com/cadl/optional/implementation/OptionalOpsImpl.java
typespec-tests/src/main/java/com/cadl/optional/models/AllPropertiesOptional.java
typespec-tests/src/main/java/com/cadl/optional/models/Optional.java
typespec-tests/tsp/optional.tsp

The `@encode` should be added on the scalar `type`, not property of union `type | null` (it is `utcDateTime` to be `@encode`, not the property, nor union)
If written as 
```
@encode(DateTimeKnownEncoding.unixTimestamp, int64)
epochDateTimeRequiredNullable: utcDateTime | null;
```
typespec-autorest would be wrong https://github.com/Azure/azure-rest-api-specs/blob/main/specification/ai/data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-02-15-preview/assistants_generated.json#L3411-L3423

tsp, correct way to write encode on scalar

---

javagen/src/main/java/com/azure/autorest/model/javamodel/JavaJavadocComment.java
typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-tests/package.json
typespec-tests/src/main/java/com/cadl/naming/models/DataResponse.java
typespec-tests/tsp/naming.tsp

Previously this seems done by formatting.

tsp, escape tab in javadoc

---

eng/pipelines/publish-typespec-java.yaml

Successful run (with publishing commented out): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3643324&view=logs&j=b996a615-b315-504a-0a4a-ff0f9eb394bb&t=b996a615-b315-504a-0a4a-ff0f9eb394bb

1ES migration for typespec publishing

---

extension-base/src/main/java/com/azure/autorest/extension/base/util/HttpExceptionType.java
javagen/pom.xml
javagen/src/main/java/com/azure/autorest/model/clientmodel/Annotation.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethod.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java
javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java

It seems causing some build failure in preview build https://github.com/Azure/autorest.java/runs/23553740795
And we probably don't want to load jar from places not maven.
pick a few from https://github.com/Azure/autorest.java/pull/2626

tsp, unbranded, temporary remove generic-core as explicit dependency in POM

---

azure-tests/src/main/java/fixtures/azureparametergrouping/models/FirstParameterGroup.java
azure-tests/src/main/java/fixtures/azureparametergrouping/models/Grouper.java
azure-tests/src/main/java/fixtures/azureparametergrouping/models/ParameterGroupingPostMultiParamGroupsSecondParamGroup.java
azure-tests/src/main/java/fixtures/azureparametergrouping/models/ParameterGroupingPostOptionalParameters.java
azure-tests/src/main/java/fixtures/azureparametergrouping/models/ParameterGroupingPostRequiredParameters.java
azure-tests/src/main/java/fixtures/azureparametergrouping/models/ParameterGroupingPostReservedWordsParameters.java
azure-tests/src/main/java/fixtures/azurespecials/models/HeaderCustomNamedRequestIdParamGroupingParameters.java
azure-tests/src/main/java/fixtures/paging/models/CustomParameterGroup.java
azure-tests/src/main/java/fixtures/paging/models/PagingGetMultiplePagesLroOptions.java
azure-tests/src/main/java/fixtures/paging/models/PagingGetMultiplePagesOptions.java
azure-tests/src/main/java/fixtures/paging/models/PagingGetMultiplePagesWithOffsetOptions.java
azure-tests/src/main/java/fixtures/paging/models/PagingGetOdataMultiplePagesOptions.java
extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/SchemaContext.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ImplementationDetails.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java
typespec-tests/src/main/java/com/cadl/flatten/models/SendLongOptions.java
typespec-tests/src/main/java/com/cadl/union/models/SendLongOptions.java
typespec-tests/src/main/java/com/parameters/spread/models/SpreadWithMultipleParametersOptions.java
vanilla-tests/src/main/java/fixtures/modelflattening/models/FlattenParameterGroup.java

`GroupSchema` is used to group method parameters. It does not correspond to a wire JSON model, and hence should not implement `JsonSerializable`.
code https://github.com/Azure/autorest.java/pull/2682/commits/ada2f3322167e4334af73d60593fc54e44429a5b

client, no serialization on GroupSchema

---

typespec-extension/src/main/java/com/azure/typespec/Main.java

The meaning of `sdkIntegration` in ARM is a bit different from that of DPG.
Basically it should be always enabled, if target is the SDK repo.
---
One remaining problem is the tag in readme/changelog/pom.
Swagger readme have tag, but there is no such concept in typespec. Still not sure how we best handle this. Maybe we need an emitter option, e.g. `readme-tag`.

tsp, mgmt, sdk integration

---

typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-extension/src/code-model-builder.ts
typespec-extension/src/type-utils.ts
typespec-tests/package.json
typespec-tests/src/main/java/com/cadl/versioning/VersioningServiceVersion.java

fix https://github.com/Azure/autorest.java/issues/2723
1. Let `ServiceVersion` contain only versions no later than the pinned api-version.
2. If pinned api-version(or default latest api-version) is stable, make `ServiceVersion` contain only stable versions.
3. Removed previous emitter logic of filtering operations/parameters/model(Properties). TCGC would do it now.

dpg, make `ServiceVersion` only contain api-versions no later than the pinned one

---

javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishMarketTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotSalmonTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/FishTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/GoblinsharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyBaseTypeTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyDerivedTypeTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/ReadonlyObjTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SalmonTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SawsharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SharkTests.java
vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java

fix https://github.com/Azure/autorest.java/issues/2725
Previously the clientmodel Model does not include PolymorphicDiscriminator property.
tested in https://github.com/Azure/azure-sdk-for-java/pull/39950
we have this mock test in e.g. https://github.com/Azure/autorest.java/blob/main/vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java but we seems not run it.

client, test gen, exclude PolymorphicDiscriminator property from mock data

---

typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-armresourceprovider-generated/reflect-config.json
typespec-tests/tsp/arm.tsp

`typespec-azure-resource-manager` has fixed the naming issue: https://github.com/Azure/typespec-azure/pull/762
Our special handling for `Resource`, `ProxyResource` and `ArmResource` is no longer needed.

arm, remove special handling for ARM types

---

fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java
fluent-tests/swagger/schema-cleanup.json
fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaCleanup.java

fix https://github.com/Azure/autorest.java/pull/2698#discussion_r1596521990
~~Currently, include all schema's parents into calculation. Yet to see whether this is an overkill...~~
Previous schema clean up logic:
1. Rough calculate unused schemas set
2. Properties of schemas are in use, remove them from unused schemas set
3. Schemas in operation requests are in use, remove them from unused schemas set
4. Schemas in operation responses are in use, remove them from unused schemas set
5. Schemas in Exceptions are in use, remove them from unused schemas set
This PR adds an extra schema in use:
For schema in schemasInUse, its collection parents(Dictionary, Array)'s element schemas are in use, remove them from unused schemas set.

mgmt, schemacleanup bug fix

---

javagen/src/main/java/com/azure/autorest/implementation/ClientModelPropertiesManager.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/AccessPolicy.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/Blob.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/BlobPrefix.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/BlobProperties.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/Container.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/ContainerProperties.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/CorsRule.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/ListBlobsResponse.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/ListContainersResponse.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/Logging.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/Metrics.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/RetentionPolicy.java
vanilla-tests/src/main/java/fixtures/streamstylexmlserialization/models/SignedIdentifier.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/AccessPolicy.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/Blob.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/BlobPrefix.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/BlobProperties.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/Container.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ContainerProperties.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/CorsRule.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ListBlobsResponse.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/ListContainersResponse.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/Logging.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/Metrics.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/RetentionPolicy.java
vanilla-tests/src/main/java/fixtures/xmlservice/models/SignedIdentifier.java

Fixes an issue where XML stream-style serialization was serializing and deserializing the polymorphic property multiple times. This was due to a recent change where polymorphic properties are now retained as formal properties within the `ClientModel` rather than being inferred. Resulting in a polymorphic property each time there was a super type and again for the model itself.

Fix polymorphic XML stream-style serialization

---

eng/pipelines/post-publish-sdk.yaml
eng/sdk/sync_sdk.py

When DevPackage=true, the pipeline would use the local build of the branch, to regen SDKs.
It would let us see what can change, before release typespec-java.
test, dev https://github.com/Azure/azure-sdk-for-java/pull/40173
non-dev https://github.com/Azure/azure-sdk-for-java/pull/40174

eng, add a DevPackage mode to sync sdk pipeline

---

typespec-extension/src/code-model-builder.ts

https://github.com/Azure/azure-sdk-for-java/pull/40170/files
found generation diff on content safety, the issue is the current readonly flag calculation does not include segment info.
Generate content safety locally, there is no diff now.

tsp, tcgc, model types, fall back to use raw type to calculate readonly flag

---

fluentgen/src/test/java/com/azure/autorest/BeforeAllTestsExtension.java
fluentgen/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
javagen/pom.xml
javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java
javagen/src/test/java/com/azure/autorest/BeforeAllTestsExtension.java
javagen/src/test/java/com/azure/autorest/JavagenUnitTests.java
javagen/src/test/java/com/azure/autorest/MockUnitJavagen.java
javagen/src/test/java/com/azure/autorest/mapper/ClientMethodMapperTests.java
javagen/src/test/java/com/azure/autorest/mapper/PomMapperTests.java
javagen/src/test/java/com/azure/autorest/model/clientmodel/ProxyMethodExampleTests.java
javagen/src/test/java/com/azure/autorest/template/TestProxyAssertsTemplateTests.java
javagen/src/test/java/com/azure/autorest/util/ClassNameUtilTests.java
javagen/src/test/java/com/azure/autorest/util/CodeNamerTests.java
javagen/src/test/java/com/azure/autorest/util/ModelTestCaseUtilTests.java
javagen/src/test/java/com/azure/autorest/util/SchemaUtilTests.java
javagen/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
postprocessor/pom.xml
preprocessor/pom.xml
preprocessor/src/test/java/com/azure/autorest/PreprocessorTests.java
typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-extension/src/main/java/com/azure/typespec/Main.java
typespec-extension/src/main/java/com/azure/typespec/util/TspLocationUtil.java
typespec-extension/src/operation-utils.ts
typespec-tests/package.json
typespec-tests/src/test/java/com/type/enums/fixed/FixedClientTest.java

fix https://github.com/Azure/autorest.java/issues/2788
code for `x-ms-original-file` https://github.com/Azure/autorest.java/pull/2789/commits/f6dd96b7a35cac35cdca69e5a68ce3956542840d
code for convert that to the relative path in sample file https://github.com/Azure/autorest.java/pull/2789/commits/979314768a9718465d26b9ad3896a3e4bc942a3e
UT with some refactor https://github.com/Azure/autorest.java/pull/2789/commits/5db62b916bf13ebbfe16a09c6b9bb914ac8da02e
test
```diff
* Samples for StandbyVirtualMachinePools Update.
*/
public final class StandbyVirtualMachinePoolsUpdateSamples {
+    /*
+     * x-ms-original-file:
+     * specification/standbypool/StandbyPool.Management/examples/2023-12-01-preview/
+     * StandbyVirtualMachinePools_Update.json
+     */
/**
* Sample code: …
```

tsp, generate origin (JSON) example file name in mgmt sample files

---

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
typespec-tests/src/main/java/com/_specs_/azure/core/basic/models/UserOrder.java
typespec-tests/src/main/java/com/cadl/patch/models/Fish.java
typespec-tests/src/main/java/com/cadl/patch/models/Salmon.java
typespec-tests/src/main/java/com/cadl/patch/models/SawShark.java
typespec-tests/src/main/java/com/cadl/patch/models/Shark.java

- Removes polymorphic discriminators from JSON merge patch tracking as they will always be serialized. So, instead of tracking them they have special handling in serialization to always include them.
- Fix where non-nullable properties weren't being checked to be included in JSON merge patch serialization.
- Removed package-private setters from polymorphic JSON merge patch models as they use access helpers instead.

Remove polymorphic discriminator from JSON merge patch tracking

---

javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java

Remove the JSON merge patch usage from models that are only used for output (read-only). The special code for JSON merge patch is only used when the model is serialized, no need to generate it if the model will never be serialized in an API request.

Remove JSON merge patch usage from output only models

---

typespec-extension/package-lock.json
typespec-extension/package.json

This change transitively adds typespec-azure-rulesets as a dependency to azure-sdk-java's emitter-package.json by adding a pinned peer dependency to the emitter's package.json file.
The constructed emitter-package.json:
```json
{
"main": "dist/src/index.js",
"dependencies": {
"@azure-tools/typespec-java": "0.16.2"
},
"devDependencies": {
"@azure-tools/typespec-azure-core": "0.42.0",
"@azure-tools/typespec-azure-resource-manager": "0.42.1",
"@azure-tools/typespec-azure-rulesets": "0.42.1",
"@azure-tools/typespec-client-generator-core": "0.42.3",
"@typespec/compiler": "0.56.0",
"@typespec/http": "0.56.0",
"@typespec/openapi": "0.56.0",
"@typespec/rest": "0.56.0",
"@typespec/versioning": "0.56.0"
}
}
```

Add typespec rulesets package as emitter dependency

---

typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-extension/src/main/java/com/azure/autorest/fluent/TypeSpecFluentPlugin.java
typespec-tests/package.json

There were discussion in scrum that Java better not use GUID.
Hence, for new lib, we'd better just let them be string.
Brownfield lib (in future) may need an emitter option.

tsp, mgmt, default to uuid-as-string

---

typespec-extension/package-lock.json
typespec-extension/package.json
typespec-tests/src/main/java/com/cadl/internal/InternalAsyncClient.java
typespec-tests/src/main/java/com/cadl/internal/InternalClient.java
typespec-tests/src/main/java/com/cadl/internal/implementation/InternalOpsImpl.java
typespec-tests/src/main/java/com/cadl/literalservice/LiteralServiceAsyncClient.java
typespec-tests/src/main/java/com/cadl/literalservice/LiteralServiceClient.java
typespec-tests/src/main/java/com/cadl/literalservice/implementation/LiteralOpsImpl.java
typespec-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java
typespec-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java
typespec-tests/src/main/java/com/cadl/longrunning/implementation/LongRunningClientImpl.java
typespec-tests/src/main/java/com/cadl/naming/NamingAsyncClient.java
typespec-tests/src/main/java/com/cadl/naming/NamingClient.java
typespec-tests/src/main/java/com/cadl/naming/implementation/NamingOpsImpl.java
typespec-tests/src/main/java/com/cadl/wiretype/WireTypeAsyncClient.java
typespec-tests/src/main/java/com/cadl/wiretype/WireTypeClient.java
typespec-tests/src/main/java/com/cadl/wiretype/implementation/WireTypeOpsImpl.java
typespec-tests/tsp/internal.tsp
typespec-tests/tsp/literal.tsp
typespec-tests/tsp/lro.tsp
typespec-tests/tsp/naming.tsp
typespec-tests/tsp/wire-type.tsp

convert implicit body property to explicit body property.
part of https://github.com/Azure/autorest.java/pull/2821 that can be merged to existing code, regardless of "what to spread".
all the changes should be about parameter name, now is `body`.

tsp, update local test for spread

---

javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/util/MethodUtil.java
package-lock.json
package.json

https://github.com/Azure/azure-sdk-for-java/pull/40936#discussion_r1660466165

client, handle single repeatability header

---

javagen/src/main/java/com/azure/autorest/template/example/ClientMethodExampleWriter.java
javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java
typespec-extension/src/code-model-builder.ts
typespec-tests/src/main/java/com/cadl/flatten/FlattenAsyncClient.java
typespec-tests/src/main/java/com/cadl/flatten/FlattenClient.java
typespec-tests/src/main/java/com/cadl/flatten/implementation/FlattenClientImpl.java
typespec-tests/src/main/java/com/cadl/union/UnionAsyncClient.java
typespec-tests/src/main/java/com/cadl/union/UnionClient.java
typespec-tests/src/main/java/com/cadl/union/implementation/UnionFlattenOpsImpl.java
typespec-tests/src/main/java/com/parameters/spread/AliasAsyncClient.java
typespec-tests/src/main/java/com/parameters/spread/AliasClient.java
typespec-tests/src/main/java/com/parameters/spread/implementation/AliasImpl.java
typespec-tests/src/main/java/com/payload/multipart/MultiPartAsyncClient.java
typespec-tests/src/main/java/com/payload/multipart/MultiPartClient.java
typespec-tests/src/main/java/com/payload/multipart/implementation/FormDatasImpl.java
typespec-tests/tsp/examples/2022-06-01-preview/FlattenOp_Send.json
typespec-tests/tsp/examples/2022-06-01-preview/FlattenOp_SendLong.json

Chenjie asks emitter to use this `getHttpOperationWithCache` (I guess the lots of diff in generated code is the reason -- calling `getHttpOperation` twice causes problem on anonymous models)
https://github.com/Azure/autorest.java/pull/2849/commits/be2195beac81348c0d4849ae27843293e4171c7d
Also fix an issue of not fallback to "body" parameter name, in grouping case.
https://github.com/Azure/autorest.java/pull/2849/commits/dff4f57d9036dadb430a8ee615119656af0aba76
The issue that emitter generate sample that cannot compile (if there is missing required values) be  https://github.com/Azure/autorest.java/issues/2611

tsp, TCGC getHttpOperationWithCache

---

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java
package-lock.json
package.json

```diff
-    opens com.azure.resourcemanager.oracledatabase.fluent.models to com.azure.core, com.fasterxml.jackson.databind;
-    opens com.azure.resourcemanager.oracledatabase.models to com.azure.core, com.fasterxml.jackson.databind;
+    opens com.azure.resourcemanager.oracledatabase.fluent.models to com.azure.core;
+    opens com.azure.resourcemanager.oracledatabase.models to com.azure.core;
```

mgmt, bug fix on module-info

---

fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
javagen/src/main/java/com/azure/autorest/util/ClassNameUtil.java

The functionality was in samples, but not in tests.
The mock test is usually one with potential long name.
---
before
```
sdk/informaticadatamanagement/azure-resourcemanager-informaticadatamanagement/src/test/java/com/azure/resourcemanager/informaticadatamanagement/generated/ServerlessRuntimesStartFailedServerlessRuntimeWithResponseMockTests.java
```
after
```
sdk/informaticadatamanagement/azure-resourcemanager-informaticadatamanagement/src/test/java/com/azure/resourcemanager/informaticadatamanagement/generated/ServerlessRuntimesStartFailedServerlessRuntimeWitMockTests.java
```

mgmt, truncate test file name, if path too long

---

javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java
typespec-tests/src/main/java/com/_specs_/azure/core/basic/BasicAsyncClient.java
typespec-tests/src/main/java/com/_specs_/azure/core/basic/TwoModelsAsPageItemAsyncClient.java
typespec-tests/src/main/java/com/cadl/protocolandconvenient/ProtocolAndConvenientAsyncClient.java
typespec-tests/src/main/java/com/cadl/response/ResponseAsyncClient.java
typespec-tests/src/main/java/com/cadl/specialheaders/EtagHeadersAsyncClient.java
typespec-tests/src/main/java/com/cadl/versioning/VersioningAsyncClient.java
typespec-tests/src/main/java/com/payload/pageable/PageableAsyncClient.java

Fixes #2847 
Updates hardcoded code generation to use more unique lambda parameter names to reduce potential conflicts with method parameter names.

Use more unique names for paging lambda parameters

---

typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/ChildResourcesInterfacesClient.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesClientImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ChildResourcesInterfacesImpl.java
typespec-tests/src/main/java/com/cadl/armresourceprovider/models/ChildResourcesInterfaces.java
typespec-tests/tsp/arm.tsp

fix https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3960525&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=738c417a-4a48-5620-b571-4f9e77e0bfd2&l=25 for next `typespec-azure-resource-manager`.
Tried to make interface `ResourceListByParent` work, all in vain.. Switched to using operation instead.
code: https://github.com/Azure/autorest.java/pull/2860/commits/c557444bee4df61dedf592230565f8b62b48586d

mgmt tsp, fix listByParent

---

javagen/src/main/resources/Readme_protocol.txt

Fix https://github.com/Azure/autorest.java/issues/2819 except the example code
Generated readme (template for further dev improvement) looks like this.
For the example, we'd first try to put a "recommended" client initialization example first. Then this "not recommended" service version example.

DPG, add Service API versions section under Examples

---

javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java
javagen/src/main/java/com/azure/autorest/template/example/ClientMethodExampleWriter.java
javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java

Fixes a `NullPointerException` issue if the value of the header is null. Also removes usage of `Optional` for nullness and null checking.

Fix possible NPE in ProxyMethodExample

---

javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/Annotation.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ExternalPackage.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
javagen/src/main/java/com/azure/autorest/template/EnumTemplate.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
javagen/src/main/java/com/azure/autorest/template/ServiceSyncClientTemplate.java

Replace references to `generic-core` with `clientcore` as `generic-core` has been renamed to `clientcore`.

Fix references to generic-core

---

typespec-extension/src/code-model-builder.ts
typespec-extension/src/emitter.ts
typespec-tests/Generate.ps1

Reason for this change: at present, the real case we encountered (2 of them) does not want to filter the preview api-versions.
---
No diff in test, as I added the option to cases that previously do this by default.
If not, versioning would then have
```java
public enum VersioningServiceVersion implements ServiceVersion {
/**
* Enum value 2022-06-01-preview.
*/
V2022_06_01_PREVIEW("2022-06-01-preview"),
/**
* Enum value 2022-09-01.
*/
V2022_09_01("2022-09-01"),
/**
* Enum value 2022-12-01-preview.
*/
V2022_12_01_PREVIEW("2022-12-01-preview");
```

tsp, temporary use emitter option service-version-exclude-preview to enable "filter out preview if GA api-version"

---

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
fluent-tests/swagger/stream-style-serialization.json
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java

Switch `TypeReference` from that of Jackson to that of azure-json.
`getType` in Jackson is now `getJavaType` in azure-json.
generated code is like:
```java
private PollerFlux<PollResult<Map<String, List<PirCommunityGalleryResource>>>, Map<String, List<PirCommunityGalleryResource>>>
beginListAsync() {
Mono<Response<Flux<ByteBuffer>>> mono = listWithResponseAsync();
return this.client
.<Map<String, List<PirCommunityGalleryResource>>, Map<String, List<PirCommunityGalleryResource>>>getLroResult(
mono, this.client.getHttpPipeline(),
new TypeReference<Map<String, List<PirCommunityGalleryResource>>>() {
}.getJavaType(), new TypeReference<Map<String, List<PirCommunityGalleryResource>>>() {
}.getJavaType(), this.client.getContext());
}
```

azure-json mgmt, fix pageable lro

---

typespec-extension/src/external-schemas.ts

The case would be covered in future cadl-ranch https://github.com/Azure/cadl-ranch/pull/613

tsp, multipart bug fix on HttpPart<File>[]

---

eng/pipelines/ci-typespec-java-dev-nightly.yaml

dev release of typespec may deprecate some of their APIs.
We would avoid lint on this, to make the nightly build pass.
the pass job https://dev.azure.com/azure-sdk/public/_build/results?buildId=4035068&view=results

eng, ignore warning of deprecation on typescript in nightly build

---

eng/sdk/sync_sdk.py
typespec-extension/src/code-model-builder.ts
typespec-tests/tsp/server.tsp

fix https://github.com/Azure/autorest.java/issues/2896

tsp, path allowReserved

---

fluent-tests/Initialize-Tests.ps1
fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java
fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentStreamStyleSerializationModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
typespec-tests/src/main/java/com/azure/resourcemanager/models/commontypes/managedidentity/fluent/models/ManagedIdentityTrackedResourceInner.java
typespec-tests/src/main/java/com/azure/resourcemanager/models/resources/fluent/models/NestedProxyResourceInner.java
typespec-tests/src/main/java/com/azure/resourcemanager/models/resources/fluent/models/TopLevelTrackedResourceInner.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/fluent/models/SalmonInner.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/fluent/models/TopLevelArmResourceInner.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/Error.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/ErrorMin.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/GoblinShark.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/OutputOnlyModelChild.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/SawShark.java
typespec-tests/src/main/java/com/cadl/armstreamstyleserialization/models/Shark.java
vanilla-tests/src/main/java/fixtures/modelflattening/models/FlattenedProduct.java
vanilla-tests/src/main/java/fixtures/streamstyleserializationimmutableoutput/models/MyDerivedType.java

The shadow property is in the middle of the inheritance hierarchy. In this case, "ResourceWithWritableName", since it has parent class `ProxyResource`.
Previously, we only check if property is shadowed in the leaf subclass. 
Now, we check if property is shadowed in the inheritance hierarchy, and use the one that's closest to the leaf.
code: 9149f75adc80f837b97267c7eebdc791ebdc917d
generated code diffs are reordering of the shadowed properties(a side effect of the fix logic). Now properties from subclass will come before the ones from parent class. 
```json
"ResourceWithWritableName": {
"description": "ARM resource.",
"type": "object",
"properties": {
"id": {
"description": "Resource ID.",
"type": "string",
"readOnly": true
},
"name": {
"description": "Resource name.",
"type": "string"
}, …
```

fix, mgmt shadow properties from Resource/ProxyResource

---

androidgen/pom.xml
customization-base/src/main/resources/pom.xml
docs/developer/readme.md
eng/versioning/external_dependencies.txt
fluentgen/pom.xml
javagen/pom.xml
pom.xml
typespec-extension/pom.xml

Switch from `maven-assembly-plugin` to the more fine-tuned `maven-shade-plugin`. This enables richer creation of JARs with dependencies and allows for features such as minimizing JARs (reducing their size).
Size of JARs shipping with the `autorest.java` NPM package should be about 15-20% smaller, saving about 10-15 MB in total size. `typespec-java` should also be saving about 4-5 MB.

Switch to Maven Shade plugin

---

typespec-tests/src/test/java/com/azure/resourcemanager/models/commontypes/managedidentity/ManagedIdentityManagerTests.java

nightly failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4167764&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=1fb2445c-3c92-5f9b-bcad-710222d02bc3
cause: 0.46.1 didn't include the `ManagedIdentityType` fix, though nightly does.

tsp, fix nightly

---

eng/pipelines/post-publish-sdk.yaml
eng/sdk/sync_sdk.py

Problem:
1. some lib fails, but we are not able to bump the commit ID because problem on specs repo (e.g. tspconfig removed from https://github.com/Azure/azure-rest-api-specs/tree/main/specification/ai/HealthInsights/HealthInsights.TrialMatcher)
2. typespec source change frequently require us to bump commit ID; it would be easier to see what's fails, and do a batch update
Dev need to check the sync SDK CI to see if there is failure.
At present, known failure is
- azure-health-insights-clinicalmatching

eng, report error, but do not fail during regen SDK

---

eng/pipelines/ci-typespec-java-dev-nightly.yaml

The default behavior appears to be that scheduled run would only happen if code in repo changed since last run.
Here we want it run every night, regardless of whether code changed.

eng, always=true for nightly build

---

typespec-tests/src/test/java/tsptest/armresourceprovider/ArmTests.java
typespec-tests/src/test/java/tsptest/armstreamstyleserialization/StreamStyleSerializationTests.java

- fix https://github.com/Azure/azure-sdk-for-java/issues/42935
- Per @archerzz 's ask, add e2e test for SDK CAE behavior. Personally, I think [HttpPipeline test](https://github.com/Azure/azure-sdk-for-java/blob/4cf3d9f1c9a1e5c8d3696079940cc94fc65545fe/sdk/core/azure-core/src/test/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicyTests.java#L44) in azure-core should suffice, though it doesn't hurt to have an e2e test for generated SDK.

mgmt, add mock test for CAE

---

core.diff
customization-base/CHANGELOG.md
customization-base/pom.xml
customization-tests/swagger/pom.xml
fluentgen/src/main/resources/readme/pom.xml
javagen/src/main/resources/readme/pom.xml
typespec-tests/customization/pom.xml

There seems some problem in customization test. It appears to loading the azure-autorest-customization lib from Maven, instead of getting it from local installed lib (which we are testing). Not sure why though.

release azure autorest customization 1.0.0 beta.9

---

typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-extension/readme.md
typespec-tests/package.json
typespec-tests/src/main/java/tsptest/armresourceprovider/fluent/models/OperationInner.java
typespec-tests/src/main/java/tsptest/response/implementation/ResponseClientImpl.java
typespec-tests/src/main/java/tsptest/visibility/VisibilityAsyncClient.java
typespec-tests/src/main/java/tsptest/visibility/VisibilityClient.java
typespec-tests/src/main/java/tsptest/visibility/VisibilityWriteAsyncClient.java
typespec-tests/src/main/java/tsptest/visibility/VisibilityWriteClient.java
typespec-tests/src/main/java/tsptest/visibility/implementation/VisibilityClientImpl.java
typespec-tests/src/main/java/tsptest/visibility/implementation/VisibilityWritesImpl.java
typespec-tests/src/main/java/tsptest/visibility/models/ReadDog.java
typespec-tests/src/main/java/tsptest/visibility/models/WriteDog.java
typespec-tests/tsp/error.tsp
typespec-tests/tsp/naming.tsp
typespec-tests/tsp/response.tsp
typespec-tests/tsp/visibility.tsp

for TypeSpec 0.63 / 0.49
There is 5 lib failure, likely due to `nextLink` break.
Will sync after specs PR https://github.com/Azure/azure-rest-api-specs/pull/31832
Also there be added `resourceId` property https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/common-types/types.tsp#L222-L223

eng, bump typespec libs, prepare 0.27.0 release

---

typespec-tests/package.json

I kind of remember why a lock file is hard in test.
We build locally the tgz of emitter package and use it in test, so generally we do `npm install` instead of `npm ci` in test module.

eng sync, pin spector and spec-api

---

eng/pipelines/ci-typespec-java-dev-nightly.yaml
eng/pipelines/ci-typespec-java.yaml
eng/pipelines/ci.yaml
eng/pipelines/fluent_integration.yaml
eng/pipelines/post-publish-sdk.yaml

Unify the pipeline pool/image as from image.yml, so that if e.g. we need upgrade ubuntu, only image.yml need to be changed.
Ideally we should go connect with azure-sdk-tools/eng, but maybe later.

eng, unify pool from image.yml

---

azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/implementation/models/AcrErrorInfo.java
fluent-tests/Initialize-Tests.ps1
fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
fluentgen/readme.md
package-lock.json
package.json
typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-tests/package.json
typespec-tests/src/main/java/azure/resourcemanager/commonproperties/implementation/CommonPropertiesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/commonproperties/implementation/ErrorsClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/commonproperties/implementation/ManagedIdentitiesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/nonresource/implementation/NonResourceClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/nonresource/implementation/NonResourceOperationsClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/operationtemplates/implementation/CheckNameAvailabilitiesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/operationtemplates/implementation/LroesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/operationtemplates/implementation/OperationTemplatesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/operationtemplates/implementation/OperationsClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/ExtensionsResourcesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/LocationResourcesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/NestedsClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/ResourcesClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/SingletonsClientImpl.java
typespec-tests/src/main/java/azure/resourcemanager/resources/implementation/TopLevelsClientImpl.java
typespec-tests/src/main/java/tsptest/armstreamstyleserialization/implementation/ArmStreamStyleSerializationClientImpl.java
typespec-tests/src/main/java/tsptest/armstreamstyleserialization/implementation/FishesClientImpl.java
typespec-tests/src/main/java/tsptest/armstreamstyleserialization/implementation/FunctionsClientImpl.java
typespec-tests/src/main/java/tsptest/armstreamstyleserialization/implementation/PrioritiesClientImpl.java
typespec-tests/src/main/java/tsptest/armstreamstyleserialization/implementation/TopLevelArmResourcesClientImpl.java

- sync non-null writeUntypedField for optional properties, and add test
- enable sync-stack by default for both typespec-java and autorest.java
- In fluent-test, for premium, still disable sync-stack
- sync-sdk result: https://github.com/Azure/azure-sdk-for-java/pull/45258
- prepare release for both typespec-java and autorest.java
- After release
- Update sdk/resourcemanager/api-specs.json, to disable sync-stack
- Sync-sdk

prepare release for typespec.java/0.30.1 and autorest.java/4.1.47

---

.github/copilot-instructions.md
typespec-extension/changelog.md
typespec-extension/package-lock.json
typespec-extension/package.json
typespec-tests/package.json

for https://github.com/microsoft/typespec/pull/7486
core is on https://github.com/microsoft/typespec/tree/http-client-java_branch-0.31.0
(due to the https://github.com/microsoft/typespec/pull/7444/files#diff-461c341b32704768ec79916fa02c008bf34c05e9cdea10973581835e7eb2d26e require update and release of `azure-autorest-customization`

eng, prepare release 0.31
