Azure/autorest.java

test/azure/src/test/java/fixtures/azurespecials/SubscriptionInCredentialsTests.java, test/azure/src/test/java/fixtures/azurespecials/SubscriptionInMethodTests.java, test/azure/src/test/java/fixtures/azurespecials/XMsClientRequestIdTests.java, test/azure/src/test/java/fixtures/lro/LROSADsTests.java, test/azure/src/test/java/fixtures/lro/LROsCustomHeaderTests.java, test/azurefluent/src/test/java/fixtures/azurespecials/SubscriptionInCredentialsTests.java, test/azurefluent/src/test/java/fixtures/azurespecials/SubscriptionInMethodTests.java, test/azurefluent/src/test/java/fixtures/azurespecials/XMsClientRequestIdTests.java, test/azurefluent/src/test/java/fixtures/lro/LROSADsTests.java, test/azurefluent/src/test/java/fixtures/lro/LROsCustomHeaderTests.java, test/vanilla/src/test/java/fixtures/header/HeaderOperationsTests.java, test/vanilla/src/test/java/fixtures/http/MultipleResponsesTests.java
A rename in the runtime caused some build errors to appear in autorest.java, so I'm fixing them.
=> Fix build errors in tests

src/vanilla/CodeNamerJv.cs, src/vanilla/DanModel/DanCodeGenerator.cs, test/vanilla/src/main/java/fixtures/bodyfile/Files.java, test/vanilla/src/main/java/fixtures/bodyfile/implementation/FilesImpl.java, test/vanilla/src/main/java/fixtures/bodyformdata/Formdatas.java, test/vanilla/src/main/java/fixtures/bodyformdata/implementation/FormdatasImpl.java, test/vanilla/src/test/java/fixtures/bodyfile/FilesTests.java, test/vanilla/src/test/java/fixtures/bodyformdata/FormdataTests.java
FileSegment stuff is a nice to have but this will do for 2017.
=> Use AsyncInputStream as stream type

src/JavaCodeGenerator.cs, src/Properties/AssemblyInfo.cs, src/autorest.java.csproj, test/autorest.java.tests/JavaCodeGeneratorTests.cs, test/autorest.java.tests/JavaFileTests.cs
This fixes https://github.com/Azure/autorest.java/issues/94.
=> Fix regular expression that escaped characters in enum value names

src/JavaCodeGenerator.cs
I thought I didn't have to do this one, but it turns out I do.
=> Change DateTimeRfc1123 to String for string-dates flag

src/azure/Model/MethodJva.cs, src/azure/Templates/AzureMethodTemplate.cshtml, src/azurefluent/Model/MethodGroupJvaf.cs, test/azure/src/main/java/fixtures/lro/implementation/LRORetrysImpl.java, test/azure/src/main/java/fixtures/lro/implementation/LROSADsImpl.java, test/azure/src/main/java/fixtures/lro/implementation/LROsCustomHeadersImpl.java, test/azure/src/main/java/fixtures/lro/implementation/LROsImpl.java, test/azurefluent/src/main/java/fixtures/lro/implementation/LRORetrysInner.java, test/azurefluent/src/main/java/fixtures/lro/implementation/LROSADsInner.java, test/azurefluent/src/main/java/fixtures/lro/implementation/LROsCustomHeadersInner.java, test/azurefluent/src/main/java/fixtures/lro/implementation/LROsInner.java, test/azurefluent/src/main/java/fixtures/paging/implementation/PagingsInner.java
=> Support for LROOptions extension handling, correctly import InnerSupport* based on multi-apiversion vs non-muti-apiversion

src/azurefluent/Templates/AzureFluentPomTemplate.cshtml
https://github.com/Azure/autorest.java/issues/340
=> Hard coding test jar version to 1.6.5 since 1.6.6 test jar is not maven

src/ClientModel/ClassType.cs, src/ClientModel/EnumType.cs, src/ClientModel/GenericType.cs, src/ClientModel/ProxyMethodParameter.cs, src/CodeNamerJv.cs, src/Mapper/ClientMethodMapper.cs, src/Mapper/MethodGroupMapper.cs, src/Mapper/ProxyMethodMapper.cs, src/Mapper/TypeMapper.cs, src/Template/ClientMethodTemplate.cs, src/Template/EnumTemplate.cs, src/Template/ExceptionTemplate.cs, src/Template/ProxyTemplate.cs, src/Template/ResponseTemplate.cs
AutoRest work for https://github.com/Azure/azure-sdk-for-java/pull/3411
=> Form data support and fixes for cognitive services 

src/azurefluent/Model/CodeModelJvaf.cs
https://github.com/Azure/azure-sdk-for-java/pull/3768
=> Reflect changes in pom refactoring

src/vanilla/Templates/ModelTemplate.cshtml, test/vanilla/src/main/java/fixtures/bodycomplex/models/Cookiecuttershark.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/DotFish.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/DotSalmon.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/Fish.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/Goblinshark.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/MyBaseType.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/MyDerivedType.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/Salmon.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/Sawshark.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/Shark.java, test/vanilla/src/main/java/fixtures/bodycomplex/models/SmartSalmon.java
See https://github.com/Azure/autorest.java/issues/380 for more details.
=> Add defaultImpl annotation to polymorphic types

src/azurefluent/Model/FluentCommon/Model/ModelLocalProperties.cs
Fix for https://github.com/Azure/azure-rest-api-specs/pull/6662 to avoid generate invalid package import declaration. 
@anuchandy , @jianghaolu  could you help me review this PR? Thanks.
=> Fix empty import.

fluentTest/pom.xml
Updating fasterxml/jackson. See https://github.com/Azure/autorest.java/issues/326
=> Updating jackson versions

src/azurefluent/Model/CodeModelJvaf.cs
Folder restructuring in azure-sdk-for-java
https://github.com/Azure/azure-sdk-for-java/issues/5682
PR for keyvault
https://github.com/Azure/azure-sdk-for-java/pull/5378
=> update fluent pom template 

tests/src/main/java/fixtures/bodyboolean/AutoRestBoolTestService.java, tests/src/main/java/fixtures/bodyboolean/AutoRestBoolTestServiceBuilder.java, tests/src/main/java/fixtures/bodyboolean/Bools.java, tests/src/main/java/fixtures/bodyboolean/models/Error.java, tests/src/main/java/fixtures/bodyboolean/models/ErrorException.java, tests/src/main/java/fixtures/bodyboolean/models/package-info.java, tests/src/main/java/fixtures/bodyboolean/package-info.java, tests/src/main/java/fixtures/bodyboolean/quirks/AutoRestBoolTestService.java, tests/src/main/java/fixtures/bodyboolean/quirks/AutoRestBoolTestServiceBuilder.java, tests/src/main/java/fixtures/bodyboolean/quirks/Bools.java, tests/src/main/java/fixtures/bodyboolean/quirks/models/Error.java, tests/src/main/java/fixtures/bodyboolean/quirks/models/ErrorException.java, tests/src/main/java/fixtures/bodyboolean/quirks/models/package-info.java, tests/src/main/java/fixtures/bodyboolean/quirks/package-info.java, tests/src/test/java/fixtures/bodyboolean/BoolTests.java
Manual change: tests/src/test/java/fixtures/bodyboolean/BoolTests.java 
Test passes.
=> codegen for body-boolean.json

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Protocol.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/RequestParameterLocation.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java, tests/src/main/java/fixtures/custombaseuri/AutoRestParameterizedHostTestClient.java, tests/src/main/java/fixtures/custombaseuri/AutoRestParameterizedHostTestClientBuilder.java, tests/src/main/java/fixtures/custombaseuri/Paths.java, tests/src/main/java/fixtures/custombaseuri/models/Error.java, tests/src/main/java/fixtures/custombaseuri/models/ErrorException.java, tests/src/main/java/fixtures/custombaseuri/models/package-info.java, tests/src/main/java/fixtures/custombaseuri/package-info.java, tests/src/test/java/fixtures/custombaseuri/CustomBaseUriTests.java
=> Add custom base url tests

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
https://github.com/Azure/autorest.java/issues/442
=> protection for NPE

generate, generate.bat, tests/src/main/java/fixtures/bodyinteger/AutoRestIntegerTestService.java, tests/src/main/java/fixtures/bodyinteger/AutoRestIntegerTestServiceBuilder.java, tests/src/main/java/fixtures/bodyinteger/Ints.java, tests/src/main/java/fixtures/bodyinteger/models/Error.java, tests/src/main/java/fixtures/bodyinteger/models/ErrorException.java, tests/src/main/java/fixtures/bodyinteger/models/package-info.java, tests/src/main/java/fixtures/bodyinteger/package-info.java, tests/src/test/java/fixtures/bodyinteger/IntOperationsTests.java
=> Generate code for body-integer.json

generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java, tests/src/main/java/fixtures/bodynumber/AutoRestNumberTestService.java, tests/src/main/java/fixtures/bodynumber/AutoRestNumberTestServiceBuilder.java, tests/src/main/java/fixtures/bodynumber/Numbers.java, tests/src/main/java/fixtures/bodynumber/models/Error.java, tests/src/main/java/fixtures/bodynumber/models/ErrorException.java, tests/src/main/java/fixtures/bodynumber/models/package-info.java, tests/src/main/java/fixtures/bodynumber/package-info.java, tests/src/test/java/fixtures/bodynumber/NumberOperationsTests.java
=> Generate code for body-number

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Protocol.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/RequestParameterLocation.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/SerializationStyle.java, javagen/readme.md, javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/PrimitiveType.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, readme.md, tests/src/test/java/fixtures/bodybyte/ByteOperationsTests.java
=> [fixes #423] Generate url.json

generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java, tests/src/main/java/fixtures/extensibleenums/PetStoreInc.java, tests/src/main/java/fixtures/extensibleenums/PetStoreIncBuilder.java, tests/src/main/java/fixtures/extensibleenums/Pets.java, tests/src/main/java/fixtures/extensibleenums/models/DaysOfWeekExtensibleEnum.java, tests/src/main/java/fixtures/extensibleenums/models/IntEnum.java, tests/src/main/java/fixtures/extensibleenums/models/Pet.java, tests/src/main/java/fixtures/extensibleenums/models/package-info.java, tests/src/main/java/fixtures/extensibleenums/package-info.java, tests/src/main/java/fixtures/httpinfrastructure/MultipleResponses.java, tests/src/test/java/fixtures/extensibleenums/PetsTests.java
=> Generate extensible-enums-swagger.json

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/MethodPageDetails.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/transformer/Transformer.java, tests/src/main/java/fixtures/paging/Pagings.java, tests/src/main/java/fixtures/paging/models/ProductResultValue.java
Fix https://github.com/Azure/autorest.java/issues/472
=> v4 fix paging null nextlinkname

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaFile.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaFileFactory.java, javagen/src/main/java/com/azure/autorest/template/PackageInfoTemplate.java
FIx https://github.com/Azure/autorest.java/issues/470
=> java source license header

javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
Fix https://github.com/Azure/autorest.java/issues/475
=> fix client property description

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java
Only the extension definition for LRO and client-flatten.
I will try to do LRO based on current draft PR on a separate branch to unblock yaohai.
=> add lro extension and flatten extension

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Property.java, javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
Add flattenedNames in code model according to latest perk.
fluentgen had a temporary generator side flattener, which was used to flatten model.
Will adapt to Garrett's flattener when it is ready.
=> support flatten

javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
Partly fix https://github.com/Azure/autorest.java/issues/483
=> support string constant

javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/MethodGroupClient.java, javagen/src/main/java/com/azure/autorest/template/MethodGroupTemplate.java
Support additional interface like InnerSupportsGet/InnerSupportsDelete/InnerSupportsListing for Fluent.
Implementation is in fluentgen.
=> method group support additional interfaces

javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
Fix https://github.com/Azure/autorest.java/issues/483
=> v4 generialize for constant in property

tests/src/main/java/fixtures/bodycomplex/models/GoblinSharkColor.java, tests/src/main/java/fixtures/modelflattening/AutoRestResourceFlatteningTestService.java, tests/src/main/java/fixtures/paging/Pagings.java, tests/src/main/java/fixtures/url/PathItems.java, tests/src/test/java/fixtures/url/PathItemsTests.java
Change on the parameter order is due to fix that required parameter put before non-required parameter.
=> v4 update tests

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java, javagen/src/main/java/com/azure/autorest/mapper/BinaryMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/DefaultMapperFactory.java, javagen/src/main/java/com/azure/autorest/mapper/MapperFactory.java, javagen/src/main/java/com/azure/autorest/mapper/Mappers.java, javagen/src/main/java/com/azure/autorest/mapper/SchemaMapper.java
While generating code for storage data-plane swagger, I ran into a few issues. This PR is to fix all those bugs that include adding BinarySchema support, disable paging if swagger doesn't have proper paging info and add yaml mapping for few missing node types.
=> Support BinarySchema and minor bug fixes for paging and xml

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
Add context to single page async and paging async client methods.
=> Add context to single page async client methods

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
When a swagger does not contain any model classes, model package with just package-info.java is generated. This PR checks if there are model classes before creating package-info.java.
=> Don't generate empty model packages

javagen/src/main/java/com/azure/autorest/util/CodeNamer.java, javagen/src/test/java/com/azure/autorest/util/CodeNamerTests.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java
Fix https://github.com/Azure/autorest.java/issues/576
For now, make sure start/end of enum name is not "_".
=> improve enum value naming, avoid invalid ones like _

javagen/src/main/java/com/azure/autorest/model/clientmodel/MapType.java, vanilla-tests/src/main/java/fixtures/bodydictionary/implementation/DictionarysImpl.java, vanilla-tests/src/main/java/fixtures/modelflattening/AutoRestResourceFlatteningTestService.java, vanilla-tests/src/main/java/fixtures/modelflattening/models/ResourceCollection.java
A rather edge case for mgmt compute.
`ManagedServiceIdentity` actually need add a `key -> null` in UPDATE to remove a user identity. Hence value in Map could be null.
=> v4 NPE guard in MapType validate

javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
In swagger, sometimes XML can contain namespaces. Our Java generator currently does not generate JacksonXmlProperty if there is a namespace. If the XML property has a namespace, we'll generate `JacksonXmlProperty(namespace = "", localName ="")`, otherwise the normal JsonProperty annotation will be used (which works).
As an aside, Jackson supports having multiple annotations on it so if we wanted to support XML and JSON side by side, it would work.
```json
"CreateQueueBody": {
"description": "The request body for creating a queue.",
"type": "object",
"xml":{
"name": "entry",
"namespace": "http://www.w3.org/2005/Atom"
},
"properties": {
"content": {
"type": "object",
"xml": {
"namespace": "http://www.w3.org/2005/Atom"
},
"properties": {
"type": {
"type": "string",
"default": …
```
=> Add support for XML namespaces

azure-tests/src/main/java/fixtures/paging/Pagings.java, fluent-tests/prepare-tests.bat, fluentnamer/readme.md, generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, preprocessor/readme.md
fix https://github.com/Azure/autorest.java/issues/621
=> v4 fix paging x ms client name

javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
This PR is to fix the order of ctor args when a super-class has more than 1 ctor arg.
=> Fix the order of ctor args of super class

fluent-tests/src/main/java/com/azure/resourcemanager/AzureServiceClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
Coupled for https://github.com/Azure/azure-sdk-for-java/pull/12585
=> update lro error handling in generated code

fluentnamer/readme.md, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
Test https://github.com/Azure/autorest.modelerfour/issues/206
=> fluent upgrade m4 to 4.15.375

fluent-tests/src/main/java/com/azure/resourcemanager/resources/fluentcore/AzureServiceClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java, vanilla-tests/src/main/java/fixtures/url/Queries.java
Make this `context = this.client.mergeContext(context);`
```
context = this.client.mergeContext(context);
return service
.createOrUpdate(
this.client.getEndpoint(),
resourceGroupName,
this.client.getApiVersion(),
this.client.getSubscriptionId(),
parameters,
context);
```
=> add mergeContext to merge user provided context and default context

fluent-tests/prepare-tests.bat, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
=> v4 use adapative method name in validation code

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ResponseStatusCodeNormalization.java
=> fluent, remove 404 in status code, for get/list

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentResourceModelMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentModelProperty.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceModel.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/ModelNaming.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/ModelType.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/WrapperTypeConversionMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelInterfaceTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java, javagen/src/main/java/com/azure/autorest/template/prototype/MethodTemplate.java, readme.md
Start with simple wrapper for inner object.
Impl class looks like this
```
public final class StorageAccountImpl implements StorageAccount {
private final StorageAccountInner innerObject;
public StorageAccountImpl(StorageAccountInner innerObject) {
this.innerObject = innerObject;
}
public Sku sku() {
return this.inner().sku();
}
public Kind kind() {
return this.inner().kind();
}
public Identity identity() {
return this.inner().identity();
}
public ProvisioningState provisioningState() {
return this.inner().provisioningState();
}
public Endpoints primaryEndpoints() {
return this.inner().primaryEndpoints();
}
public String primaryLocation() {
return this.inner().primaryLocation();
}
public AccountStatus statusOfPrimary() {
return this.inner().statusOfPrimary();
}
public OffsetDateTime …
```
=> v4 fluentlite wrapper

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java, androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java, androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidMapperFactory.java, androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidOptionalParameterMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
collapse optional parameters in client method into an options model
generate options model
=> Create options model for optional parameters in client methods

fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceModel.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/ModelNaming.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentConstructorByInner.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentConstructorByName.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionInterfaceTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/UtilsTemplate.java, fluentgen/src/main/resources/Utils_getValueFromIdByName.txt
Sample impl code in Update flow.
```
public BlobContainerImpl update() {
return this;
}
public BlobContainer apply() {
this.innerObject =
serviceManager.blobContainers().inner().update(resourceGroupName, accountName, containerName, innerObject);
return this;
}
public BlobContainer apply(Context context) {
this.innerObject =
serviceManager
.blobContainers()
.inner()
.update(resourceGroupName, accountName, containerName, innerObject, context);
return this;
}
public BlobContainerImpl(BlobContainerInner innerObject, StorageManager serviceManager) {
this.innerObject = innerObject;
this.serviceManager = serviceManager;
this.resourceGroupName = Utils.getValueFromIdByName(innerObject.id(), "resourceGroups");
this.accountName = Utils.getValueFromIdByName(innerObject.id(), "storageAccounts"); …
```
=> v4 fluentlite update idparser

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentApplyMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentCreateMethod.java, generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, vanilla-tests/src/main/java/fixtures/bodyfile/Files.java
fix https://github.com/Azure/autorest.java/issues/695
=> v4 fix stream response

fluent-tests/src/main/java/com/azure/resourcemanager/resources/fluentcore/AzureServiceClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceModel.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/ModelNaming.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceImplementation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentApplyMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentCreateMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTypeConversionTemplate.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClientProperty.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java, javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
Also add method visibility control on `ServiceClientProperty`
=> v4, fluent, only provide max overload with Context

generate, generate.bat, vanilla-tests/src/main/java/fixtures/discriminatorflattening/MetricAlerts.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/MonitorManagementClient.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/MonitorManagementClientBuilder.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/MetricAlertCriteria.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/MetricAlertResource.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/MetricAlertSingleResourceMultipleMetricCriteria.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/Odatatype.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/package-info.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/package-info.java, vanilla-tests/src/test/java/fixtures/discriminatorflattening/DiscriminatorTests.java, vanilla-tests/swagger/discriminator-flattening.json
Add test swagger vanilla-tests/swagger/discriminator-flattening.json
=> v4 add test case for discriminator under flattened property

fluent-tests/pom.xml, fluent-tests/src/main/java/com/azure/resourcemanager/resources/fluentcore/AzureServiceClient.java, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
This will be merge to `v4_fluentgen` branch, but not yet to `v4` branch, since azure-core-management is not released.
=> v4 fluent, update azure-core-management

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/arm/UrlPathSegments.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ObjectMapper.java
1st, try resource group as parent
2nd, try subscription as parent
3rd, try nested resource (with some other resource as its parent)
=> v4 fluentlite misc for find resource create

azure-tests/pom.xml, extension-base/pom.xml, fluent-tests/pom.xml, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/pom.xml, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentManagerProperty.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/ModelNaming.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionInterfaceTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/UtilsTemplate.java, fluentgen/src/main/resources/Manager_authenticate.txt, fluentnamer/pom.xml, fluentnamer/src/main/java/com/azure/autorest/fluent/model/FluentType.java, javagen/pom.xml, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, vanilla-tests/pom.xml
make service client structure in lite be same as in premium. the difference is that async method is not visible in lite.
also update dependencies
=> v4, fluentlite, change generate config

.gitignore, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentProxyTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientBuilderTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentTemplateFactory.java, fluentnamer/readme.md, fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/Pom.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java, javagen/src/main/java/com/azure/autorest/template/DefaultTemplateFactory.java, javagen/src/main/java/com/azure/autorest/template/PomTemplate.java, javagen/src/main/java/com/azure/autorest/template/TemplateFactory.java, javagen/src/main/java/com/azure/autorest/template/Templates.java
improve later when CI is finalized.
sample pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager-storage-generated</artifactId>
<version>1.0.0-beta</version>
<packaging>jar</packaging>
<name>Microsoft Azure SDK for Storage</name>
<description>The Azure Storage Management API.</description>
<url>https://github.com/Azure/azure-sdk-for-java</url>
<licenses>
<license>
<name>The MIT License (MIT)</name>
<url>http://opensource.org/licenses/MIT</url>
<distribution>repo</distribution>
</license>
</licenses>
<scm> …
```
=> v4 fluentlite minimal pom

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyRegion.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java, fluentnamer/src/main/java/com/azure/autorest/fluent/model/FluentType.java
Use `withRegion` instead of `withLocation`.
=> v4 fluentlite support withRegion

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/TextFile.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/ChangelogTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/ReadmeTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/main/resources/Changelog.txt, fluentgen/src/main/resources/Readme.txt, fluentnamer/readme.md, fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java, javagen/src/main/java/com/azure/autorest/model/xmlmodel/XmlBlock.java, javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
Write versioning comment to pom as well.
Generate README and CHANGELOG.
Read dependency versions from `version_client.txt`. This requires `azure-libraries-for-java-folder` to get the sdk folder.
=> v4 fluentlite misc3

fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelInterfaceTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
support `region()` in model, if `location` is present.
=> v4 fluentlite region

fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
first use that from parameter, then try namespace
=> v4 fix artifact-id, first use that from parameter, then try namespace

javagen/pom.xml, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
azure-core updated the package name for `JsonPatchDocument`. This PR is to update the core version to pull in this change and also update the package name of JsonPatchDocument for the generated code.
=> Update JsonPatchDocument package

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java
i.e., if the method is `createOrUpdateVirtualNetworkRule`, the define method in collection will be `defineVirtualNetworkRule`.
=> v4 fluentlite, heuristic use createOrUpdateFoo method name as base for defineFoo method

androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java, androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java, androidgen/src/main/java/com/azure/autorest/android/model/AndroidProxyMethod.java, androidgen/src/main/java/com/azure/autorest/android/model/AndroidServiceClient.java, androidgen/src/main/java/com/azure/autorest/android/template/AndroidClientMethodTemplate.java, androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceAsyncClientTemplate.java, androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceClientTemplate.java, androidgen/src/main/java/com/azure/autorest/android/template/AsyncPageRetrieverTemplate.java, androidgen/src/main/java/com/azure/autorest/android/template/PageResponseRetrieverTemplate.java, androidgen/src/main/java/com/azure/autorest/android/template/PageRetrieverTemplate.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
Add logic to generate sync and async methods within service implementation layer to support async callback to return pages asynchronously and sync methods to return page collections with or without response
=> Implement paging code generation in service impl

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/TypeConversionUtils.java
```
public List<StorageAccountKey> keys() {
List<StorageAccountKey> inner = this.innerModel().keys();
if (inner != null) {
return Collections.unmodifiableList(inner);
} else {
return Collections.emptyList();
}
}
```
=> v4 fluentlite, return Collections.emptyList() when inner return null for List

fluent-tests/prepare-tests.bat, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/OperationNameNormalization.java, javagen/pom.xml
for something like this https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2020-05-01-preview/databoxedge.json#L195-L212
=> v4 fluent reorder getByResourceGroup param

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaRenamer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java, readme.md
sample usage
```
--rename-model:PrivateEndpointConnection:PrivateEndpointConnectionAutoGenerated,PrivateEndpointConnectionAutoGenerated:PrivateEndpointConnection,PrivateLinkServiceConnectionStateProperty:PrivateLinkServiceConnectionStatePropertyAutoGenerated,PrivateLinkServiceConnectionStatePropertyAutoGenerated:PrivateLinkServiceConnectionStateProperty
```
=> v4 fluent, support rename model

fluent-tests/prepare-tests.bat, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/delete/ResourceDelete.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
=> v4 fluent lite, bug fixes

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyRegion.java, fluentgen/src/test/java/com/azure/autorest/fluent/util/FluentUtilsTests.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java, javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
=> v4 fluentlite bug fixes

fluent-tests/report.md, fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMethodGroupMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentCollectionMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentResourceCollection.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/delete/ResourceDelete.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/test/java/com/azure/autorest/fluent/mapper/ResourceParserTests.java, fluentgen/src/test/resources/code-model-fluentnamer-locks.yaml, fluentnamer/src/main/java/com/azure/autorest/fluent/model/WellKnownMethodName.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/OperationNameNormalization.java
`delete` in client.
`deleteByResourceGroup` in fluent collection.
=> v4 fluentlite, handle deleteByResourceGroup

fluent-tests/report.md, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/MethodParameter.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentConstructorByName.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentDefineMethod.java, javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
`define` method in collection will be something like this.
```
/**
* Begins definition for a new AdvancedThreatProtectionSetting resource.
*
* @return the first stage of the new AdvancedThreatProtectionSetting definition.
*/
AdvancedThreatProtectionSetting.DefinitionStages.Blank define();
```
=> v4 fluentlite resource constant name

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentnamer/readme.md
=> v4 fluentlite, add live test for define() method

customization-base/pom.xml, extension-base/pom.xml, pom.xml
=> Add missing info in poms

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaNameNormalization.java, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java
1. avoid conflict of listNext operation
2. do not override "additionalProperties" model method
3. modify to remove CLIENT from query parameters (except "api-version")
=> v4 fluent, bug fixes

fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Changelog.java, fluentgen/src/main/resources/Readme.txt
testing on https://github.com/Azure/azure-sdk-for-java/pull/18634
=> v4 fluentlite add documentation and survey to readme

package.json
Updating version to 4.0.12 to unblock storage.
=> Bump version to 4.0.12

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, package.json
This PR is a follow-up change to fix the response headers that also use header collection prefix.
https://github.com/Azure/autorest.java/issues/877#issuecomment-767049352
=> Fix header collection for response types

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, package.json
The previous PR https://github.com/Azure/autorest.java/pull/907 did not update the annotation from JsonProperty to HeaderCollection. This PR addresses that issue.
=> Response header collection

.gitignore, azure-tests/src/main/java/fixtures/lro/LroManager.java, azure-tests/src/main/java/fixtures/lro/implementation/AutoRestLongRunningOperationTestServiceImpl.java, azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/LroWithParamaterizedEndpointsImpl.java, azure-tests/src/test/java/fixtures/lro/LroNoRetryTests.java, eng/pipelines/ci.yaml, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java, package.json
also try to update testserver to lastest
=> v4 fluent, npe fix

azure-tests/pom.xml, azure-tests/src/main/java/fixtures/lro/implementation/AutoRestLongRunningOperationTestServiceImpl.java, azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/LroWithParamaterizedEndpointsImpl.java, fluent-tests/pom.xml, fluentgen/src/main/resources/Client_getLroFinalResultOrError.txt, fluentnamer/pom.xml, pom.xml
core throws `com.azure.core.implementation.serializer.MalformedValueException`. no good option to handle it exception RuntimeException.
=> v4 fluent misc fix

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/UtilsTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/TypeConversionUtils.java, fluentgen/src/main/resources/Utils_PagedIterableImpl.txt, fluentgen/src/test/java/com/azure/autorest/fluent/util/TypeConversionUtilsTests.java
https://github.com/Azure/azure-sdk-for-java/pull/19042
=> v4 fluentlite, switch away from PagedIterable.mapPage

readme.md
Added configuration to print help when using `--help`.
Copied the flags from the settings section above.
when running -`autorest ---help --java` it will display this after autorest help content
=> Added autorest help-content for java

eng/pipelines/fluent_integration.yaml, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/UtilsTemplate.java, fluentgen/src/main/resources/Utils_PagedIterableImpl.txt, fluentnamer/readme.md
Mirror https://github.com/Azure/azure-sdk-for-java/pull/19649/commits/089650809cd362d8811858ef19e5c043a31ce9c7
Also update autorest core and m4 to latest (hope it will be fine...)
=> v4 fluentlite, improve PagedIterableImpl

preprocessor/readme.md
This will resolve "FATAL: Error: Circular $ref in Model"
=> Update ModelerFour version to 4.15.442

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java, customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
Fixes #951, fixes #949
This PR adds better tracking mechanisms when adding a method to a `ClassCustomization`. When adding a method an attempt to extract the method signature will be performed, if this succeeds then line number tracking will be ignored. This results in better handling as line numbers may be modified when the method is added.
=> Better Handle Tracking the Added Method

azure-tests/src/main/java/fixtures/azurespecials/Headers.java, azure-tests/src/test/java/fixtures/azurespecials/AzureSpecialParametersTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMethodGroupMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/TypeConversionUtils.java, generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java, vanilla-tests/src/main/java/fixtures/header/Headers.java
Fix https://github.com/Azure/autorest.java/issues/870
Pending some fixes in fluent.
=> v4, bug fix, client method with sync response should return specialized Response with headers

postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java, postprocessor/src/main/resources/readme/pom.xml
This PR checks the status of building the customization code and throws an exception if the build fails. Also, removed the parent pom relative link from the customization pom.
=> Throw exception if customization build fails

eng/pipelines/fluent_integration.yaml, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
bug fix for case that `api-version` is not from client method, but a constant in method.
=> v4 fluentlite, bug fix for resource actions

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
Added test dependencies will be like this (in current sdk repo)
```
<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-identity</artifactId>
<version>1.2.5</version> 
<scope>test</scope>
</dependency>
<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-core-test</artifactId>
<version>1.6.1</version> 
<scope>test</scope>
</dependency>
<dependency>
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager-resources</artifactId>
<version>2.4.0</version> 
<scope>test</scope>
</dependency>
```
=> v4 fluentlite, include test dependencies in pom

eng/pipelines/ci.yaml, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/PomMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
It helps regenerate the SDK, when there is added dependencies in pom (usually for testing).
=> v4 fluentlite, parse existing pom for additonal dependencies

fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/CodeSample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/ReadmeTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/TextTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/main/resources/Readme.txt
utilize existing test code, extract it to example block in README.
e.g. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/hdinsight/azure-resourcemanager-hdinsight/src/test/java/com/azure/resourcemanager/hdinsight/HdInsightTests.java
will extract the code within the `try` block.
=> v4 fluentlite, auto extract sample code from test

javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java, javagen/src/main/java/com/azure/autorest/model/xmlmodel/XmlFile.java, javagen/src/main/java/com/azure/autorest/model/xmlmodel/XmlFileContents.java
fluent lite would like to have indent=2 in pom.xml, as pom from most track2 SDK have indent=2 instead of 4.
=> v4, add Options to XmlFile to allow some customization

.gitignore, eng/pipelines/ci.yaml
for now, just add an extra step to copy "/coverage" directory to previous directory.
=> update ci as report now in /coverage

androidgen/src/main/java/com/azure/autorest/android/Androidgen.java, extension-base/pom.xml, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java, extension-base/src/main/java/com/azure/autorest/extension/base/plugin/NewPlugin.java, fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java, javagen/src/main/java/com/azure/autorest/Javagen.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java
1.25 have security issue (DDOS https://snyk.io/vuln/maven:org.yaml:snakeyaml@1.25)
=> upgrade snakeyaml to 1.28

azure-tests/pom.xml, customization-base/src/main/resources/pom.xml, customization-tests/pom.xml, fluent-tests/pom.xml, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, javagen/pom.xml, pom.xml, vanilla-tests/pom.xml, vanilla-tests/src/test/java/fixtures/bodyarray/ArrayTests.java, vanilla-tests/src/test/java/fixtures/bodyboolean/BoolTests.java, vanilla-tests/src/test/java/fixtures/bodybyte/ByteOperationsTests.java, vanilla-tests/src/test/java/fixtures/bodydictionary/DictionaryOperationsTests.java, vanilla-tests/src/test/java/fixtures/bodyinteger/IntOperationsTests.java, vanilla-tests/src/test/java/fixtures/bodynumber/NumberOperationsTests.java, vanilla-tests/src/test/java/fixtures/bodystring/StringOperationsTests.java
The JsonFlatten on field requires latest azure-core.
=> v4 upgrade to latest core

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, javagen/src/main/java/com/azure/autorest/Javagen.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java, package.json
This PR is to add the credential policies to the pipeline after retry policy. Now, azurekeycredential type requires setting the key header name.
=> Add token and key credential policy after retry policy 

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/MapNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java
sample
```
package com.azure.mgmtlitetest.storage;
import java.util.HashMap;
import java.util.Map;
public final class QueueCreateSamples {
public static void queueOperationPut(com.azure.mgmtlitetest.storage.StorageManager storageManager) {
storageManager.queues().define("queue6185").withExistingStorageAccount("res3376", "sto328").create();
}
public static void queueOperationPutWithMetadata(com.azure.mgmtlitetest.storage.StorageManager storageManager) {
storageManager
.queues()
.define("queue6185")
.withExistingStorageAccount("res3376", "sto328")
.withMetadata(mapOf("sample1", "meta1", "sample2", "meta2"))
.create();
} …
```
=> v4 fluentlite example support map

androidgen/src/main/java/com/azure/autorest/android/model/clientmodel/AndroidClientModel.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ClientModelNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/LiteralNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
sample code
```
public static void createAAMLCompute(
com.azure.resourcemanager.machinelearningservices.MachineLearningServicesManager
machineLearningServicesManager) {
machineLearningServicesManager
.machineLearningComputes()
.define("compute123")
.withRegion("eastus")
.withExistingWorkspace("testrg123", "workspaces123")
.withProperties(
new AmlCompute()
.withProperties(
new AmlComputeProperties()
.withOsType(OsType.WINDOWS)
.withVmSize("STANDARD_NC6")
.withVmPriority(VmPriority.DEDICATED)
.withVirtualMachineImage(
new VirtualMachineImage()
.withId(
"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups"
+ "/myResourceGroup/providers/Microsoft.Compute/galleries/myImageGallery"
+ "/images/myImageDefinition/versions/0.0.1"))
.withIsolatedNetwork(false)
.withScaleSettings(
new …
```
=> v4 fluentlite, support sample for ResourceCreate flow, parameters

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/checker/JavaFormatter.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ObjectNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/test/java/com/azure/autorest/fluent/checker/JavaFormatterTests.java, fluentgen/src/test/java/com/azure/autorest/fluent/template/FluentExampleTests.java, fluentgen/src/test/resources/code-model-fluentnamer-policy.yaml
Sample (who wrote this stupid swagger???)
```
package com.azure.mgmtlitetest.rp;
import com.azure.core.management.serializer.SerializerFactory;
import com.azure.core.util.serializer.SerializerEncoding;
import com.azure.mgmtlitetest.rp.models.ParameterDefinitionsValue;
import com.azure.mgmtlitetest.rp.models.ParameterDefinitionsValueMetadata;
import com.azure.mgmtlitetest.rp.models.ParameterType;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
public final class PolicyDefinitionsCreateOrUpdateSamples {
public static void createOrUpdateAPolicyDefinitionWithAdvancedParameters( …
```
=> v4 example support Object

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ClientModelNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/ReadmeTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/SampleTemplate.java
sample https://github.com/Azure/azure-sdk-for-java/blob/4d157aef3f7302a62aea3ed07a9de655493bdf5e/sdk/machinelearningservices/azure-resourcemanager-machinelearningservices/SAMPLE.md
=> v4 fluentlite generate sample.md

customization-base/src/main/java/com/azure/autorest/customization/Editor.java, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
Fixes the issue mentioned here - https://github.com/Azure/azure-sdk-for-java/pull/22556#discussion_r660774668
=> Fix JacksonXmlProperty annotation for inner classes

fluent-tests/gen_all.py, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java, generate, generate-android.bat, generate.bat
required by https://github.com/Azure/azure-rest-api-specs/pull/15165
=> v4, upgrade autorest.core to 3.4.5

.github/CODEOWNERS, androidgen/src/main/java/com/azure/autorest/android/Androidgen.java, extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, javagen/src/main/java/com/azure/autorest/Javagen.java, package.json, postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java, readme.md
Fix https://github.com/Azure/autorest.java/issues/1107
=> v4, add skip-formatting

javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/clientflatten/models/ApplicationPackageReference.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/models/ApplicationPackageReference.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/noflatten/models/ApplicationPackageReference.java, vanilla-tests/src/main/java/fixtures/discriminatorflattening/requirexmsflattened/models/ApplicationPackageReference.java, vanilla-tests/swagger/discriminator-flattening.json
=> fix issue #1119 to add summary in schema together with description for code model property

docs/developer/design.md, docs/developer/readme.md, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ClientModelNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ExampleNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentCollectionMethodExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceCreateExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceUpdateExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ListNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/LiteralNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/MapNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/ObjectNode.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceLocalVariables.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/CollectionMethodTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/immutablemodel/PropertyTypeConversionTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelImplementationTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/TypeConversionUtils.java, fluentgen/src/test/java/com/azure/autorest/fluent/util/TypeConversionUtilsTests.java, readme.md
a basic developer guide in ./developer/readme.md
an in depth guide in ./developer/design.md
=> v4, rev1 for dev docs

javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java, javagen/src/main/java/com/azure/autorest/template/ServiceVersionTemplate.java, protocol-tests/src/main/java/fixtures/bodycomplex/AutoRestComplexTestServiceBuilder.java, protocol-tests/src/main/java/fixtures/bodystring/AutoRestSwaggerBATServiceBuilder.java, protocol-tests/src/main/java/fixtures/header/AutoRestSwaggerBATHeaderServiceBuilder.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/AutoRestHttpInfrastructureTestServiceBuilder.java, protocol-tests/src/main/java/fixtures/llcinitial/LLCClientBuilder.java, protocol-tests/src/main/java/fixtures/llcupdate1/LLCClientBuilder.java, protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClientBuilder.java, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceBuilder.java, protocol-tests/src/main/java/fixtures/url/AutoRestUrlTestServiceBuilder.java
Resolve https://github.com/Azure/autorest.java/issues/1146
Service version upper case
Remove serializer adapter
=> Service version upper case; Remove serializer adapter

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
stupid bug, should use `continue`
=> v4 fluent, sample bug fix

azure-tests/pom.xml, eng/pipelines/ci.yaml, vanilla-tests/pom.xml
try to get coverage publish work for latest autorest.testserver
=> v4 update ci for latest testserver

eng/pipelines/ci.yaml, generate, generate.bat, pom.xml, protocol-resilience-test/llcinitial/pom.xml, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/LLCAsyncClient.java, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/LLCClient.java, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/LLCClientBuilder.java, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/implementation/LLCClientImpl.java, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/implementation/ParamsImpl.java, protocol-resilience-test/llcinitial/src/main/java/fixtures/llcresi/package-info.java, protocol-resilience-test/llcupdate1/pom.xml, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/LLCAsyncClient.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/LLCClient.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/LLCClientBuilder.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/implementation/LLCClientImpl.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/implementation/ParamsImpl.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/package-info.java, protocol-resilience-test/pom.xml
Resolve https://github.com/Azure/autorest.java/issues/1132
=> Check breaking change resilience using revapi

.gitignore, customization-tests/swagger/README.md, docs/developer/readme.md, fluentgen/package.json, fluentnamer/package.json, javagen/package.json, package.json, readme.md
I've changed "v4" to "main", from what I can find. So far all is in markdown.
"main" is already added to CI.
=> prepare to use main branch

fluent-tests/prepare-tests.bat, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentBaseExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentCollectionMethodExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceCreateExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentResourceUpdateExample.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java, fluentgen/src/test/java/com/azure/autorest/fluent/model/clientmodel/ProxyMethodExampleTests.java, fluentnamer/readme.md, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodExampleMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethodExample.java, package.json, pom.xml
- core and m4 version update
- rename `xmsOriginalFile` method to `originalFile`
- generate sample with `x-ms-original-file` metadata
Sample:
```java
package com.azure.mgmtlitetest.storage.generated;
import com.azure.mgmtlitetest.storage.models.CorsRule;
import com.azure.mgmtlitetest.storage.models.CorsRuleAllowedMethodsItem;
import com.azure.mgmtlitetest.storage.models.CorsRules;
import com.azure.mgmtlitetest.storage.models.Multichannel;
import com.azure.mgmtlitetest.storage.models.ProtocolSettings;
import com.azure.mgmtlitetest.storage.models.SmbSetting;
import java.util.Arrays;
/** Samples for FileServices SetServiceProperties. */ …
```
=> v4 fluent, support x-ms-original-file in latest m4

generate, generate.bat, preprocessor/readme.md, readme.md
so dev does not need to duplicate these in README in SDK repo.
=> add default config for LLC

azure-tests/src/main/java/fixtures/azurespecials/models/Error.java, generate, generate.bat, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, package.json, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceClient.java, protocol-tests/src/main/java/fixtures/paging/implementation/PagingsImpl.java, protocol-tests/src/test/java/fixtures/paging/PagingTests.java, vanilla-tests/src/main/java/fixtures/bodystring/models/RefColorConstant.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsDelete307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsGet300Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsGet301Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsGet302Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsGet307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsHead300Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsHead301Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsHead302Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsHead307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsOptions307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPatch302Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPatch307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPost303Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPost307Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPut301Headers.java, vanilla-tests/src/main/java/fixtures/httpinfrastructure/models/HttpRedirectsPut307Headers.java, vanilla-tests/src/main/java/fixtures/validation/models/ChildProduct.java, vanilla-tests/src/main/java/fixtures/validation/models/ConstantProduct.java, vanilla-tests/src/main/java/fixtures/validation/models/Product.java
Do not generate e.g. `listAll(RequestOptions)`.
`listAll(RequestOptions, Context)` should be enough.
=> llc, remove sync API without Context

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, fluentnamer/readme.md, generate, generate.bat, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java, protocol-tests/src/main/java/fixtures/bodycomplex/PolymorphismAsyncClient.java, protocol-tests/src/main/java/fixtures/bodycomplex/PolymorphismClient.java, protocol-tests/src/main/java/fixtures/bodycomplex/implementation/PolymorphismsImpl.java, protocol-tests/src/main/java/fixtures/bodystring/StringOperationAsyncClient.java, protocol-tests/src/main/java/fixtures/bodystring/StringOperationClient.java, protocol-tests/src/main/java/fixtures/bodystring/implementation/StringOperationsImpl.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpClientFailureAsyncClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpClientFailureClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRedirectsAsyncClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRedirectsClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRetryAsyncClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRetryClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpServerFailureAsyncClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpServerFailureClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpSuccessAsyncClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpSuccessClient.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpClientFailuresImpl.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpRedirectsImpl.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpRetriesImpl.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpServerFailuresImpl.java, protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpSuccessImpl.java, protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesAsyncClient.java, protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java, protocol-tests/src/main/java/fixtures/mediatypes/implementation/MediaTypesClientImpl.java
fix https://github.com/Azure/autorest.java/issues/1199
=> llc, always generate request body doc

postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
fix https://github.com/Azure/autorest.java/issues/1222
=> postprocess, NPE guard

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java, customization-base/src/main/java/com/azure/autorest/customization/Customization.java, customization-base/src/main/resources/pom.xml, customization-tests/pom.xml, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, pom.xml, protocol-resilience-test/pom.xml, protocol-sdk-integration-tests/eng/versioning/version_client.txt, protocol-tests/pom.xml, vanilla-tests/pom.xml
We might need re-release `customization-base` module to maven.
=> all, update core version

javagen/src/main/java/com/azure/autorest/template/PomTemplate.java, javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java, package.json, postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
1. update to use the new POM properties
2. allow data-plane to use remote README
3. bug fix on LLC swagger README output, allow multiple JSON as input-file
=> misc improvement

fluentnamer/readme.md
both autorest.core and m4 need it
=> mgmt, move x-ms-examples-original-file option to global

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
for this https://github.com/Azure/azure-sdk-for-java/pull/25431
=> mgmt, fix missing config on premium

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/OperationNameNormalization.java, fluentnamer/src/main/java/com/azure/autorest/fluent/util/Utils.java
also accommodate certain example error of mismatched type.
=> mgmt, dedpulicate Operations_List

preprocessor/src/test/java/com/azure/autorest/MockPreprocessor.java, preprocessor/src/test/java/com/azure/autorest/PreprocessorTests.java
fix https://github.com/Azure/autorest.java/issues/1256
=> add additional assertions to preprocessor unit test

javagen/src/main/java/com/azure/autorest/Javagen.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ProtocolExample.java, javagen/src/main/java/com/azure/autorest/template/ProtocolSampleTemplate.java, package.json, protocol-sdk-integration-tests/test.py
=> LLC, fix exception type

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
Actually I am not sure why object does not match...
=> mgmt, fallback to name match, if object match failed

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
Bug is that previous code only check children of the model, but in some case, the polymorphic class is the child of the child (or deeper).
=> mgmt, bug fix, search the derive tree for model with polymorphic

package.json
for autorest new version release
=> incr version to 4.0.45

package.json
need a new release with bug fix included, for purview catalog dev
=> bump version to 4.0.48

javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
=> Make DEFAULT_SCOPES private

azure-tests/src/main/java/fixtures/lro/fluent/LROsClient.java, azure-tests/src/main/java/fixtures/lro/fluent/LroRetrysClient.java, azure-tests/src/main/java/fixtures/lro/fluent/LrosCustomHeadersClient.java, azure-tests/src/main/java/fixtures/lro/fluent/LrosaDsClient.java, azure-tests/src/main/java/fixtures/lro/implementation/LROsClientImpl.java, azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysClientImpl.java, azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersClientImpl.java, azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsClientImpl.java, azure-tests/src/main/java/fixtures/lroparameterizedendpoints/fluent/ResourceProvidersClient.java, azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/ResourceProvidersClientImpl.java
pure codegen code.
script here
https://github.com/Azure/autorest.java/blob/main/generate.bat#L66-L68
it is not enabled in script because of Java version, local we uses 11+, CI uses 8.
=> mgmt, update generated lro code

eng/pipelines/ci.yaml, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentExampleTemplate.java, generate, generate.bat, package.json
Likely this is an invalid example, as they specify null value for required property.
=> mgmt, distinguish primitive type in null case

generate, generate.bat
Fix the 2 lines that missed in a previous PR.
=> client, pin testserver

protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java
- sample customization of PollerFlux
- sample (proper) customization of PagedFlux
=> dpg, test, customize PollerFlux and PagedFlux

docs/generate/dataplane-customization.md
fix https://github.com/Azure/autorest.java/issues/1341
branch and PR for examples https://github.com/Azure/azure-sdk-for-java/pull/27647
=> dpg, customization doc for review

androidgen/pom.xml, customization-base/pom.xml, extension-base/pom.xml, postprocessor/pom.xml, preprocessor/pom.xml
=> client, jackson datbind 2.13.2.1

fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java
sample code
```java
/**
* Creates an instance of Storage service API entry point.
*
* @param httpPipeline the {@link HttpPipeline} configured with Azure authentication credential.
* @param profile the Azure profile for client.
* @return the Storage service API instance.
*/
public static StorageManager authenticate(HttpPipeline httpPipeline, AzureProfile profile) {
Objects.requireNonNull(httpPipeline, "'httpPipeline' cannot be null.");
Objects.requireNonNull(profile, "'profile' cannot be null.");
return new StorageManager(httpPipeline, profile, null);
}
```
=> mgmt, support authenticate with HttpPipeline

androidgen/pom.xml, azure-tests/pom.xml, customization-base/pom.xml, eng/versioning/external_dependencies.txt, eng/versioning/sync_versions.py, extension-base/pom.xml, fluent-tests/pom.xml, fluentnamer/pom.xml, javagen/pom.xml, partial-update-tests/pom.xml, pom.xml, postprocessor/pom.xml, preprocessor/pom.xml, protocol-resilience-test/pom.xml, protocol-tests/pom.xml, vanilla-tests/pom.xml
python script at commit https://github.com/Azure/autorest.java/commit/9cb1d741df081d5e75c6069d4f17b5f74b7bc341
=> client, script to sync versions in POM

androidgen/pom.xml, azure-tests/pom.xml, customization-base/src/main/resources/pom.xml, customization-tests/pom.xml, fluent-tests/pom.xml, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPomMapper.java, fluentnamer/pom.xml, javagen/pom.xml, javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, package.json, partial-update-tests/pom.xml, protocol-resilience-test/pom.xml, protocol-tests/pom.xml, vanilla-tests/pom.xml
also update azure-core and identity
=> dpg, add slf4j-simple to pom

docs/generate/dataplane.md, extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, generate, generate.bat, partial-update-tests/existing/swagger/README.md, preprocessor/readme.md, protocol-sdk-integration-tests/test.py, protocol-tests/swagger/custom-http-exception-mapping.md, readme.md
fix https://github.com/Azure/autorest.java/issues/1415
=> DPG, option data-plane (previously low-level-client)

postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
the case that readme.md for java configure is not under <module_folder>/swagger
=> partial update, use output-folder

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java
Fix https://github.com/Azure/autorest.java/issues/1442
I am ignoring tests here, as [these](https://github.com/Azure/azure-sdk-for-java/pull/28811/files) should do.
=> mgmt, use CoreUtils.mergeContext

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentManagerProperty.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java
sample (add the latter part of description)
```java
/**
* Gets the resource collection API of BlobContainers. It manages BlobContainer, ImmutabilityPolicy resource.
*
* @return Resource collection API of BlobContainers.
*/
public BlobContainers blobContainers() {
if (this.blobContainers == null) {
this.blobContainers = new BlobContainersImpl(clientObject.getBlobContainers(), this);
}
return blobContainers;
}
/**
* Gets the resource collection API of StorageAccounts. It manages StorageAccount resource.
*
* @return Resource collection API of StorageAccounts.
*/
public StorageAccounts storageAccounts() {
if (this.storageAccounts == null) {
this.storageAccounts = new StorageAccountsImpl(clientObject.getStorageAccounts(), this);
}
return storageAccounts;
}
/**
* Gets the resource collection …
```
=> mgmt, improve javadoc of Manager

docs/generate/dataplane.md, extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, protocol-tests/src/main/java/fixtures/dpgcustomization/DpgAsyncClient.java, protocol-tests/src/main/java/fixtures/dpgcustomization/DpgClient.java, protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java, protocol-tests/src/main/java/fixtures/llcupdate1/DpgAsyncClient.java, protocol-tests/src/main/java/fixtures/llcupdate1/DpgClient.java, protocol-tests/src/main/java/fixtures/llcupdate1/implementation/ParamsImpl.java, protocol-tests/src/main/java/fixtures/parameterizedendpoint/ParmaterizedEndpointAsyncClient.java, protocol-tests/src/main/java/fixtures/parameterizedendpoint/ParmaterizedEndpointClient.java, protocol-tests/src/main/java/fixtures/parameterizedendpoint/implementation/ParmaterizedEndpointClientImpl.java, protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java, protocol-tests/src/test/java/fixtures/dpgcustomization/DpgSendRequestTests.java, protocol-tests/src/test/java/fixtures/dpgupdate/DpgUpdateTests.java, protocol-tests/src/test/java/fixtures/parameterizedendpoint/ParameterizedEndpointTests.java, vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceAsyncClient.java, vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceClient.java, vanilla-tests/src/main/java/fixtures/bodydictionary/implementation/DictionariesImpl.java
for https://github.com/Azure/autorest.java/issues/1456
=> dpg, disable send request method

customization-base/README.md, readme.md
Update readme.md to avoid mentioning "low-level".
Add a troubleshooting section on customization-base. @alzimmermsft feel free to modify that if you wish.
=> improve readme

javagen/pom.xml, javagen/src/main/java/com/azure/autorest/Javagen.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java, javagen/src/main/java/com/azure/autorest/template/ModelTestTemplate.java, javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java, javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java, javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java, javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java, javagen/src/main/resources/data-plane.md, preprocessor/data-plane.md, preprocessor/pom.xml, preprocessor/readme.md, protocol-sdk-integration-tests/data-specs.json, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishMarketTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotSalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/FishTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/GoblinsharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyBaseTypeTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyDerivedTypeTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/ReadonlyObjTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SawsharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
add back the feature of generating swagger/readme.md, as the decision is not to use the configure on spec repo.
=> dpg, generate swagger/readme.md

generate, generate-android.bat, generate.bat
Adds functions to `generate`, `generate.bat`, and `generate-android.bat` to log which AutoRest command is being run to more easily troubleshoot generation failures locally and in the CI.
=> Log the AutoRest Command Running in Generation

customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java, customization-base/src/test/java/com/azure/autorest/customization/ClassCustomizationTests.java
This PR adds new methods to `ClassCustomization` to enable adding static code blocks to a class.
=> ClassCustomization method to add a static code block to class

androidgen/src/main/java/com/azure/autorest/android/util/package-info.java, azure-tests/pom.xml, customization-base/pom.xml, customization-tests/pom.xml, customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/DotSalmon.java, customization-tests/swagger/src/main/java/BodyComplexCustomization.java, extension-base/src/main/java/com/azure/autorest/extension/base/jsonrpc/package-info.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/package-info.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/package-info.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/package-info.java, extension-base/src/main/java/com/azure/autorest/extension/base/plugin/package-info.java, fluent-tests/pom.xml, fluentgen/pom.xml, fluentgen/src/test/java/com/azure/autorest/fluent/TestUtils.java, javagen/pom.xml, partial-update-tests/pom.xml, pom.xml, postprocessor/src/main/java/com/azure/autorest/postprocessor/util/PartialUpdateHandler.java, preprocessor/pom.xml, protocol-tests/pom.xml, vanilla-tests/pom.xml
Updates the parent POM and children POM configurations to simplify engineering for release and to standardize build further.
=> Update POMs to Simplify Release and Standardize Build

.github/workflows/generate-test-code.yml, .github/workflows/pre-release.yml, eng/versioning/external_dependencies.txt, extension-base/pom.xml, javagen/pom.xml, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/template/ServiceAsyncClientTemplate.java, javagen/src/main/java/com/azure/autorest/template/ServiceSyncClientTemplate.java, package.json, postprocessor/pom.xml, preprocessor/pom.xml, protocol-tests/src/main/java/fixtures/dpgcustomization/DpgAsyncClient.java, protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java, protocol-tests/src/main/java/fixtures/lro/LROsAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LroRetrysAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LrosCustomHeaderAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LrosaDsAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java, protocol-tests/src/main/java/fixtures/specialheader/SpecialHeaderAsyncClient.java, protocol-tests/src/main/java/fixtures/specialheader/implementation/HeadersImpl.java, protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java
fix https://github.com/Azure/autorest.java/issues/1508
Also
- add slf4j-nop to avoid "SLF4J: Failed to load class" in stderr
- add a github action to regen the code
---
Update to deviceupdate would be
https://github.com/weidongxu-microsoft/azure-sdk-for-java/commit/a0dda01627ea9664cf90de2af26f5ceda31cb3bd
=> DPG, bug fix on simple async method for LRO

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java
fix https://github.com/Azure/autorest.java/issues/1517
Align conditions of whether generating named response type for both response model and return type of proxy methods.
=> fix bug on generating named response type for fluent LRO pageable

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/DpgAsyncClient.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/DpgClient.java, protocol-resilience-test/llcupdate1/src/main/java/fixtures/llcresi/implementation/ParamsImpl.java, protocol-tests/src/main/java/fixtures/llcupdate1/DpgAsyncClient.java, protocol-tests/src/main/java/fixtures/llcupdate1/DpgClient.java, protocol-tests/src/main/java/fixtures/llcupdate1/implementation/ParamsImpl.java, protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesAsyncClient.java, protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java, protocol-tests/src/main/java/fixtures/mediatypes/implementation/MediaTypesClientImpl.java, protocol-tests/src/main/java/fixtures/multimediatypes/DpgMultiMediaTypesAsyncClient.java, protocol-tests/src/main/java/fixtures/multimediatypes/DpgMultiMediaTypesClient.java, protocol-tests/src/main/java/fixtures/multimediatypes/implementation/DpgMultiMediaTypesClientImpl.java
Fix https://github.com/Azure/autorest.java/issues/1494
=> DPG, fix wrong requestbodyschema javadoc for binary schema

javagen/src/main/resources/data-plane.md, preprocessor/data-plane.md, protocol-tests/src/main/java/fixtures/dpgcustomization/models/Input.java, protocol-tests/src/main/java/fixtures/dpgcustomization/models/LroProduct.java, protocol-tests/src/main/java/fixtures/dpgcustomization/models/Product.java, protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java
link https://github.com/Azure/autorest.java/issues/1526
=> dpg, by default enable required-fields-as-ctor-args

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fix https://github.com/Azure/autorest.java/issues/1559
result https://github.com/Azure/azure-sdk-for-java/pull/29957/files
=> mgmt, samples, improve handling of body parameter

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java, protocol-tests/src/main/java/fixtures/bodycomplex/PrimitiveAsyncClient.java, protocol-tests/src/main/java/fixtures/bodycomplex/PrimitiveClient.java, protocol-tests/src/main/java/fixtures/bodycomplex/implementation/PrimitivesImpl.java, protocol-tests/src/main/java/fixtures/bodystring/EnumAsyncClient.java, protocol-tests/src/main/java/fixtures/bodystring/EnumClient.java, protocol-tests/src/main/java/fixtures/bodystring/implementation/EnumsImpl.java, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceAsyncClient.java, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceClient.java, protocol-tests/src/main/java/fixtures/paging/implementation/PagingsImpl.java, protocol-tests/src/main/java/fixtures/requiredoptionalbody/RequiredOptionalBodyAsyncClient.java, protocol-tests/src/main/java/fixtures/requiredoptionalbody/RequiredOptionalBodyClient.java, protocol-tests/src/main/java/fixtures/requiredoptionalbody/implementation/RequiredOptionalBodyClientImpl.java
Fix https://github.com/Azure/autorest.java/issues/1574
=> dpg, use serialize name in javadoc

protocol-tests/src/test/java/fixtures/dpgupdate/DpgUpdateTests.java
testserver has implemented the two tests being disabled, added back.
=> improve test server coverage

cadl-extension/src/code-model-builder.ts
Currently, only for the corner case of a Model with Template arguments, but without a `@friendlyName`.
=> cadl, concat model name with name from template argument for a template

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
fix https://github.com/Azure/autorest.java/issues/1588
=> mgmt, generate examples only for json payload methods

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java
code
```java
String jobScheduleIdLocal = Utils.getValueFromIdByName(id, "jobSchedules");
if (jobScheduleIdLocal == null) {
throw LOGGER
.logExceptionAsError(
new IllegalArgumentException(
String.format("The resource ID '%s' is not valid. Missing path segment 'jobSchedules'.", id)));
}
UUID jobScheduleId = UUID.fromString(jobScheduleIdLocal);
return this.getWithResponse(resourceGroupName, automationAccountName, jobScheduleId, Context.NONE).getValue();
```
=> mgmt, fix spotbugs error

cadl-extension/src/code-model-builder.ts, cadl-tests/cadl/response.cadl, cadl-tests/src/main/java/com/cadl/response/ResponseAsyncClient.java, cadl-tests/src/main/java/com/cadl/response/ResponseClient.java, cadl-tests/src/main/java/com/cadl/response/ResponseClientBuilder.java, cadl-tests/src/main/java/com/cadl/response/implementation/ResponseClientImpl.java, cadl-tests/src/main/java/com/cadl/response/implementation/ResponseOpsImpl.java, eng/pipelines/cadl-ci.yaml, pom.xml
refer to openapi3 impl https://github.com/microsoft/cadl/blob/0a89618/packages/openapi3/src/openapi.ts#L536-L544
=> cadl, use semi-formal getEffectiveModelType

cadl-extension/src/code-model-builder.ts
fix https://github.com/Azure/autorest.java/issues/1670
=> cadl, support x-ms-convenient-api

cadl-extension/src/main/java/com/azure/cadl/Main.java, cadl-tests/src/main/java/com/cadl/odata/OdataAsyncClient.java, cadl-tests/src/main/java/com/cadl/odata/OdataClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedAsyncClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedClient.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
ref https://github.com/Azure/autorest.java/issues/1671
=> Cadl, convenience method for pageable

eng/pipelines/cadl-ci.yaml
Ref https://github.com/Azure/autorest.java/issues/1593#issuecomment-1245256589
Output cadl ranch coverage message:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1854335&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=3763df9f-aac5-5292-209f-31e3fd069cd1
=> Add cadl ranch coverage step in cadl-ci.yaml

javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
fix https://github.com/Azure/autorest.java/issues/1721
=> client, fix incorrect method name

fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ResourceTypeNormalization.java
fix https://github.com/Azure/autorest.java/issues/1564
=> fix adaptforparentschema 

cadl-tests/src/main/java/com/models/property/optional/DurationOperationAsyncClient.java, cadl-tests/src/main/java/com/models/property/optional/DurationOperationClient.java, cadl-tests/src/main/java/com/models/property/optional/implementation/DurationOperationsImpl.java, cadl-tests/src/main/java/com/models/property/optional/models/DurationProperty.java, cadl-tests/src/test/java/com/extensibleenums/ExtensibleEnumsClientTest.java, cadl-tests/src/test/java/com/hello/HelloClientTest.java, cadl-tests/src/test/java/com/models/inheritance/DiscriminatedClientTest.java, cadl-tests/src/test/java/com/models/inheritance/InheritanceClientTest.java, cadl-tests/src/test/java/com/models/property/optional/DurationOperationClientTest.java, cadl-tests/src/test/java/com/models/property/types/DictionaryStringClientTest.java
=> dpg, cadl, add cadl ranch tests

extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Property.java, fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java, fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java
https://github.com/Azure/azure-sdk-for-java/issues/31184
=> mgmt, not allow client-flatten on polymorphic schema

cadl-tests/src/main/java/com/cadl/odata/OdataAsyncClient.java, cadl-tests/src/main/java/com/cadl/odata/OdataClient.java, cadl-tests/src/main/java/com/cadl/odata/implementation/OdataOpsImpl.java, cadl-tests/src/main/java/com/cadl/paged/PagedAsyncClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedClient.java, cadl-tests/src/main/java/com/cadl/paged/implementation/PagedOpsImpl.java, cadl-tests/src/main/java/com/cadl/response/CadlCoreOpAsyncClient.java, cadl-tests/src/main/java/com/cadl/response/CadlCoreOpClient.java, cadl-tests/src/main/java/com/cadl/response/implementation/CadlCoreOpsImpl.java, cadl-tests/src/main/java/com/resiliency/devdriven/ResiliencyDevDrivenAsyncClient.java, cadl-tests/src/main/java/com/resiliency/devdriven/ResiliencyDevDrivenClient.java, cadl-tests/src/main/java/com/resiliency/devdriven/implementation/DevDrivensImpl.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplateBase.java, protocol-tests/src/main/java/fixtures/dpgcustomization/DpgAsyncClient.java, protocol-tests/src/main/java/fixtures/dpgcustomization/DpgClient.java, protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceAsyncClient.java, protocol-tests/src/main/java/fixtures/paging/AutoRestPagingTestServiceClient.java, protocol-tests/src/main/java/fixtures/paging/implementation/PagingsImpl.java, protocol-tests/src/main/java/fixtures/specialheader/SpecialHeaderAsyncClient.java, protocol-tests/src/main/java/fixtures/specialheader/SpecialHeaderClient.java, protocol-tests/src/main/java/fixtures/specialheader/implementation/HeadersImpl.java
Fix https://github.com/Azure/autorest.java/issues/1733
Main logic is in this commit: 51f4dd5a6979ae06c4ea34e16380ae973933c1a3
=> dpg, display inner model schema for paging in javadoc

cadl-extension/package.json, cadl-extension/readme.md, cadl-tests/package.json, eng/pipelines/cadl-ci.yaml, eng/pipelines/publish-cadl-java.yaml
https://www.npmjs.com/package/@azure-tools/cadl-java
=> eng, pipeline for npm release cadl-java

fluentgen/src/main/resources/Readme.txt
based on https://github.com/Azure/azure-sdk-for-java/pull/31287
detail: https://github.com/Azure/azure-sdk-for-java/pull/31287#issuecomment-1275864743
=> mgmt, improve readme template

cadl-extension/package.json, cadl-extension/readme.md, cadl-extension/src/emitter.ts, cadl-tests/package.json, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModel.java
follow https://github.com/Azure/azure-sdk-tools/pull/4402
wiki updated https://github.com/Azure/autorest.java/wiki/Cadl-to-Java#side-car-design-changes-expected
also remove the "java.json" support
=> Cadl, support noEmit

cadl-extension/src/emitter.ts, cadl-extension/src/main/java/com/azure/cadl/Main.java
fix https://github.com/Azure/autorest.java/pull/1776
emitter at present does not use this option.
=> cadl, allow unknown options

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/util/MethodUtil.java, protocol-tests/src/main/java/fixtures/lro/LROsAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LROsClient.java, protocol-tests/src/main/java/fixtures/lro/LroRetrysAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LroRetrysClient.java, protocol-tests/src/main/java/fixtures/lro/LrosaDsAsyncClient.java, protocol-tests/src/main/java/fixtures/lro/LrosaDsClient.java, protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java, vanilla-tests/src/main/java/fixtures/lro/LRORetrys.java, vanilla-tests/src/main/java/fixtures/lro/LROs.java, vanilla-tests/src/main/java/fixtures/lro/LrosaDs.java
=> dpg, use Void as final type for LRO DELETE

Generate.ps1, javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java
We seems got > 30% of CI hang around here https://github.com/Azure/autorest.java/blob/main/Generate.ps1#L71-L73 
See if "-UseNewRunspace" helps. So far tried 3 times, 3 pass. Though does not mean it is all good...
=> eng, try to see if "-UseNewRunspace" helps

androidgen/pom.xml, cadl-extension/package.json, cadl-extension/readme.md, cadl-tests/package.json, customization-base/pom.xml, extension-base/pom.xml, javagen/pom.xml, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, postprocessor/pom.xml, preprocessor/pom.xml
also bump some dependencies in pom
=> Cadl, bump package version

cadl-extension/src/emitter.ts, cadl-extension/src/main/java/com/azure/autorest/CadlPlugin.java, cadl-extension/src/main/java/com/azure/cadl/Main.java, cadl-extension/src/main/java/com/azure/cadl/model/EmitterOptions.java, cadl-tests/cadl-project.yaml
cadl compiler deprecated "output-path"
also switch to kebab-case as other lib do this
=> cadl, use output-dir

cadl-tests/cadl/auth.cadl, cadl-tests/cadl/builtin.cadl, cadl-tests/cadl/enum.cadl, cadl-tests/cadl/error.cadl, cadl-tests/cadl/lro.cadl, cadl-tests/cadl/naming.cadl, cadl-tests/cadl/odata.cadl, cadl-tests/cadl/optional.cadl, cadl-tests/cadl/paged.cadl, cadl-tests/cadl/partialupdate.cadl, cadl-tests/cadl/patch.cadl, cadl-tests/cadl/polymorphism.cadl, cadl-tests/cadl/response.cadl, cadl-tests/cadl/server.cadl, cadl-tests/cadl/special-headers.cadl, cadl-tests/cadl/visibility.cadl
relate: https://github.com/Azure/autorest.java/pull/1780
=> replace @serviceTitle and @serviceVersion with @service

androidgen/src/main/java/com/azure/autorest/android/template/AndroidClientMethodTemplate.java, cadl-extension/src/code-model-builder.ts, cadl-extension/src/common/operation.ts, cadl-tests/cadl/lro.cadl, cadl-tests/cadl/paged.cadl, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedAsyncClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedClient.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ConvenienceApi.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Operation.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ProxyMethod.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java, javagen/src/main/java/com/azure/autorest/util/MethodNamer.java
fix https://github.com/Azure/autorest.java/issues/1465
=> cadl, support convenienceAPI

fluentgen/src/main/resources/Readme.txt
=> mgmt, update readme template

androidgen/src/main/java/com/azure/autorest/android/Main.java, fluentgen/src/main/java/com/azure/autorest/fluent/Main.java, fluentnamer/src/main/java/com/azure/autorest/fluentnamer/Main.java, javagen/src/main/java/com/azure/autorest/Main.java, postprocessor/src/main/java/com/azure/autorest/postprocessor/Main.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/Main.java
Still sees multiple cases of CI hang when regenerating code.
Try see if `System.exit(0)` helps.
=> client, exit at end of main

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java, fluentnamer/readme.md, javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java, javagen/src/main/java/com/azure/autorest/util/SchemaUtil.java, vanilla-tests/src/main/java/fixtures/bodyfile/Files.java, vanilla-tests/src/test/java/fixtures/bodyfile/FilesTests.java
fix https://github.com/Azure/autorest.java/issues/1812
=> client, by default use BinaryData for file/stream

fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/MockUnitTestParser.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentClient.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentMethodMockUnitTest.java, fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentMethodTestTemplate.java, fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientBuilder.java, javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java, javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java
major change https://github.com/Azure/autorest.java/pull/1817/commits/7c37aed471abee0be4a13354a9e65bf5ac2d3f24
fix https://github.com/Azure/autorest.java/issues/1711
test PR https://github.com/Azure/azure-sdk-for-java/pull/31881
=> mgmt, redact generated samples/tests

cadl-extension/package.json, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ArmIdSchema.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/CodeModelCustomConstructor.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Schema.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/AllowedResource.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsArmIdDetails.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/extensionmodel/XmsExtensions.java, fluentnamer/readme.md, javagen/src/main/java/com/azure/autorest/mapper/PrimitiveMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java, javagen/src/main/java/com/azure/autorest/template/example/ModelExampleWriter.java, package.json
Mostly for fixing new issues found on m4 4.25.0 https://github.com/Azure/autorest.java/wiki/Fluent-Codegen-Report/38bddfadd26fb8ebb5c47a19ee34c5402a47b8fc
1. support arm-id (from m4 4.25.0)
2. support URL in example
3. switch to BinaryData for file response
=> mgmt, support arm-id

cadl-extension/src/code-model-builder.ts, cadl-extension/src/emitter.ts, cadl-extension/src/main/java/com/azure/autorest/CadlPlugin.java, cadl-extension/src/main/java/com/azure/cadl/model/EmitterOptions.java
link https://github.com/Azure/autorest.java/issues/1831
=> Cadl, support service-versions

cadl-tests/src/main/java/com/cadl/visibility/VisibilityClientBuilder.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientBuilder.java
follow https://github.com/lmazuel/cadl-azure/pull/1
=> dpg, use buildClient for ServiceClient

cadl-tests/src/main/java/com/cadl/odata/OdataAsyncClient.java, cadl-tests/src/main/java/com/cadl/paged/PagedAsyncClient.java, cadl-tests/src/main/java/com/cadl/response/CoreAsyncClient.java, cadl-tests/src/main/java/com/resiliency/devdriven/DevDrivenAsyncClient.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ServiceAsyncClientTemplate.java
fix https://github.com/Azure/autorest.java/issues/1741
=> cadl, improve pageable convenience api

cadl-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
link https://github.com/Azure/autorest.java/issues/1672
=> Cadl, LRO convenience api

cadl-extension/src/emitter.ts
fix https://github.com/Azure/autorest.java/issues/1775
=> cadl, report error if java not found on PATH

azure-tests/pom.xml, cadl-extension/pom.xml, cadl-tests/pom.xml, customization-base/pom.xml, fluent-tests/pom.xml, fluentgen/pom.xml, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPomMapper.java, javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, package.json, partial-update/pom.xml, protocol-sdk-integration-tests/eng/versioning/version_client.txt, protocol-tests/pom.xml, vanilla-tests/pom.xml
link https://github.com/Azure/azure-sdk-for-java/pull/31504
=> client, pom also include junit-api in test

cadl-extension/src/code-model-builder.ts
ServiceVersion would handle the allowed api-versions, if needed.
=> cadl, use string for api-version on host

cadl-extension/src/code-model-builder.ts
link https://github.com/Azure/autorest.java/issues/1800
=> cadl, make property not readonly if the visibility is 'create' or 'update'

cadl-extension/package.json, cadl-extension/readme.md, cadl-tests/Generate.ps1, cadl-tests/cadl/lro.cadl, cadl-tests/package.json, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java, cadl-tests/src/main/java/com/cadl/longrunning/implementation/LongRunningClientImpl.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
1. modify the test to first generate without convenience API and do a compile without tests (to verify the code compiles)
2. update a test
3. fix the bug
=> cadl, bug fix on LRO without convenience API

Generate.ps1
Changes how generation works to be done using PowerShell jobs.
=> Run Generate as a Job

.gitignore, cadl-extension/src/code-model-builder.ts, cadl-tests/cadl_checkout.sh
for Union, it will not fail, but leave a warning e.g.
```
warning cadl-java: Unsupported Union type: 'input' for 'string,Array,Array,Array'. Treated as Unknown.
```
=> Cadl, unblock openai

eng/pipelines/ci-cadl-java.yaml
link https://github.com/Azure/autorest.java/issues/1863
ref: https://teams.microsoft.com/l/message/19:16f8f1ed70d044139be153707bdaee0e@thread.skype/1670954749275?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1670954749275&teamName=Azure%20SDK&channelName=Cadl%20Engineering&createdTime=1670954749275&allowXTenantAccess=false
=> cadl, update upload cadl ranch report step

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java, fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java, javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java
fix https://github.com/Azure/autorest.java/issues/1900
code sample https://github.com/Azure/azure-sdk-for-java/blob/002fcc1d3df5e53e50de3ae3224b82fd6ba14197/sdk/loadtesting/azure-resourcemanager-loadtesting/src/main/java/com/azure/resourcemanager/loadtesting/models/EncryptionPropertiesIdentity.java#L29
=> mgmt, option property-include-always

cadl-tests/cadl/special-headers.cadl
link https://github.com/Azure/autorest.java/issues/1908
so far, `Repeatability-First-Sent` is good.
=> cadl, update Repeatability-First-Sent test

cadl-extension/src/code-model-builder.ts, cadl-extension/src/common/operation.ts, cadl-tests/src/main/java/com/cadl/flatten/FlattenAsyncClient.java, cadl-tests/src/main/java/com/cadl/flatten/FlattenClient.java, cadl-tests/src/test/java/com/cadl/flatten/FlattenTests.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ConvenienceApi.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ParameterMapping.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java
link https://github.com/Azure/autorest.java/issues/1898
current impl likely have more bugs. e.g. when body is optional.
=> Cadl, premiliary on payload flatten

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
The Javadoc of protocol method would still say `Object`.
For now it is for ADP, whose Cadl defines 200 as model1 (`finalType`) and 202 as model2 (`intermediateType`).
For best, we'd hope Cadl source could explicitly define `finalOperation` so that codegen can get the `finalType` unambiguously.
=> cadl, fallback to 200 in LRO

cadl-extension/src/code-model-builder.ts, cadl-tests/cadl/builtin.cadl, cadl-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java, cadl-tests/src/main/java/com/cadl/builtin/BuiltinClient.java, cadl-tests/src/main/java/com/cadl/builtin/implementation/BuiltinClientImpl.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java
fix https://github.com/Azure/autorest.java/issues/1908
=> Cadl, date in header

cadl-extension/src/code-model-builder.ts
@haolingdong-msft 
When you do projectedName, likely handle it in `getName`.
=> cadl, getName for operation

cadl-extension/readme.md, cadl-extension/src/emitter.ts
=> cadl, update docs about emitter options

cadl-tests/cadl/lro.cadl, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java, cadl-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java, cadl-tests/src/main/java/com/cadl/longrunning/implementation/LongRunningClientImpl.java, cadl-tests/src/main/java/com/cadl/longrunning/models/ResourceOperationStatusExportedResourceError.java, cadl-tests/src/main/java/com/cadl/longrunning/models/ResourceOperationStatusResourceError.java, cadl-tests/src/main/java/com/cadl/longrunning/models/ResourceOperationStatusResourceExportedResourceError.java
mainly use what's already defined in Azure.Core
=> cadl, update lro test

cadl-extension/src/code-model-builder.ts, javagen/src/main/java/com/azure/autorest/Javagen.java, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java, javagen/src/main/java/com/azure/autorest/util/ClientModelUtil.java
link https://github.com/Azure/autorest.java/issues/1876
version, baseUri, hostParameters should be moved to client, so that different client can have different setting
=> cadl, remove global version

cadl-extension/changelog.md, cadl-extension/package.json, cadl-extension/src/code-model-builder.ts, cadl-tests/cadl/enum.cadl, cadl-tests/package.json, cadl-tests/src/main/java/com/cadl/enumservice/EnumServiceAsyncClient.java, cadl-tests/src/main/java/com/cadl/enumservice/EnumServiceClient.java, cadl-tests/src/main/java/com/cadl/enumservice/implementation/EnumServiceClientImpl.java, cadl-tests/src/main/java/com/cadl/odata/OdataAsyncClient.java, cadl-tests/src/main/java/com/cadl/odata/OdataClient.java, cadl-tests/src/main/java/com/cadl/odata/implementation/OdataClientImpl.java, cadl-tests/src/test/java/com/cadl/enumservice/EnumTests.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java
context https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1675287069941?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1675284088668&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1675287069941&allowXTenantAccess=false
=> cadl, support query format=multi

javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
fix https://github.com/Azure/autorest.java/issues/1970
tested locally with cadl, protocol and fluent lite
example for fluent lite: 
```pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager-storage-generated</artifactId>
<version>1.0.0-beta.1</version> 
<packaging>jar</packaging>
<name>Microsoft Azure SDK for Storage Management</name>
<description>This package contains Microsoft Azure SDK for Storage Management SDK. For documentation on how to use this package, please see https://aka.ms/azsdk/java/mgmt. The Azure Storage …
```
=> generate copyright for pom.xml

eng/pipelines/ci-cadl-java.yaml, eng/pipelines/ci.yaml, eng/pipelines/fluent_integration.yaml, eng/pipelines/publish-autorest-java.yaml, eng/pipelines/publish-cadl-java.yaml
=> Upgrade Node Version to a Consistent Version

Generate.ps1
Attempt to prevent `Generate.ps1` from deadlocking randomly.
=> Changing Script to Prevent Deadlocking

cadl-extension/src/code-model-builder.ts, cadl-tests/src/main/java/com/_specs_/azure/traits/implementation/TraitsClientImpl.java, cadl-tests/src/test/java/com/_specs_/azure/traits/TraitsTests.java
fix https://github.com/Azure/autorest.java/issues/2008
=> Cadl, fix for api-version in path via TraitOverride<VersionParameterTrait<>>

azure-dataplane-tests/src/main/java/com/azure/ai/formrecognizer/documentanalysis/implementation/models/ContentType.java, azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactArchitecture.java, azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactManifestOrder.java, azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactTagOrder.java, cadl-tests/src/main/java/com/models/property/types/models/FixedInnerEnum.java, cadl-tests/src/main/java/com/models/property/types/models/InnerEnum.java, customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/GoblinSharkColor.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ChoiceSchema.java, extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/SealedChoiceSchema.java, javagen/src/main/java/com/azure/autorest/mapper/ChoiceMapper.java, javagen/src/main/java/com/azure/autorest/mapper/MapperUtils.java, javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientEnumValue.java, javagen/src/main/java/com/azure/autorest/model/javamodel/JavaEnum.java, javagen/src/main/java/com/azure/autorest/template/EnumTemplate.java, vanilla-tests/src/main/java/fixtures/bodycomplex/models/GoblinSharkColor.java, vanilla-tests/src/main/java/fixtures/extensibleenums/models/IntEnum.java, vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType.java, vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType1.java, vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType2.java, vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType3.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/GoblinSharkColor.java
Fixes #987
Adds support for descriptions in enum values.
=> Support Descriptions in Enum Values

cadl-tests/package.json, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
mgmt no longer need this after removing JsonFlatten
=> mgmt, remove code no longer needed

preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java
mgmt policy added model `Override`...
=> client, avoid Override as model name

javagen/src/main/java/com/azure/autorest/template/StreamSerializationModelTemplate.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/DotFish.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/Fish.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/MyBaseType.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/Salmon.java, vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/Shark.java, vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/DotFish.java, vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/Fish.java, vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/MyBaseType.java, vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/Salmon.java, vanilla-tests/src/main/java/fixtures/streamstyleserializationctorargs/models/Shark.java
Modifies stream-style JSON polymorphic deserialization to always buffer the JSON object being deserialized.
=> Always Buffer the JSON Object when Handling Polymorphism

typespec-extension/src/code-model-builder.ts, typespec-extension/src/utils.ts, typespec-tests/src/main/java/com/cadl/multicontenttypes/MultiContentTypesAsyncClient.java, typespec-tests/src/main/java/com/cadl/multicontenttypes/MultiContentTypesClient.java, typespec-tests/src/main/java/com/cadl/multicontenttypes/implementation/MultiContentTypesClientImpl.java
reduce the size of code-model-builder.ts
this PR moves utility functions to utils.ts
=> tsp, refactor ts code

typespec-extension/changelog.md, typespec-extension/package.json, typespec-extension/readme.md, typespec-extension/src/code-model-builder.ts, typespec-extension/src/emitter.ts, typespec-extension/src/utils.ts, typespec-tests/package.json, typespec-tests/tsp_checkout.sh
link https://github.com/Azure/autorest.java/issues/1682
currently codegen only output examples for prototype APIs (as example generation for convenience API not ready)
test with AnomalyDetector
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/AnomalyDetector
=> tsp, loadExamples

javagen/src/main/java/com/azure/autorest/template/ConvenienceSyncMethodTemplate.java
fix https://github.com/Azure/autorest.java/issues/2069
Add back async way.
=> fix enable-sync-stack: false

typespec-tests/src/test/java/com/arrays/itemtypes/NullableFloatValueClientTest.java, typespec-tests/src/test/java/com/models/property/nullable/BytesClientTest.java, typespec-tests/src/test/java/com/models/property/nullable/CollectionsByteClientTest.java, typespec-tests/src/test/java/com/models/property/nullable/CollectionsModelClientTest.java, typespec-tests/src/test/java/com/models/property/nullable/DatetimeOperationClientTest.java, typespec-tests/src/test/java/com/models/property/nullable/DurationOperationClientTest.java, typespec-tests/src/test/java/com/server/path/multiple/MultipleClientTest.java, typespec-tests/src/test/java/com/server/path/single/SingleClientTest.java
Link https://github.com/Azure/autorest.java/issues/2057
https://azure.github.io/cadl-ranch/
=> cadl-ranch, add more tests

customization-base/src/main/resources/pom.xml, customization-tests/pom.xml, eng/versioning/sync_versions.py, fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPomMapper.java, javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, pom.xml, protocol-sdk-integration-tests/eng/versioning/version_client.txt, typespec-tests/pom.xml
part of preparation for https://github.com/Azure/autorest.java/pull/2098
=> client, refactor Project, move all dependency related info to Project.Dependency enum

typespec-tests/src/test/java/com/_specs_/azure/clientgenerator/core/internal/InternalTests.java
main.tsp:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/client-generator-core/internal/main.tsp
=> tsp, add test for refined internal

fluentgen/pom.xml, fluentgen/src/test/java/com/azure/autorest/fluent/checker/JavaFormatterTests.java
refresh latest master in https://github.com/weidongxu-microsoft/google-java-format
and released 1.17.0-beta.1 on internal maven repo
=> mgmt, update google-java-format to latest 1.17

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodSampleTemplate.java, javagen/src/main/java/com/azure/autorest/template/example/ClientInitializationExampleWriter.java, javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
part of https://github.com/Azure/autorest.java/issues/2068
Mainly refactor, extract client initialization code to a separate class.
generated samples:
https://github.com/Azure/azure-sdk-for-java/commit/c379b2c186d6c1e37232c0029bd812e66c603dc1
=> convenience sample, write client initialization

eng/pipelines/ci-typespec-java-dev-nightly.yaml, typespec-extension/package.json, typespec-tests/bump_deps.ts
script now *add* "overrides" section.
cadl-ranch PR https://github.com/Azure/cadl-ranch/pull/321
=> tsp, update nightly build script

typespec-extension/src/code-model-builder.ts, typespec-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java, typespec-tests/src/main/java/com/cadl/builtin/BuiltinClient.java, typespec-tests/src/main/java/com/cadl/builtin/implementation/BuiltinClientImpl.java, typespec-tests/src/main/java/com/cadl/builtin/models/Encoded.java, typespec-tests/src/test/java/com/cadl/builtin/EncodeTests.java, typespec-tests/tsp/builtin.tsp
skip UnixTimestamp, as I am not sure whether it be long or string on wire.
=> tsp, support other encode

javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
swagger error, response be "string" on pageable.
=> client, fix potential NPE in error handling

typespec-extension/src/code-model-builder.ts, typespec-tests/src/main/java/com/parameters/collectionformat/implementation/QueriesImpl.java, typespec-tests/src/test/java/com/parameters/collectionformat/CollectionFormatClientTest.java
That bug in compiler still not fixed. https://github.com/microsoft/typespec/issues/1870
Use case in typespec-java for now.
=> tsp, use cast to support ssv etc.

typespec-extension/changelog.md, typespec-tests/src/test/java/com/parameters/bodyoptionality/BodyTests.java
no update about version range so far.
also add one missed api call in test.
=> tsp, prepare release 0.8.0

eng/pipelines/post-publish-sdk.yaml, eng/sdk/sync_sdk.py
relate https://github.com/Azure/autorest.java/issues/1504
pipeline https://dev.azure.com/azure-sdk/internal/_build?definitionId=6270
Sample PR from pipeline https://github.com/Azure/azure-sdk-for-java/pull/35655
the code above uses a wrong namespace, because of an outdated commit id.
This PR updates the commit id on openai
https://github.com/Azure/azure-sdk-for-java/pull/35654
=> eng, pipeline to update sdk repo

fluentgen/src/main/java/com/azure/autorest/fluent/mapper/MockTestParser.java, javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishMarketTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotSalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/FishTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/GoblinsharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyBaseTypeTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyDerivedTypeTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/ReadonlyObjTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SawsharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SharkTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
1st commit to fix a rare case of e.g. "csv of double"
2nd commit try fix error of "missing required property" in https://github.com/Azure/autorest.java/issues/1861, tested to be good on datafactory and mobilenetwork
=> mgmt, fix test gen issue

androidgen/src/main/java/com/azure/autorest/android/model/clientmodel/AndroidServiceClient.java, androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceClientBuilderTemplate.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/PipelinePolicyDetails.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java, typespec-extension/src/main/java/com/azure/typespec/mapper/TypeSpecServiceClientMapper.java, typespec-extension/src/operation-utils.ts, typespec-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersClientBuilder.java, typespec-tests/tspconfig.yaml
fix https://github.com/Azure/autorest.java/issues/2216
=> tsp, corner case of "client-request-id" header for RequestIdPolicy

typespec-extension/src/emitter.ts
link https://github.com/Azure/autorest.java/pull/2204
=> tsp, avoid calling sync func in async onEmit func

javagen/src/main/java/com/azure/autorest/template/ProtocolTestBaseTemplate.java
e.g.
```java
package com.cadl.naming.generated;
// The Java test files under 'generated' package are generated for your reference.
// If you wish to modify these files, please copy them out of the 'generated' package, and modify there.
// See https://aka.ms/azsdk/dpg/java/tests for guide on adding a test.
import com.azure.core.http.HttpClient;
import com.azure.core.http.policy.HttpLogDetailLevel;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.core.test.TestBase;
import com.azure.core.test.TestMode;
import com.azure.core.util.Configuration;
import com.cadl.naming.NamingClient;
import …
```
=> dpg, comment in TestBase as guide

javagen/src/test/java/com/azure/autorest/template/TestProxyAssertsTemplateTests.java
due to https://github.com/Azure/autorest.java/pull/2222
=> eng, fix merge conflict

.github/workflows/fluent-test-gen-all.yml, .github/workflows/pre-release-typespec.yml
1. use larger timeout in daily ci
2. do not upload assert with typespec-java
=> eng, update action and ci

fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ErrorTypeNormalization.java
fix https://github.com/Azure/autorest.java/issues/2241
we had to clone the error model, one rename to `ManagementError` for exception, another for model inheritance.
=> mgmt, mitigate the issue of ErrorResponse used in model

fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ErrorTypeNormalization.java
fix https://github.com/Azure/autorest.java/issues/2241
now, it generates such:
(instead of `CommonPostActionResponseForDeviceUpdateInner extends ResponseError`)
```java
@Fluent
public final class CommonPostActionResponseForDeviceUpdateInner {
/*
* Gets the configuration state.
*/
@JsonProperty(value = "configurationState", access = JsonProperty.Access.WRITE_ONLY)
private ConfigurationState configurationState;
/*
* List of ARM Resource IDs for which the given action applied successfully.
*/
@JsonProperty(value = "successfulDevices")
private List<String> successfulDevices;
/*
* List of ARM Resource IDs for which the given action failed to apply.
*/
@JsonProperty(value = "failedDevices")
private List<String> failedDevices;
/*
* The error object.
*/
@JsonProperty(value = "error")
private …
```
=> mgmt, use composite instead of inherit, if model inherit ErrorResponse

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java, javagen/src/main/java/com/azure/autorest/template/example/ModelExampleWriter.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DictionaryWrapperTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
fix for https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2952250&view=logs&j=9046e4d6-dade-5eef-a661-231b150a1dac&t=7e2e9f17-cd01-5305-2bbb-6ad75d043791
=> mgmt, fix a javadoc issue on manager

typespec-extension/src/code-model-builder.ts
test case is under develop in cadl-ranch
=> tsp, support discriminatorProperty as EnumMember

Generate.ps1, fluent-tests/gen_all.py, fluent-tests/prepare-tests.bat, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentPomTemplate.java, javagen/src/main/java/com/azure/autorest/template/PomTemplate.java, protocol-sdk-integration-tests/test.py, typespec-extension/src/code-model-builder.ts, typespec-tests/src/main/java/com/cadl/enumservice/models/Name.java
mgmt lite now have quite some stable releases.
It is common that their preview api-version has breaking changes (compared to prior stable. Ignore that in automation. It is not a big concern whether beta breaks or not.
=> mgmt, skip revapi if beta

typespec-extension/.eslintrc.cjs, typespec-extension/package.json, typespec-extension/readme.md, typespec-tests/.prettierrc.yaml, typespec-tests/package.json, typespec-tests/tsp/flatten.tsp, typespec-tests/tsp/multiple-apiversion.tsp, typespec-tests/tsp/multiple-content-types.tsp, typespec-tests/tsp/protocol-api-convenient-api.tsp, typespec-tests/tsp/response.tsp, typespec-tests/tsp/special-headers.tsp, typespec-tests/tsp/union.tsp, typespec-tests/tsp/versioning.tsp
seems no breaking changes from typespec/typespec-azure
=> tsp, upgrade compiler 0.47

fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
for https://github.com/Azure/sdk-release-request/issues/4375 and https://github.com/Azure/azure-sdk-for-java/pull/36306
=> mgmt, deploymentStack in azure-resourcemanager-resources

javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java, typespec-extension/changelog.md, typespec-extension/src/code-model-builder.ts, typespec-tests/src/main/java/com/cadl/enumservice/EnumServiceAsyncClient.java, typespec-tests/src/main/java/com/cadl/enumservice/EnumServiceClient.java, typespec-tests/src/main/java/com/cadl/enumservice/implementation/EnumServiceClientImpl.java, typespec-tests/src/main/java/com/cadl/enumservice/models/Operation.java, typespec-tests/tsp/enum.tsp
link https://github.com/Azure/autorest.java/issues/2273
=> tsp, support EnumMember as type

azure-dataplane-tests/pom.xml, azure-tests/pom.xml, customization-base/src/main/resources/pom.xml, customization-tests/pom.xml, fluent-tests/pom.xml, fluentnamer/pom.xml, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, protocol-sdk-integration-tests/eng/versioning/version_client.txt, protocol-tests/pom.xml, typespec-extension/changelog.md, typespec-tests/pom.xml, vanilla-tests/pom.xml
azure-identity 1.10.1 released but incr PR not merged.
=> eng, bump core libs to latest, prepare 0.8.12

package.json, typespec-tests/package.json
npm lib should have fixed the issue https://github.com/ljharb/set-function-name/commit/db2eda8da4c8aecfad01739000bbd63d04a8e8cf
=> eng, remove functions-have-names

fluent-tests/prepare-tests.bat, fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ResourceTypeNormalization.java, package.json
v3+ https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/types.json#L29
Sometimes, the systemData was not extracted.
=> mgmt, bug fix on lost properties from ProxyResource/Resource

fluentgen/src/main/java/com/azure/autorest/fluent/template/UtilsTemplate.java, fluentgen/src/main/resources/Utils_PagedIterableImpl.txt, fluentgen/src/main/resources/Utils_getValueFromIdByParameterName.txt
issue: https://github.com/Azure/azure-sdk-for-java/pull/36864
1. add private constructor to Utils
2. remove unnecessary generics info
test generation for billing: https://github.com/Azure/azure-sdk-for-java/pull/36875/files#diff-9ec99b447a43b7c7731cd9ab50f79499a681ba74b675229c94b99637d37202a2
=> mgmt, Utils add private ctor

extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
Actually, any value not in current enum would do. But make it explicit.
=> mgmt, add DISABLED to model flatten

postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java
fix https://github.com/Azure/autorest.java/issues/2319
=> partial update, fix bug of getting wrong base directory

typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json
This reverts commit 94e9ae5de0510c341ae6b6994727654a90e1de94.
=> Revert "verify createSdkContext works"

androidgen/pom.xml, azure-dataplane-tests/pom.xml, customization-base/pom.xml, fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java, javagen/pom.xml, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java, postprocessor/pom.xml, protocol-tests/pom.xml, typespec-extension/pom.xml, typespec-tests/pom.xml, vanilla-tests/pom.xml
for code like
```java
public Boolean showInFeed() {
return this.innerProperties() == null ? EMPTY_BYPE_ARRAY : this.innerProperties().showInFeed();
}
```
=> mgmt, fix empty byte array under flatten properties

fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java, javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java, package.json
it would include a bug fix in data-plane pagination; a bug fix on partial-update in the case of relative output-folder.
mgmt would include graalvm, and some other fixes.
=> prepare 4.1.22

javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java, javagen/src/main/java/com/azure/autorest/model/clientmodel/examplemodel/BinaryDataNode.java, javagen/src/main/java/com/azure/autorest/template/example/ModelExampleWriter.java, javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java, javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java, typespec-tests/src/samples/java/com/cadl/multicontenttypes/generated/SingleContentTypeUploadImageForSingleContentType.java, typespec-tests/src/test/java/com/cadl/multicontenttypes/generated/SingleContentTypeUploadImageForSingleContentTypeTests.java, typespec-tests/tsp/examples/SingleContentType_uploadImageForSingleContentType.json
For BinaryData as ClientType, generate sample code:
```java
BinaryData.fromBytes(exampleValue.toString().getBytes());
```
=> tsp, fix binarydata example

javagen/src/main/java/com/azure/autorest/util/ReturnTypeDescriptionAssembler.java
pick from https://github.com/Azure/autorest.java/pull/2360
=> client, cache for ReturnTypeDescriptionAssembler

azure-dataplane-tests/src/main/java/com/azure/ai/formrecognizer/documentanalysis/implementation/FormRecognizerClientImpl.java, javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java, protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java, protocol-tests/src/main/java/fixtures/endpointlro/implementation/LROsImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java, protocol-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java, protocol-tests/src/main/java/fixtures/specialheader/implementation/HeadersImpl.java, typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/implementation/RpcClientImpl.java, typespec-tests/src/main/java/com/_specs_/azure/core/lro/rpc/legacy/implementation/LegacyClientImpl.java, typespec-tests/src/main/java/com/_specs_/azure/core/lro/standard/implementation/StandardClientImpl.java, vanilla-tests/src/main/java/fixtures/lro/LRORetrys.java, vanilla-tests/src/main/java/fixtures/lro/LROs.java, vanilla-tests/src/main/java/fixtures/lro/LROsCustomHeaders.java, vanilla-tests/src/main/java/fixtures/lro/LrosaDs.java
follow up pr on https://github.com/Azure/autorest.java/pull/2349#discussion_r1371344306
=> [lro] polling strategy not generate the line when serviceVersion and endpoint is null

eng/versioning/external_dependencies.txt, fluent-tests/pom.xml, javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java, javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java, javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java, javagen/src/main/java/com/azure/autorest/template/ServiceClientTemplate.java, javagen/src/main/java/com/azure/autorest/template/TemplateHelper.java, typespec-extension/src/main/java/com/azure/typespec/Main.java
remove use of `KeyCredentialTrait`
also avoid 3rd param in `RequestOptions.addQueryParam`
=> tsp, unbranded, branch for Trait and addQueryParam

androidgen/pom.xml, azure-dataplane-tests/pom.xml, azure-tests/pom.xml, customization-base/CHANGELOG.md, customization-base/README.md, customization-base/pom.xml, customization-tests/pom.xml, customization-tests/swagger/pom.xml, eng/pipelines/ci.yaml, eng/pipelines/fluent_integration.yaml, extension-base/pom.xml, fluent-tests/pom.xml, fluentgen/pom.xml, fluentgen/src/main/resources/spotless-pom.xml, fluentnamer/pom.xml, javagen/pom.xml, partial-update-tests/pom.xml, partial-update/pom.xml, pom.xml, postprocessor/pom.xml, postprocessor/src/main/resources/readme/pom.xml, preprocessor/pom.xml, protocol-resilience-test/pom.xml, protocol-tests/pom.xml, typespec-extension/pom.xml, typespec-extension/src/main/resources/spotless-pom.xml, typespec-tests/pom.xml, vanilla-tests/pom.xml
Updates versions of Autorest libraries in preparation for release.
=> Update versions for release

Generate.ps1, typespec-tests/Generate.ps1
Parallelizes `/Generate.ps1` and `/typespec-tests/Generate.ps1`.
=> Parallelize Generate scripts

typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-extension/src/prenamer/formatter.ts, typespec-tests/package.json
bump prettier to ~3, to fix nightly build
=> tsp, bump npm dependencies

eng/versioning/external_dependencies.txt, typespec-extension/pom.xml, typespec-tests/readme.md
link https://github.com/Azure/autorest.java/pull/2432
=> client, sync ch.qos.logback:logback-classic with SDK repo

typespec-tests/src/test/java/com/projection/projectedname/ProjectedNameClientTest.java
Add test cases for for tsp, cadl-ranch Projection.ProjectedName
=> Add test cases for for tsp, cadl-ranch Projection.ProjectedName

typespec-tests/src/test/java/com/type/property/additionalproperties/ExtendsTests.java, typespec-tests/src/test/java/com/type/property/additionalproperties/IsFloatClientTest.java, typespec-tests/src/test/java/com/type/property/additionalproperties/IsModelArrayClientTest.java, typespec-tests/src/test/java/com/type/property/additionalproperties/IsModelClientTest.java, typespec-tests/src/test/java/com/type/property/additionalproperties/IsStringClientTest.java, typespec-tests/src/test/java/com/type/property/additionalproperties/IsUnknownClientTest.java, typespec-tests/src/test/java/com/type/property/valuetypes/LiteralTests.java, typespec-tests/src/test/java/com/type/property/valuetypes/UnionTests.java
1. Add test cases for [issue#2443](https://github.com/Azure/autorest.java/issues/2443)
2. The `get` request did not respond for a long time, so disabled the test case `ExtendsTests#testExtendsModelArrayClient`.
=> Add test case for issue#2443

javagen/src/main/java/com/azure/autorest/mapper/DictionaryMapper.java, typespec-tests/src/main/java/com/cadl/builtin/BuiltinAsyncClient.java, typespec-tests/src/main/java/com/cadl/builtin/BuiltinClient.java, typespec-tests/src/main/java/com/cadl/builtin/implementation/BuiltinOpsImpl.java, typespec-tests/src/main/java/com/cadl/builtin/models/Builtin.java, typespec-tests/src/main/java/com/type/dictionary/NullableFloatValueAsyncClient.java, typespec-tests/src/main/java/com/type/dictionary/NullableFloatValueClient.java, typespec-tests/src/main/java/com/type/dictionary/implementation/NullableFloatValuesImpl.java, typespec-tests/tsp/flatten.tsp
when flattened parameter get longer than 6...
=> tsp, set MapType element IType as nullable, if nullableItems=true

typespec-extension/changelog.md, typespec-tests/readme.md
with multipart/form-data support.
=> tsp, prepare 0.12.1

typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-extension/src/type-utils.ts, typespec-tests/package.json
the global `service.version` is removed from `@scenarioService`
=> tsp, bump cadl-ranch

typespec-extension/src/main/java/com/azure/typespec/Main.java, typespec-tests/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-armresourceprovider-generated/proxy-config.json, typespec-tests/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-armresourceprovider-generated/reflect-config.json
Add pom.xml, readme.md and changelog.md to make generated SDK work at least.
Currently package tag is null in all these files. Will fix in https://github.com/Azure/autorest.java/issues/2518.
=> mpg, generate pom.xml, readme and changelog

typespec-extension/src/code-model-builder.ts
Seems getLroMetadata is working in typespec-azure-core 0.37.2.
=> mpg, remove lro workaround, use getLroMetadata

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/readme.md, typespec-extension/src/code-model-builder.ts, typespec-extension/src/main/java/com/azure/autorest/TypeSpecPlugin.java, typespec-tests/package.json, typespec-tests/src/main/java/com/cadl/naming/models/BytesData.java, typespec-tests/tsp/naming.tsp
also include the support for `@clientName`
=> tsp, upgrade compiler 0.52

fluentgen/src/main/java/com/azure/autorest/fluent/template/SampleTemplate.java, postprocessor/src/main/java/com/azure/autorest/postprocessor/implementation/CodeFormatterUtil.java
It was removed by Alan when moving to Spotless :-(
Now it is back to in-memory format, we should be able to add it back.
effect
```diff
diff --git a/sdk/datafactory/azure-resourcemanager-datafactory/SAMPLE.md b/sdk/datafactory/azure-resourcemanager-datafactory/SAMPLE.md
index b5e2a23ceb8..5f741e5933e 100644
--- a/sdk/datafactory/azure-resourcemanager-datafactory/SAMPLE.md
+++ b/sdk/datafactory/azure-resourcemanager-datafactory/SAMPLE.md
@@ -176,22 +176,27 @@
import com.azure.resourcemanager.datafactory.models.RunFilterParameters;
import java.time.OffsetDateTime;
-import java.time.format.DateTimeFormatter;
/**
* Samples for ActivityRuns QueryByPipelineRun.
*/
public final class ActivityRunsQueryByPipelineRunSamples {
/*
-     * x-ms-original-file: …
```
=> mgmt, format code before write to SAMPLE.md

javagen/src/main/java/com/azure/autorest/template/ConvenienceAsyncMethodTemplate.java, typespec-tests/src/main/java/com/cadl/response/ResponseAsyncClient.java, typespec-tests/src/main/java/com/cadl/response/ResponseClient.java, typespec-tests/src/main/java/com/cadl/response/implementation/ResponseClientImpl.java, typespec-tests/tsp/response.tsp
fix https://github.com/Azure/autorest.java/issues/2578
code https://github.com/Azure/autorest.java/pull/2580/commits/5d3928e56ad13d2f237d5e3bf14e89192e5bb909
=> tsp, support paged scalar

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json, typespec-tests/src/main/java/com/cadl/flatten/FlattenAsyncClient.java, typespec-tests/src/main/java/com/cadl/flatten/FlattenClient.java, typespec-tests/src/main/java/com/cadl/flatten/implementation/FlattenClientImpl.java, typespec-tests/src/main/java/com/cadl/flatten/implementation/models/SendLongRequest.java, typespec-tests/src/main/java/com/cadl/flatten/implementation/models/SendRequest.java, typespec-tests/src/main/java/com/cadl/flatten/models/SendLongOptions.java, typespec-tests/src/main/java/com/cadl/flatten/models/Status.java, typespec-tests/src/main/java/com/cadl/flatten/models/TodoItem.java, typespec-tests/src/samples/java/com/cadl/flatten/generated/FlattenOpSendLong.java, typespec-tests/src/test/java/com/cadl/flatten/FlattenTests.java, typespec-tests/src/test/java/com/cadl/flatten/generated/FlattenOpSendLongTests.java, typespec-tests/tsp/examples/2022-06-01-preview/FlattenOp_SendLong.json, typespec-tests/tsp/flatten.tsp
code https://github.com/Azure/autorest.java/pull/2612/commits/196d1705d6b3d6b66f20684a19bb53a834ab5c5e
Error happens when read-only property or constant property in the model get flattened as well.
There could be more bug, e.g. a model (that extends another model) get flattened...
=> tsp, bug fix on grouping

javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodExampleMapper.java, javagen/src/main/java/com/azure/autorest/util/CodeNamer.java, preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java
=> client, remove duplicate code in 2 CodeNamer

typespec-extension/src/code-model-builder.ts
=> tsp, bug fix, isDisciminator not set to discriminator property

typespec-extension/src/code-model-builder.ts, typespec-extension/src/emitter.ts, typespec-tests/Generate.ps1, typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/CustomTemplateResourceInterfacesClient.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/CustomTemplateResourceImpl.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/CustomTemplateResourceInterfacesClientImpl.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/models/CustomTemplateResource.java, typespec-tests/tsp/arm.tsp
https://github.com/Azure/autorest.java/issues/2633
As a first step, add a flag for disabling etag headers grouping.
=> Add flag for etag grouping

eng/pipelines/publish-autorest-java.yaml, eng/pipelines/templates/stages/1es-redirect.yml, eng/pipelines/variables/image.yml
Successful run w/o publish: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3643180&view=logs&j=b996a615-b315-504a-0a4a-ff0f9eb394bb&t=b996a615-b315-504a-0a4a-ff0f9eb394bb
=> 1ES pipeline migration

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json
=> tsp, bump dependency for 0.15.9

typespec-tests/src/test/java/com/payload/multipart/MultipartTests.java, typespec-tests/src/test/java/com/server/versions/VersionedTests.java
Add 2 tests for cadl-ranch 0.13.8
=> tsp, add 2 simple test

typespec-extension/src/code-model-builder.ts
tcgc bug https://github.com/Azure/typespec-azure/issues/699
=> tsp, guard against TCGC bug

typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json
fix https://github.com/Azure/autorest.java/issues/2716
=> all client, upgrade tcgc and support versioning

javagen/src/main/java/com/azure/autorest/template/ConvenienceMethodTemplateBase.java, typespec-extension/src/code-model-builder.ts
Bug fix, should use `EnumType.getToMethodName`
=> tsp, bug fix for enum type in convenience method

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/readme.md, typespec-extension/src/code-model-builder.ts, typespec-extension/src/emitter.ts, typespec-tests/Generate.ps1, typespec-tests/package.json, typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/models/CustomTemplateResourceInner.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/fluent/models/CustomTemplateResourceProperties.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/ArmResourceProviderClientImpl.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/implementation/CustomTemplateResourceImpl.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/models/CustomTemplateResource.java, typespec-tests/src/main/java/com/cadl/armresourceprovider/models/CustomTemplateResourcePatch.java, typespec-tests/src/main/java/com/cadl/versioning/VersioningAsyncClient.java, typespec-tests/src/main/java/com/cadl/versioning/VersioningClient.java, typespec-tests/src/main/java/com/cadl/versioning/implementation/VersioningOpsImpl.java, typespec-tests/src/main/java/com/cadl/versioning/models/ExportedResource.java, typespec-tests/tsp/versioning.tsp
fix https://github.com/Azure/autorest.java/issues/2720
1. support `api-version` in tspconfig.yaml
2. bump tcgc to 0.41.6
3. bump typespec-java to 0.15.13 for release
=> bump tcgc and typespec-java, support `api-version`

eng/sdk/sync_sdk.py, fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/FluentProject.java, typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json
=> tsp, mgmt, no tag line in readme/changelog/pom, if generated from typespec

typespec-tests/package.json
=> tsp, fix tcgc to 0.42.0 in test

eng/sdk/sync_sdk.py, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json
test on https://github.com/Azure/azure-sdk-for-java/pull/40121
=> eng, update script for sync sdk for mgmt

typespec-tests/src/test/java/com/azure/arm/models/resources/ArmResourceTest.java
Add test cases for tsp, cadl-ranch add test case for ARM
=> tsp, cadl-ranch add test case for ARM

typespec-tests/src/test/java/com/type/array/NullableBooleanValueClientTest.java, typespec-tests/src/test/java/com/type/array/NullableInt32ValueClientTest.java, typespec-tests/src/test/java/com/type/array/NullableModelValueClientTest.java, typespec-tests/src/test/java/com/type/array/NullableStringValueClientTest.java
relate to [issue#2829](https://github.com/Azure/autorest.java/issues/2829)
Add test case for Type/Array/NullableBooleanValue, Type/Array/NullableInt32Value, Type/Array/NullableModelValue, Type/Array/NullableStringValue
=> tsp, add test for cadl-ranch Type/Array

typespec-tests/src/test/java/com/type/property/nullable/CollectionsStringClientTest.java
relate to [issue#2831](https://github.com/Azure/autorest.java/issues/2831)
Add test ceses for tsp, add test for cadl-ranch Type/Property/Nullable
=> tsp, add test for cadl-ranch Type/Property/Nullable

typespec-extension/src/code-model-builder.ts, typespec-extension/src/operation-utils.ts, typespec-tests/src/main/java/com/cadl/optional/OptionalAsyncClient.java, typespec-tests/src/main/java/com/cadl/optional/OptionalClient.java, typespec-tests/src/main/java/com/cadl/optional/implementation/OptionalOpsImpl.java, typespec-tests/src/main/java/com/cadl/specialheaders/EtagHeadersOptionalBodyAsyncClient.java, typespec-tests/src/main/java/com/cadl/specialheaders/EtagHeadersOptionalBodyClient.java, typespec-tests/src/main/java/com/cadl/specialheaders/implementation/EtagHeadersOptionalBodiesImpl.java, typespec-tests/src/main/java/com/parameters/bodyoptionality/OptionalExplicitAsyncClient.java, typespec-tests/src/main/java/com/parameters/bodyoptionality/OptionalExplicitClient.java, typespec-tests/src/main/java/com/parameters/bodyoptionality/implementation/OptionalExplicitsImpl.java
code https://github.com/Azure/autorest.java/pull/2836/commits/706a4234663348a01fb75c95344c2b72cf0ea8e3
=> tsp, set request mediaTypes from body.contentTypes

fluentgen/src/main/resources/Readme.txt, package-lock.json, package.json
we also need to update https://aka.ms/azsdk/java/mgmt related docs.
=> mgmt, update readme template, avoid AZURE_CLIENT_SECRET

postprocessor/src/main/java/com/azure/autorest/postprocessor/implementation/CodeFormatterUtil.java
logging for diagnose the cause of such format failure
=> client, include file content on format error

typespec-tests/package.json, typespec-tests/src/test/java/com/azure/resourcemanager/models/resources/ArmResourceTest.java
https://github.com/Azure/autorest.java/pull/2864#discussion_r1680450455
=> bump cadl-ranch-specs, enable arm update test

typespec-tests/src/test/java/com/_specs_/azure/core/model/ModelClientTests.java, typespec-tests/src/test/java/com/azure/resourcemanager/models/commontypes/managedidentity/ManagedIdentityManagerTests.java, typespec-tests/src/test/java/com/azure/resourcemanager/models/resources/ArmResourceTest.java, typespec-tests/src/test/java/com/type/model/visibility/AutomaticClientTest.java, typespec-tests/src/test/java/com/type/property/optional/PlaindateClientTests.java, typespec-tests/src/test/java/com/type/property/optional/PlaintimeClientTests.java
1. Add test cases for Azure/ResourceManager/Models/CommonTypes/ManagedIdentity
2. Add test cases for Type/Property/Optional/Plaindate
3. Add test cases for Type/Property/Optional/Plaintime
4. Add test cases for azure/core/model
=> tsp, add test for cadl-ranch

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json
code: 88f6c1cd86704f2069ae124824ed6bdc31dbbcc0
logics change mainly on:
1. built in types change
2. multipart form data handling logic change
=> tsp, upgrade TCGC version to 0.44.2

javagen/src/main/java/com/azure/autorest/Javagen.java, javagen/src/main/java/com/azure/autorest/template/example/ProtocolTestWriter.java, typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json, typespec-tests/src/test/java/com/authentication/oauth2/generated/OAuth2ClientTestBase.java, typespec-tests/src/test/java/com/authentication/union/generated/UnionClientTestBase.java
bug fix for feature https://github.com/Azure/autorest.java/issues/2886
I will add a test case in cadl-ranch.
=> tsp, bug fix, remove SubNamespace from operation group name

fluent-tests/Initialize-Tests.ps1, fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java, javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
fix automation failure: https://github.com/Azure/azure-rest-api-specs/pull/29981/checks?check_run_id=28499121687
`value` and `nextLink` properties are defined in parent model:
https://github.com/Azure/azure-rest-api-specs/blob/0ed912fdfaffd5c81eb86b79df0e3b31d978d795/specification/billing/resource-manager/Microsoft.Billing/stable/2024-04-01/billingSavingsPlan.json#L552-L566
=> mgmt, fix pageable model inheritance

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/src/code-model-builder.ts, typespec-tests/package.json, typespec-tests/src/main/java/com/cadl/flatten/FlattenAsyncClient.java, typespec-tests/src/main/java/com/cadl/flatten/FlattenClient.java, typespec-tests/src/main/java/com/cadl/flatten/implementation/FlattenClientImpl.java, typespec-tests/src/main/java/com/cadl/flatten/implementation/models/SendRequest.java, typespec-tests/src/samples/java/com/cadl/flatten/generated/FlattenOpSend.java, typespec-tests/src/test/java/com/cadl/flatten/FlattenTests.java, typespec-tests/src/test/java/com/cadl/flatten/generated/FlattenOpSendTests.java, typespec-tests/tsp/examples/2022-06-01-preview/FlattenOp_Send.json, typespec-tests/tsp/flatten.tsp
bug reported by openai
code change https://github.com/Azure/autorest.java/pull/2911/commits/5efc992ccdd4a0dccc4364293f9c5e286ed8a969
SDK repo change seems not due to this PR https://github.com/Azure/azure-sdk-for-java/pull/41497
=> tsp, bug fix, flatten body property that having same serialized name with path parameter

typespec-tests/src/test/java/com/azure/resourcemanager/models/resources/ArmResourceTest.java
Fix the test case `testTopLevelTrackedResource` to support resource action.
=> tsp, add test to support resource action

extension-base/src/main/java/com/azure/autorest/extension/base/jsonrpc/Connection.java, typespec-extension/src/main/java/com/azure/autorest/TypeSpecPlugin.java, typespec-extension/src/main/java/com/azure/typespec/Main.java
- fix https://github.com/Azure/autorest.java/issues/2923
- cause: https://github.com/Azure/autorest.java/issues/2923#issuecomment-2306541926
- pipeline succeeded: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4075989&view=logs&j=f0ea25ea-b7e0-596e-c691-94ee910ce8e9&t=4036877c-0fde-50d1-2f32-52f8f5ad201b
=> tsp mgmt, fix stuck for some pipelines

package-lock.json, package.json
=> release autorest 4.1.36

typespec-tests/Setup.ps1
We've switched to using microsoft/typespec from core, update test setup script.
=> fix Setup.ps1 for typespec-tests

package-lock.json, package.json
Include features e.g.
- non-string extensible enum
- `BearerTokenAuthenticationPolicy` that supports CAE
=> autorest, prepare release 4.1.40

typespec-extension/readme.md
=> tsp, update readme of typespec-java

typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json
=> eng, bump tcgc 0.49.1

fluent-tests/Initialize-Tests.ps1, fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
- https://github.com/microsoft/typespec/pull/5510
=> mgmt, use `byte[0]` for client implementations

fluent-tests/pom.xml, protocol-sdk-integration-tests/eng/versioning/version_client.txt, typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-extension/readme.md, typespec-tests/package.json, typespec-tests/pom.xml
test sync https://github.com/Azure/azure-sdk-for-java/pull/43811
=> eng, bump core, prepare release 0.27.2

Build-AutoRest.ps1, readme.md
many doc is copied from https://github.com/Azure/typespec-azure/blob/main/CONTRIBUTING.md
=> doc for submodule, and convenience script to build for Autorest

typespec-extension/package-lock.json, typespec-extension/package.json
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/common/scripts/typespec/New-EmitterPackageJson.ps1#L34-L35
test https://github.com/Azure/azure-sdk-for-java/pull/43839/files
=> eng, add typespec-liftr-base

typespec-tests/src/main/java/azure/resourcemanager/commonproperties/CommonPropertiesManager.java, typespec-tests/src/main/java/azure/resourcemanager/operationtemplates/OperationTemplatesManager.java, typespec-tests/src/main/java/azure/resourcemanager/resources/ResourcesManager.java, typespec-tests/src/main/java/tsptest/armresourceprovider/ArmResourceProviderManager.java, typespec-tests/src/main/java/tsptest/armstreamstyleserialization/ArmStreamStyleSerializationManager.java, typespec-tests/src/main/resources/azure-resourcemanager-armresourceprovider-generated.properties, typespec-tests/src/main/resources/azure-resourcemanager-armstreamstyleserialization-generated.properties, typespec-tests/src/main/resources/azure-resourcemanager-commonproperties-generated.properties, typespec-tests/src/main/resources/azure-resourcemanager-operationtemplates-generated.properties, typespec-tests/src/main/resources/azure-resourcemanager-resources-generated.properties
- sync from typespec repo: https://github.com/microsoft/typespec/pull/5914
=> mgmt, add properties file

fluentgen/src/main/resources/simplelogger.properties, javagen/src/main/resources/simplelogger.properties, typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json, typespec-tests/tsp/response.tsp
https://github.com/microsoft/typespec/pull/6300
=> eng, sync PR 6300

eng/pipelines/ci.yaml
after https://github.com/Azure/autorest.java/issues/3061
=> eng, revert skip diff

vanilla-tests/src/test/java/fixtures/bodycomplex/generated/BooleanWrapperTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishMarketTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotSalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SalmonTests.java, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
- microsoft/typespec PR: https://github.com/microsoft/typespec/pull/6969
=> mgmt, sync 6969 for HEAD mock test

package-lock.json, package.json, typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json, vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
- typespec PR: https://github.com/microsoft/typespec/pull/6995
=> mgmt, sync PR 6995, prepare release autorest.java/typespec-java for mock test fix

docs/developer/code-generator-mode.md, docs/developer/typespec/readme.md, typespec-tests/readme.md
update docs/developer/typespec/readme.md
=> doc, add notice to docs/developer/typespec/readme.md

package-lock.json, package.json, typespec-tests/src/main/java/tsptest/armresourceprovider/fluent/ManagedMaintenanceWindowStatusOperationsClient.java, typespec-tests/src/main/java/tsptest/armresourceprovider/fluent/ModelInterfaceSameNamesClient.java, typespec-tests/src/main/java/tsptest/armresourceprovider/implementation/ManagedMaintenanceWindowStatusOperationsClientImpl.java, typespec-tests/src/main/java/tsptest/armresourceprovider/implementation/ManagedMaintenanceWindowStatusOperationsImpl.java, typespec-tests/src/main/java/tsptest/armresourceprovider/implementation/ModelInterfaceSameNamesClientImpl.java, typespec-tests/src/main/java/tsptest/armresourceprovider/implementation/ModelInterfaceSameNamesImpl.java, typespec-tests/src/main/java/tsptest/armresourceprovider/models/ManagedMaintenanceWindowStatusOperations.java, typespec-tests/src/main/java/tsptest/armresourceprovider/models/ModelInterfaceSameNames.java, typespec-tests/tsp/arm.tsp
- sync https://github.com/microsoft/typespec/pull/7629
- prepare autorest.java 4.1.52 release
- duplicate sample file fix
- deleteByResourceGroup fix
=> sync typespec 7629, prepare autorest.java release

Build-TypeSpec.ps1, typespec-extension/changelog.md, typespec-extension/package.json, typespec-extension/src/options.ts, typespec-tests/tspconfig.yaml
for https://github.com/microsoft/typespec/pull/7745
=> eng, sync 7745 for JFR profiling

azure-dataplane-tests/src/main/java/com/azure/data/schemaregistry/implementation/SchemaGroupsOperationsImpl.java, azure-dataplane-tests/src/main/java/com/azure/data/schemaregistry/implementation/SchemasImpl.java, protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java
for PR https://github.com/microsoft/typespec/pull/7888
nightly pass on this https://dev.azure.com/azure-sdk/public/_build/results?buildId=5082996&view=results
=> eng, sync the fix for nightly build

readme.md, typespec-extension/src/options.ts, typespec-tests/Generate.ps1, typespec-tests/src/main/java/tsptest/armstreamstyleserialization/fluent/models/FunctionConfiguration.java, typespec-tests/src/test/java/tsptest/armstreamstyleserialization/StreamStyleSerializationTests.java
follow-up on https://github.com/microsoft/typespec/pull/7991
=> Update options.ts for rename-model

typespec-extension/changelog.md, typespec-extension/package-lock.json, typespec-extension/package.json, typespec-tests/package.json
fix https://github.com/Azure/autorest.java/issues/3185
=> eng, prepare release 0.32.2
